### ISSUE TITLE
won't apply load order

### ISSUE THREAD

**Issue by gdog361** [loot/loot#961] opened 2018-06-02 21:06 UTC
I've never had an issue until this update, it sorts my load order but wont allow me to apply it, ive tried uninstalling and doing a fresh install, deleting the app data folder for LOOT as well as checking and double checking my plugins file WAS NOT set to read only. anyways here s my error message from the debug log
 ```
[16:59:24.815840] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[16:59:24.856187] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[16:59:31.956998] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[16:59:31.957124] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[16:59:31.958643] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\Bobby\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)

```

**Comment by WrinklyNinja** [comment] 2018-06-02 21:10
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by gdog361** [comment] 2018-06-02 21:39
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2065408/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-06-02 21:41
You didn't turn on debug logging.

**Comment by gdog361** [comment] 2018-06-02 21:42
oh my bad one sec

**Comment by gdog361** [comment] 2018-06-02 21:43
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2065410/LOOTDebugLog.txt)
here ya go

**Comment by WrinklyNinja** [comment] 2018-06-02 21:44
Yeah, duplicate of #956, see that issue for details.

**Closed by WrinklyNinja** 2018-06-02 21:44 UTC
