### ISSUE TITLE
LOOT libloadorder error, can't apply after sorting plugins for Fallout 4.

### ISSUE THREAD

**Issue by StormV1** [loot/loot#962] opened 2018-06-03 03:10 UTC
The new LOOT update just recently came out and after getting said update I've ran into this problem where when I apply after sorting my plugins I get an error that tells me my plugins.txt might be set to read-only, only problem here is that it never is. I've looked all over Google for a solution.

**Things I've already tried that did NOT work**
- Ticked off read-only from my plugins.txt located at (C:\Users\Username\AppData\Local\Fallout4)
- Ran LOOT as administrator
- Deleted Fallout4 folder located at (C:\Users\Username\AppData\Local\LOOT)
- Reinstalled LOOT v0.13.0

Any help would be appreciated because I'm unsure what else I could do to solve this.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2065600/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-06-03 05:19
Duplicate of #956, try the fix posted there.

**Closed by WrinklyNinja** 2018-06-03 05:19 UTC
