### ISSUE TITLE
Loot won't start or start without recognizing my mods

### ISSUE THREAD

**Issue by binn05** [loot/loot#640] opened 2016-09-07 21:17 UTC
Hello,
Using the latest version of loot.
It won't start if I click Loot.exe, or try to use it from MO. If I enter spam Loot.exe (from loot foolder) it start, but only shows Skyrim original esms ou esps.
I attached the lootdebuglog (created when I enter spammed the .exe).

[LOOTDebugLog.txt](https://github.com/loot/loot/files/460358/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2016-09-08 07:03
This looks like a duplicate of #575, try the fix given there.

**Closed by WrinklyNinja** 2016-09-08 07:03 UTC
