### ISSUE TITLE
LOOT crashes constantly when run through Mod Organizer

### ISSUE THREAD

**Issue by RevReese** [loot/loot#1096] opened 2019-03-09 16:40 UTC
Hi, I am having constant crashes usually within a few seconds of launching LOOT through Mod Organizer (mainly when parsing metadata).  
Sometimes, it loads up and then crashes when switching games or clicking sort.

Very rarely, it works and sorts my load order.

I can load it up most often outside MO but obviously LOOT does not detect my mods so is useless in that case.

I am using Windows 7 64bit and the latest installer version of LOOT (i have also tried the latest dev version with the same results).

I have re downloaded and re installed numerous times with no different result and have tried posting on Steam too: https://steamcommunity.com/app/22380/discussions/0/1837937637891481868/

I have tried deleting the LOOT folder in Appdata too but no improvement.
I have tried running LOOT as Admin and MO as Admin but still experience crashes.
Also, on occasion, LOOT likes to delete the "resources" folder (or parts of it anyway) when loading up MO.

I am using Mod Organizer 1.3.15 as i did not see a benefit to upgrading to MO2.
I did find on the STEP wiki that Windows 7 users need to update TLS which i did and that worked a few times before the crashing started again.

All my plugins are clean on SLE/FNV/FO3 and downloaded through the Nexus site.

My system is up to date and i have set an exclusion in my AV just in case.

[CEFDebugLog.txt](https://github.com/loot/loot/files/2948590/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2948592/LOOTDebugLog.txt)

I hope i have given enough information to go on, but please ask any questions and i will try my best to answer them.

Thank you.

**Comment by LostDragonist** [comment] 2019-03-10 06:42
Does it still crash if you get rid of the ghosted plugins?

**Comment by RevReese** [comment] 2019-03-10 14:08
Thanks for your reply.
I do have a few mods merged into my bashed patch and deactivated if that's what you mean?
Anyway, ticking all the mods on the right pane still crashes on or shortly before clicking sort.
I rebuilt my bashed patch but didn't merge any this time and loot still crashes on launch.

**Comment by Ortham** [comment] 2019-03-10 15:57
Try turning off plugin ghosting, IIRC it's unnecessary for Skyrim and later games.

**Comment by RevReese** [comment] 2019-03-10 16:17
Auto ghost is already off.
I am using Wrye Flash but it seems to work the same as Wrye Bash.
I am having this issue with Skyrim Legendary, Fallout 3 and Fallout New Vegas as i am using LOOT for those games.

**Comment by Ortham** [comment] 2019-03-10 16:41
If ghosting is off, how come you have files with a `.ghost` extension?

**Comment by RevReese** [comment] 2019-03-10 16:42
i dont know, but it is definitely off already, not sure what has happened there.

**Comment by RevReese** [comment] 2019-04-02 23:16
I am still having the crashes has anyone got anything else i could try? I would like to reliably use LOOT.

**Comment by LostDragonist** [comment] 2019-04-03 09:04
I think someone else had this problem and it was determined to be caused by the MO2 paths getting too long.  

"C:\Users\LostDragonist\AppData\Local\ModOrganizer\This is a really long instance name\mods\This is a really long mod name so ridiculously long like OMG it's so long but I still had to add this extra bit to break\This is a really long name for a plugin who the hell does this OMG WTF are you doing.esp" is 300 characters long.  That's 45 characters too many.  MO2 can not open the file therefore LOOT can not open the file.

As the ESP exists in plugins.txt, LOOT assumes the plugin is ghosted and checks for that.  It doesn't exist and LOOT throws an exception.

If that sounds like it could be an issue for you, you can move your mods folder closer to the root of the drive.  Use shorter mod names.  Use shorter plugin names.

**Comment by RevReese** [comment] 2019-04-05 18:45
That's an interesting thought, though the path isn't overly long in this case (G:\LOOT\Loot.exe) but it is something to keep in mind for the future thank you.

**Comment by LostDragonist** [comment] 2019-04-06 00:22
It's the path of the MO2 mods folder that matters, not LOOT.

**Comment by RevReese** [comment] 2019-04-06 18:16
Ah okay, my apologies i read that wrong.
The actual path to the mods folders for:
Skyrim is G:\Mod Organizer 1.3.15\mods.
Fallout 3 G:\Steam\steamapps\common\Fallout 3 goty\Mod Organizer 1.3.15\mods.
Fallout New Vegas G:\Steam\steamapps\common\Fallout New Vegas\Mod Organizer 1.3.15\mods.

Are these too long?

**Comment by LostDragonist** [comment] 2019-04-06 23:45
Not by a mile.  Guess it might be something else then.

**Comment by pStyl3** [comment] 2019-07-25 21:11
I've had LOOT crash on me a couple of times aswell in the past, if run through MO. I've fixed it by reinstalling MO (delete every folder within the MO folder BUT the `downloads`,`mods` and `profiles` folder, and installing a fresh MO installation over it. Never really knew, what the actual issue was.

In any case, closing this issue, since the problem only occurs if LOOT is run through MO, as well as new LOOT versions have been released since the opening of this issue.

**Closed by pStyl3** 2019-07-25 21:11 UTC
