### ISSUE TITLE
Error Message when i want to sort Plugins

### ISSUE THREAD

**Issue by ibbenbueren99** [loot/loot#1242] opened 2020-06-06 18:01 UTC
This appears, ppl said i need to select only one mod but i am not that informed how i disable one of them, i already disabled them in nexmus mod manager via plugins mask, and retried loot sorting plugins but it still show me this error. pls help me

Cyclic interaction detected between "ELE_SSE.esp" and "Immersive Citizens - ELFXHardcore patch.esp":

ELE_SSE.esp
 [Master]
Immersive Citizens - ELE patch.esp
 [Group]
ELFX - Hardcore.esp
 [Master]
Immersive Citizens - ELFXHardcore patch.esp
 [Group]
ELE_SSE.esp

You have not sorted your load order this session.

**Comment by CptMcSplody** [comment] 2020-06-06 18:17
> This appears, ppl said i need to select only one mod

Yes, you should only be using one lighting enhancer.
`ELE_SSE.esp` or `ELFX - Hardcore.esp` or `ELFXEnhancer.esp`.

There are no sorting rules between these plugins they're incompatible.

You can technically use `ELE_SSE.esp` with `EnhancedLightsandFX.esp`.
But `EnhancedLightsandFX.esp` is supposed to be used with `ELFXEnhancer.esp` or `ELFX - Hardcore.esp`.

`ELE_SSE.esp` was designed to be used with [Relighting Skyrim - SSE](https://www.nexusmods.com/skyrimspecialedition/mods/8586) `RelightingSkyrim_SSE.esp`.
`RelightingSkyrim_SSE.esp` is not compatible with `EnhancedLightsandFX.esp`.

**Comment by ibbenbueren99** [comment] 2020-06-06 19:00
> 
> 
> > This appears, ppl said i need to select only one mod
> 
> Yes, you should only be using one lighting enhancer.
> `ELE_SSE.esp` or `ELFX - Hardcore.esp` or `ELFXEnhancer.esp`.
> 
> There are no sorting rules between these plugins as they're incompatible.
> 
> You can technically use `ELE_SSE.esp` with `EnhancedLightsandFX.esp`.
> But `EnhancedLightsandFX.esp` is supposed to be used with `ELFXEnhancer.esp` or `ELFX - Hardcore.esp`.
> 
> `ELE_SSE.esp` was designed to be used with [Relighting Skyrim - SSE](https://www.nexusmods.com/skyrimspecialedition/mods/8586).
> `RelightingSkyrim_SSE.esp` is not compatible with `EnhancedLightsandFX.esp`.

thank you, i disabled ELE_SS.esp and tried sorting again and it did sorted i could apply it

**Comment by CptMcSplody** [comment] 2020-06-06 19:04
> thank you, i disabled ELE_SS.esp and tried sorting again and it did sorted i could apply it

Your're welcome, I'll close this issue now since it has been resolved.

**Closed by CptMcSplody** 2020-06-06 19:04 UTC
