### ISSUE TITLE
Error: Cannot read property of 'text' of undefined 

### ISSUE THREAD

**Issue by FireTehVahu** [loot/loot#789] opened 2017-06-11 01:40 UTC
I get this error in LOOT v 0.11.0 when trying to sort plugins. I tried reopening it with the same result.

 Masterlist Revision	94b69f0
Masterlist Date	2017-05-18

[CEFDebuglog](https://pastebin.com/cKtpuQHQ)
[LOOTDebuglog](https://pastebin.com/UqRfQFp0)

**Comment by WrinklyNinja** [comment] 2017-06-11 15:00
Does [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-8-g0370a16_fix-undefined-message.7z) work for you?

**Comment by FireTehVahu** [comment] 2017-06-11 16:36
No, it did not initially; but I figured out the issue. The Error it gave me was Failed to sort plugins which led me to believe that LOOT could not find where skyrim is located.

When I first installed skyrim, I moved it to another drive where Oblivion is located under C:\Bethesda Softworks\Skyrim and created a symlink to the original location. The original location under S:\Steam\SteamApps\common\Skyrim is where LOOT was looking at and apparently it cannot read symlinks. I'm running windows 7 64bit Professional if that helps.

So after I had changed to the real location, both builds were able to read it and sort plugins.

Thanks for the help!

**Comment by WrinklyNinja** [comment] 2017-06-11 16:41
> No, it did not initially; but I figured out the issue. The Error it gave me was Failed to sort plugins which led me to believe that LOOT could not find where skyrim is located.

So you were still getting the `Cannot read property of 'text' of undefined`, or a different error?

**Comment by WrinklyNinja** [comment] 2017-06-11 16:48
Also, if the error was because LOOT couldn't find your game, you'd never see any plugins listed, and LOOT would open the settings dialog when you launched it, let alone be able to try sorting anything, so I don't think the issue is actually resolved.

Knowing you're using symlinks helps though, there are a few possibilities where they may not be resolved correctly...

**Comment by FireTehVahu** [comment] 2017-06-11 23:46
I get the error 'Cannot read property of 'text' of undefined' when I sort plugins using LOOT v 0.11.0 when skyrim's location is set to the symlink location, S:\Steam\SteamApps\common\Skyrim. 

No plugins were listed( and it even says this under general information; must have missed it the first time) and it never took me to the settings page due I guess because I had installed LOOT previously. 

The exact error from the build you sent me is `Error: Failed to sort plugins. Details: See general messages for details.'

General Messages contain:
Latest LOOT thread.
It appears you do not have the latest version of SKSE. Some mods may require functionality added in the latest version of SKSE to work.
It appears you have Fores New Idles in Skyrim installed. Remember to run GenerateFNISforUsers.exe every time you have installed or de-installed FNIS, or a FNIS based mod.

Same thing here as well. No plugins.

As a side note, I noticed that I have do have the latest version of SKSE, however the file version number of skse_loader is 0.1.7.3. as opposed to 1.7.3 yet, LOOT reports otherwise.

**Comment by WrinklyNinja** [comment] 2017-06-12 07:01
> No plugins were listed

The underlying cause is probably that LOOT isn't resolving symlinks when scanning for plugins. If you delete your `%LOCALAPPDATA%\LOOT\settings.yaml` (or rename it if you don't want to delete it), is LOOT still able to detect that Skyrim is still installed? If it is, what path does it store in its settings, the real path or the symlink path?

> The exact error from the build you sent me is Error: Failed to sort plugins. Details: See general messages for details.

So my fix for that issue is working, it's just that there's another underlying it.

**Comment by FireTehVahu** [comment] 2017-06-12 14:50
After renaming settings.yaml, LOOT detects that Skyrim is installed in the symlink path under steam: S:\Steam\steamapps\common\Skyrim.

**Comment by WrinklyNinja** [comment] 2017-06-12 20:51
Right, can you try with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-10-gb66b0fd_fix-undefined-message.7z)?

**Comment by FireTehVahu** [comment] 2017-06-13 01:36
`Error: Oh no, something went wrong! You can check your `[LOOTDebuglog](https://pastebin.com/HL1MhSzU)` for more information.` is the error I got when I selected skyrim for LOOT (it defaults to Oblivion) in that build.

The strange thing is that debug log shows the path incorrectly even though I don't have it typed that way, especially with the front slash. It looks it combined both the symlink and real path together.

**Comment by WrinklyNinja** [comment] 2017-06-13 06:10
Well, that was unexpected... Can you run that build and the previous build with debug logging enabled, and upload the logs?

**Comment by FireTehVahu** [comment] 2017-06-13 14:57
LOOT v.0.11.0-10: [LOOTDebuglog](https://pastebin.com/HL1MhSzU)
LOOT v.0.11.0-8: [LOOTDebuglog](https://pastebin.com/QK1zzTTc)

**Comment by FireTehVahu** [comment] 2017-06-13 15:07
LOOT v 0.11.0-8 : [LOOTDebuglog](https://pastebin.com/5p85iHqz)
LOOT v 0.11.0-10: [LOOTDebuglog](https://pastebin.com/7qdLJiw5)

**Comment by WrinklyNinja** [comment] 2017-06-13 16:29
Hmm, what happens if you replace the `loot_api.dll` in the v0.11.0 release with [this one](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.0-5-g13ad64e_improve-symlink-support-win32.7z)?

**Comment by FireTehVahu** [comment] 2017-06-13 16:52
It fails to open:
[LOOTDebuglog](https://pastebin.com/7i0whtDT)
[LOOTAPIlog](https://pastebin.com/VAEgFQyZ)

**Comment by WrinklyNinja** [comment] 2017-06-13 19:24
Well, that's no good... I just tried replicating your setup, and the last build I linked works for me (with the newer LOOT API).

However, I'm testing this on Linux (I'm currently having problems booting Windows), and my Windows and Linux mount points are different partitions on the same physical drive (I'm guessing yours are on different drives?), so there's probably a platform difference involved.

**Comment by WrinklyNinja** [comment] 2017-06-15 19:28
OK, I fixed my Windows boot, and tried replicating the issue. I created a symlink using the following command:

```
mklink /D C:\Users\Oliver\Documents\Code\LOOT\loot\build\Release\skyrim.symlink "C:\Games\Steam\steamapps\common\Skyrim Special Edition"
```

I then built the commit before the HEAD of the `fix-undefined-message` branch, and configured LOOT  to use the symlink path for the game's install path. Opening LOOT and sorting plugins encountered no problems.

The binary versions:
```
[18:50:22.396058] [info]: LOOT Version: 0.11.0+927309db
[18:50:22.396058] [info]: LOOT API Version: 0.11.0+8864f788
```

I then tested the latest build of the `fix-undefined-message` branch from Bintray, in case there were compiler/build environment-related differences:

```
[18:58:23.394618] [info]: LOOT Version: 0.11.0+b66b0fd5
[18:58:23.394618] [info]: LOOT API Version: 0.11.0+8864f788
```

Again, no issues. Finally, I tested the LOOT v0.11.0 release binary:

```
[19:00:12.331925] [info]: LOOT Version: 0.11.0+7976a4de
[19:00:12.332926] [info]: LOOT API Version: 0.11.0+8864f788
```

To my surprise, this had no issues either.

@FireTehVahu How did you create your symlink?

**Comment by FireTehVahu** [comment] 2017-06-16 00:40
I do have two drives set up like you guessed and steam is on the HDD and Skyrim on the SSD. 

I have used console commands in the past to create symlinks but this time I used a program called [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) as indicated in this [article](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/).

**Comment by WrinklyNinja** [comment] 2017-06-16 07:41
I suspect you've got a junction link, like #777. I just replaced my symlink with a junction link and LOOT doesn't like that. I don't have time right now to verify, but you can try swapping your junction link for a symlink and see if everything still works, I expect it would.

**Comment by WrinklyNinja** [comment] 2017-06-16 17:58
OK, replace your `loot_api.dll` with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.0-5-gc78314c_fix-junction-link-support-win32.7z), and see if that fixes things, it does for me.

**Comment by FireTehVahu** [comment] 2017-06-17 00:36
Yep, it works like a charm! Apparently I didn't realize there was difference in symlinks and junctions. Thanks for your help!

**Closed** 2017-06-17 02:56 UTC
Labels: bug
