### ISSUE TITLE
Cant update masterlist

### ISSUE THREAD

**Issue by Avriron** [loot/loot#893] opened 2018-02-24 20:55 UTC
[error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

**Comment by SuperSandro2000** [comment] 2018-02-24 21:24
Look latest release notes

**Comment by pStyl3** [comment] 2018-02-24 21:48
Update LOOT to version 0.12.4, install all recommended Windows 7 updates and make sure that you have [url=https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in]enabled TLS 1.2 support[/url] to support updating the masterlists from LOOT's official repositories on GitHub.

This is a duplicate of #882.

**Closed** 2018-02-25 08:45 UTC
Labels: duplicate
