### ISSUE TITLE
LOOT immediate CTD

### ISSUE THREAD

**Issue by darkallnight** [loot/loot#609] opened 2016-07-18 06:10 UTC
So after months without playing Fallout 4 I decided to get back into the game, and a lot of mods recommended LOOT to be run to sort out mods. So I downloaded LOOT as recommended but sadly not even 3 seconds after launching the program it immediately crashes to desktop, the only messages it displays is: 
Name of event problem:	APPCRASH
  Name of Application:	LOOT.exe
  Application version:	0.9.1.0
 Date/Time application stamp:	576b84b3
  Name of faulty module:	ntdll.dll

At first I thought it was a problem with DEP since some programs had before, but that wasn't it, tried changing compatibility to other windows versions or running as admin, didn't work either.

OS: Windows 7 ultimate  x64

Edit: ..... What the hell? So apparently after looking into some answers here in the github someone suggested I tried to open the program spamming it so it could open multiple instances of the program....and it worked...I don't know why, but it did.

**Comment by Freso** [comment] 2016-07-18 10:31
Please be sure to [provide debug logs](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) when reporting issues. :)

**Comment by WrinklyNinja** [comment] 2016-07-18 10:38
Closing this as it looks like a duplicate of #575, then. @darkallnight, if you do provide debug logs, just upload them in a comment in that issue.

**Closed by WrinklyNinja** 2016-07-18 10:38 UTC
