### ISSUE TITLE
LOOT stops running before UI is displayed

### ISSUE THREAD

**Issue by AleBurzio** [loot/loot#575] opened 2016-05-20 20:19 UTC
I recently downloaded the new version of LOOT, but it doesn't start anymore. Last time I updated it was a month ago, but now it doesn't simply work: I click on the icon, it shows that it's loading, and then it stops (I checked everything in task manager)

I don't know what to do now, any help?

PS: of course i tried to install it again from scratch, but it doesn't work anyways

**Comment by WrinklyNinja** [comment] 2016-05-20 20:22
What do you mean by "it shows that it's loading, and then it stops", and
have you tried deleting LOOT's settings.yaml file? If you were using a
snapshot build, you have to delete that before using an earlier release.

**Comment by AleBurzio** [comment] 2016-05-20 20:33
First of all, ad I dadi before, i uninstall ed everything before installing the new version of the program

By "it shows that it's loading" i mean that loot appese sto be running in the task manager when i click on the icon, but after a few seconds the process simply disappears from the task manager and the program doesn't start

**Comment by AleBurzio** [comment] 2016-05-20 20:34
As I said before*

**Comment by WrinklyNinja** [comment] 2016-05-21 06:27
The only case I know where that happens is when an older version of LOOT is trying to load a snapshot build's settings file. Please try using the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0).

**Comment by WrinklyNinja** [comment] 2016-05-30 14:09
When LOOT runs, does it create a `%LOCALAPPDATA%\LOOT` folder (if one already exists, delete it and try again)?

**Comment by Castello669** [comment] 2016-06-05 17:23
Hello, I am having thesame issue. Installed LOOT 0.9.0 and then when I double clicked it, nothing.
I had two older folders of loot inside my Skyrim folder, none of them required an installation. I deleted both, cleaned applocale folder then removed loot with Revo Uninstaller and took out all leftovers, installed it again and nothing. Uninstalled and tried the snapshot built and got a "LOOT.exe has stopped working" Windows message.

"Files that help describe the problem:
  C:\Users\KSTL\AppData\Local\Temp\WER9839.tmp.WERInternalMetadata.xml
  C:\Users\KSTL\AppData\Local\Temp\WERB24F.tmp.appcompat.txt
  C:\Users\KSTL\AppData\Local\Temp\WERB26F.tmp.mdmp"

**Comment by WrinklyNinja** [comment] 2016-06-05 17:49
Did v0.8.1 work? As above, when LOOT runs, does it create a %LOCALAPPDATA%\LOOT folder?

**Comment by Castello669** [comment] 2016-06-11 04:43
Both instances of LOOT worked on Skyrim, I did not test them after I installed 0.9.0, I just deleted both folders (one inside mod organizer).

**Comment by Rods03** [comment] 2016-06-13 03:45
had same problem with 0.9.0, didn't start and didn't creat folder, found the 0.8.1 on the other topic and worked fine, problem is i want LOOT for fallout 4 so i don't know what to do.

**Comment by WrinklyNinja** [comment] 2016-06-13 05:24
@AleBurzio @Castello669 @Rods03 Can you try the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (0.9.0-40)?

**Comment by Castello669** [comment] 2016-06-15 23:59
0.9.0-40
"has stopped working"
copying a txt file that was on the "more info":

<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="LOOT.exe" FILTER="CMI_FILTER_PRIVACY">
    <MATCHING_FILE NAME="d3dcompiler_47.dll" SIZE="3709120" CHECKSUM="0x41CA7E34" BIN_FILE_VERSION="10.0.10586.212" BIN_PRODUCT_VERSION="10.0.10586.212" PRODUCT_VERSION="10.0.10586.212" FILE_DESCRIPTION="Direct3D HLSL Compiler for Redistribution" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="10.0.10586.212 (th2_release_sec.160328-1908)" ORIGINAL_FILENAME="d3dcompiler_47.dll" INTERNAL_NAME="d3dcompiler_47.dll" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x398033" LINKER_VERSION="0xA0000" UPTO_BIN_FILE_VERSION="10.0.10586.212" UPTO_BIN_PRODUCT_VERSION="10.0.10586.212" LINK_DATE="03/29/2016 06:30:51" UPTO_LINK_DATE="03/29/2016 06:30:51" EXPORT_NAME="D3DCOMPILER_47.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="libcef.dll" SIZE="52034560" CHECKSUM="0x76312702" BIN_FILE_VERSION="3.2704.1427.0" BIN_PRODUCT_VERSION="3.2704.1427.0" PRODUCT_VERSION="3.2704.1427.g95055fe" FILE_DESCRIPTION="Chromium Embedded Framework (CEF) Dynamic Link Library" PRODUCT_NAME="Chromium Embedded Framework (CEF) Dynamic Link Library" FILE_VERSION="3.2704.1427.g95055fe" ORIGINAL_FILENAME="libcef.dll" INTERNAL_NAME="libcef" LEGAL_COPYRIGHT="Copyright (C) 2016 The Chromium Embedded Framework Authors" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="3.2704.1427.0" UPTO_BIN_PRODUCT_VERSION="3.2704.1427.0" LINK_DATE="06/11/2016 06:01:06" UPTO_LINK_DATE="06/11/2016 06:01:06" EXPORT_NAME="libcef.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="libEGL.dll" SIZE="80384" CHECKSUM="0x88A27295" BIN_FILE_VERSION="2.1.0.0" BIN_PRODUCT_VERSION="2.1.0.0" PRODUCT_VERSION="2.1.0.1a1b30c37e13" FILE_DESCRIPTION="ANGLE libEGL Dynamic Link Library" PRODUCT_NAME="ANGLE libEGL Dynamic Link Library" FILE_VERSION="2.1.0.1a1b30c37e13" ORIGINAL_FILENAME="libEGL.dll" INTERNAL_NAME="libEGL" LEGAL_COPYRIGHT="Copyright (C) 2015 Google Inc." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.1.0.0" UPTO_BIN_PRODUCT_VERSION="2.1.0.0" LINK_DATE="06/11/2016 05:12:32" UPTO_LINK_DATE="06/11/2016 05:12:32" EXPORT_NAME="libEGL.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="libGLESv2.dll" SIZE="1734656" CHECKSUM="0x718E5439" BIN_FILE_VERSION="2.1.0.0" BIN_PRODUCT_VERSION="2.1.0.0" PRODUCT_VERSION="2.1.0.1a1b30c37e13" FILE_DESCRIPTION="ANGLE libGLESv2 Dynamic Link Library" PRODUCT_NAME="ANGLE libGLESv2 Dynamic Link Library" FILE_VERSION="2.1.0.1a1b30c37e13" ORIGINAL_FILENAME="libGLESv2.dll" INTERNAL_NAME="libGLESv2" LEGAL_COPYRIGHT="Copyright (C) 2015 Google Inc." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.1.0.0" UPTO_BIN_PRODUCT_VERSION="2.1.0.0" LINK_DATE="06/11/2016 05:12:28" UPTO_LINK_DATE="06/11/2016 05:12:28" EXPORT_NAME="libGLESv2.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="LOOT.exe" SIZE="3099648" CHECKSUM="0xBEE40BA8" BIN_FILE_VERSION="0.9.0.0" BIN_PRODUCT_VERSION="0.9.0.0" PRODUCT_VERSION="0.9.0" FILE_VERSION="0.9.0" LEGAL_COPYRIGHT="Copyright (C) 2013-2016 WrinklyNinja" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x2F5C7A" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="0.9.0.0" UPTO_BIN_PRODUCT_VERSION="0.9.0.0" LINK_DATE="06/12/2016 13:14:18" UPTO_LINK_DATE="06/12/2016 13:14:18" EXPORT_NAME="LOOT.exe" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="wow_helper.exe" SIZE="67072" CHECKSUM="0x38057203" MODULE_TYPE="WIN32" PE_CHECKSUM="0x144D8" LINKER_VERSION="0x0" LINK_DATE="02/03/2009 19:16:59" UPTO_LINK_DATE="02/03/2009 19:16:59" EXE_WRAPPER="0x0" />
</EXE>
<EXE NAME="LOOT.exe" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="LOOT.exe" SIZE="3099648" CHECKSUM="0xBEE40BA8" BIN_FILE_VERSION="0.9.0.0" BIN_PRODUCT_VERSION="0.9.0.0" PRODUCT_VERSION="0.9.0" FILE_VERSION="0.9.0" LEGAL_COPYRIGHT="Copyright (C) 2013-2016 WrinklyNinja" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x2F5C7A" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="0.9.0.0" UPTO_BIN_PRODUCT_VERSION="0.9.0.0" LINK_DATE="06/12/2016 13:14:18" UPTO_LINK_DATE="06/12/2016 13:14:18" EXPORT_NAME="LOOT.exe" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
</EXE>
<EXE NAME="kernel32.dll" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="1114112" CHECKSUM="0xB25986C" BIN_FILE_VERSION="6.1.7601.23418" BIN_PRODUCT_VERSION="6.1.7601.23418" PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x11CD1F" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23418" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23418" LINK_DATE="04/09/2016 06:57:39" UPTO_LINK_DATE="04/09/2016 06:57:39" EXPORT_NAME="KERNEL32.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>

**Comment by WrinklyNinja** [comment] 2016-06-16 07:02
Is there anything in your LOOT debug logs? (See [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for how to get them.)

**Comment by Rods03** [comment] 2016-06-17 16:22
same as castello, didn't create LOOT fold as well.

**Comment by Rods03** [comment] 2016-06-17 16:22
maybe it's cause i'm using windows 7?

**Comment by WrinklyNinja** [comment] 2016-06-17 16:50
That shouldn't cause a problem, but it would be interesting to know if @Castello669 is also using Windows 7 - I'm on Windows 10.

**Comment by racusska** [comment] 2016-06-18 12:16
Hi i also have the same problem (i think it same issue).
let me explain my problem first,When i'm run LOOT.exe (Lastest Release & First install) then Loot.exe Shut themselves (Not responding messenge popup) every times i'm try to run this program.
There my solution
1. Try to troubleshoot Win7 comp.mode,Win8 comp.mode,High DPImode>> Not work
2. Run as admin >> still wont work
3. reinstall with Installer in default directory >> it work!

I think would be some part of my first directory is native language because of issue.

Hope my solution will help

ps. sorry for my language it not my native try to learn a lot

**Comment by Agnusthemagi** [comment] 2016-06-18 14:27
I have the same problem, I managed to install and use version 0.8.1 with mod organizer 1.3.8, but 0.9 and up have the same behavior as users above indicate.
System windows 10 professional 64 bits.
Steps:
1.Remove old version (delete from c:\loot and %appdata)
2.Unpack the zip and execute first time from the local folder to create files
3. Run from mod organizer
4. Task manager shows loot.exe with 5.12 Mb memory usage for 5-10 seconds then shutdown
5. Screen dosent appear
6. I experienced same behavior with 0.8.1 up until today, honestly dont know what made this version work now

**Comment by WrinklyNinja** [comment] 2016-06-19 13:00
> I have the same problem, I managed to install and use version 0.8.1 with mod organizer 1.3.11, but 0.9 and up have the same behavior as users above indicate.

If it works when you run it directly (i.e. not through Mod Organiser), then it's not a problem with LOOT and you should report the issue to Mod Organiser's dev(s).

**Comment by Agnusthemagi** [comment] 2016-06-20 04:27
Indeed, it works directly. Your reasoning is sound and also not point reporting to MO, since the response I will get is only MO 2.0 being developed. 
Also I think MO 2.0 will be required for skyrim special edition (64 bits exe), so not much point keeping to old one.

**Comment by Castello669** [comment] 2016-06-20 13:55
I'm on Win7-64. I am trying to run loot for Fallout 4.
Since it won't start, and It doesn't create a %LOCALAPPDATA%\LOOT\ , I don't think there are any logs. Will check when I get home.

**Comment by WrinklyNinja** [comment] 2016-07-01 06:40
One user experiencing issues when running LOOT through MO found that their antivirus software was interfering with LOOT's operation. While it's a very different situation to this issue, could anyone experiencing the issue try whitelisting/excluding LOOT in their antivirus software and see if that fixes things?

**Comment by WrinklyNinja** [comment] 2016-07-02 16:58
Could anyone experiencing this issue please try running LOOT again, using the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) in the `autocomplete-filenames-bash-tags` folder?

**Comment by Kazzymio** [comment] 2016-07-02 19:09
I have the same issue.

snapshot build 0.9.1-8 doesn't work for me.

**Comment by Gashimahiron** [comment] 2016-07-06 03:14
For the people here still lost and unable to run the latest LOOT, try spamming the program open by holding/mashing enter or whatever method you prefer to open a program repeatedly as fast as possible.
I don't know why, so don't ask how, but it may work, as pointed out by Nexus user VSairaf.

It worked for him, it worked for me, it worked for some other guy, it might work for you too.

**Comment by bwmutley** [comment] 2016-07-07 02:57
"try spamming the program open by holding/mashing enter" LOL, I wonder how they found this "method". Anyways, it worked for me, though it was useless. I rolled back to version 0.8.1. The thing to do now is to wait for developers to check that. BTW, mine were crashing with and without MOd Organizer, so my guess it is the binary which is bugged.

**Comment by Kazzymio** [comment] 2016-07-08 01:51
spamming works sometimes, thank you Gashimahiron. 0.8.1-131 works with or without MO, so I will stick with it.

**Comment by WrinklyNinja** [comment] 2016-07-31 09:51
Could anyone experiencing this issue please try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.9.1-87-g92408c9_update-cef.7z). I managed to replicate the issue, and this fixed it for me.

**Comment by Castello669** [comment] 2016-07-31 23:12
Didn't fix for me. Worth noting I did the Win 7 to Win 10 upgrade, without formatting. So now I'm having the same problem on Win 10. Spamming the .exe works eventually. Sometimes opens a blank page though.

**Comment by Kazzymio** [comment] 2016-08-01 05:22
0.9.1-87 didn't fix for me.

**Comment by Freso** [comment] 2016-08-01 22:39
Two people report that this didn't work… so why close?

**Comment by WrinklyNinja** [comment] 2016-08-01 22:40
Whoops, that was GitHub doing it automatically because I mentioned the issue in the commit message.

**Comment by Triquetra** [comment] 2016-08-06 17:21
I've had this issue also.  Is there a limit to the number of plugins LOOT can handle?  I ask because I've been able to get LOOT 0.9.2 to run in MO with a profile having only 18 plugins, but when I try to run it on my main profile (with about 275 plugins -- because I haven't yet merged a bunch of patches) MO says that LOOT is running, but LOOT never comes up, and eventually MO returns as though the program had closed.  No logs were generated by the failed run, but I'm attaching logs generated with the successful run in the smaller profile.  I hope this helps.
[CEFDebugLog.txt](https://github.com/loot/loot/files/405104/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/405105/LOOTDebugLog.txt)

Also, 0.9.2 didn't work correctly right away in the smaller profile either.  I had to spam the run/crash cycle in MO to finally get it working.

**Comment by WrinklyNinja** [comment] 2016-08-07 00:20
> I've had this issue also. Is there a limit to the number of plugins LOOT can handle? I ask because I've been able to get LOOT 0.9.2 to run in MO with a profile having only 18 plugins, but when I try to run it on my main profile (with about 275 plugins -- because I haven't yet merged a bunch of patches) MO says that LOOT is running, but LOOT never comes up, and eventually MO returns as though the program had closed.

Unfortunately using MO can cause issues to occur that don't otherwise, so it's not clear whether your issues are in any way related to those experienced by everyone else in this thread.

**Comment by Kazzymio** [comment] 2016-09-01 00:58
0.9.2-55-g938002f_cancel-operation

I don't know why but I tried this snapshot and now this bug is fixed for me.

Windows 10 anniversary update 64 bits, with and without MO.

**Comment by WrinklyNinja** [comment] 2016-09-01 06:38
It could be the switch from statically linking the C++ runtime to dynamically linking it. I can't think of anything else that would have an effect, but then again I don't know why the runtime linking would matter...

**Comment by Kazzymio** [comment] 2016-09-02 00:22
It may be the C++ as it starts working after snapshot loot_0.9.2-29-g9a045a7_c++-api

**Comment by WrinklyNinja** [comment] 2016-09-02 05:47
OK, I'll close the issue, if anyone else still has it when trying the latest snapshot build, it can be reopened.

**Closed by WrinklyNinja** 2016-09-02 05:47 UTC
Labels: bug

**Comment by MMDCastro** [comment] 2016-09-04 17:07
OMG. Finally! Confirmed! 0.9.2-55-g938002f_cancel-operation snapshot version worked.
Since 0.9.0 (may/2016) I haven't been able to sort my mods with LOOT. Sometimes it worked after almost mashing my keyboard to bits trying to spam it fast enough to open LOOT.
With this version only a simple double click opened it. Almost magical.
I had a hard time finding the snapshot build tough. Maybe put up a link to it here?

**Comment by WrinklyNinja** [comment] 2016-09-07 16:40
[Here](https://bintray.com/wrinklyninja/loot/LOOT/0.9.2-52-g2daf0a3_dev#files)'s the latest dev branch snapshot at time of writing. Anyone wanting to test the fix should try with that.

**Comment by binn05** [comment] 2016-09-08 20:50
Hello WrinklyNinja,
Tried this latest dev branch and it solved the problem =)
