### ISSUE TITLE
Error 12: no masterlist present

### ISSUE THREAD

**Issue by mariyamak** [loot/loot#885] opened 2018-02-24 00:36 UTC
I recently started getting error messages when using LOOT for Skyrim. For some time I got error notifications but LOOT still did its work and sorted plugins, so I didn't actually check the debug log. But few days later it completely broke - and now it has 'n/a masterlist'. Don't even know what could cause this. Attached a debug log.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1753650/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-02-24 07:08
There's nothing in your log that suggests you've tried updating your masterlist, have you?

**Comment by gameLvr85** [comment] 2018-02-24 07:56
delete the masterlist.yaml
located in C:\Users\Maria 2\AppData\Local\LOOT\Skyrim\
and restart the loot should re-download the master-list and will work.

**Comment by Blackstarlsd** [comment] 2018-02-24 14:15
i have this same problem with fallout 4 now
it was working fine last time used - two days ago, now it says N/A: No masterlist present (which is correct, theres nothing on that folder)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1754422/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-02-24 14:37
> i have this same problem with fallout 4 now
> it was working fine last time used - two days ago, now it says N/A: No masterlist present (which is correct, theres nothing on that folder)
> LOOTDebugLog.txt

That's #882, see the link for the fix.

**Comment by mariyamak** [comment] 2018-02-24 17:44
> There's nothing in your log that suggests you've tried updating your masterlist, have you?
I did, LOOT does it automatically when I run it and then I also try to do that by myself.

> delete the masterlist.yaml
> located in C:\Users\Maria 2\AppData\Local\LOOT\Skyrim
> and restart the loot should re-download the master-list and will work.
Well the thing is I just checked this folder and it's completely empty

**Comment by Blackstarlsd** [comment] 2018-02-24 17:56
no.good.
infact thats ok. LOOT fked my load order already several times, thought to use it for possible errors to clean in FO4Edit but i can use something else for that too. go. die. thanks.

**Comment by WrinklyNinja** [comment] 2018-02-25 08:47
> no.good.
> infact thats ok. LOOT fked my load order already several times, thought to use it for possible errors to clean in FO4Edit but i can use something else for that too. go. die. thanks.

Blocked for unnacceptable behaviour.

**Comment by WrinklyNinja** [comment] 2018-02-25 08:48
Also re-opening this because I closed in response to the wrong comment...

> I did, LOOT does it automatically when I run it and then I also try to do that by myself.
> Well the thing is I just checked this folder and it's completely empty

Please supply the debug log for when you try to update the masterlist.

**Comment by JayToo13** [comment] 2018-02-25 14:08
I'm having the same problem with no masterlist present.. Followed instructions above and it didn't work... even rolled back to the previous version with the same result. Cleaned, reinstalled current version... still no luck.

**Comment by WrinklyNinja** [comment] 2018-02-25 14:35
@JayToo13: That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.

**Comment by mariyamak** [comment] 2018-02-25 18:11
> Please supply the debug log for when you try to update the masterlist.

OK it seems I was doing something wrong. Here is it, so the last 4 lines are my attempts to update masterlist.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1756562/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-02-25 19:09
Yep, duplicate of #882.

**Closed by WrinklyNinja** 2018-02-25 19:09 UTC

**Comment by mariyamak** [comment] 2018-02-26 19:16
That's really sad but none of the solutions worked for me. I have Windows 8, tried downloading and using regedit file, installing Windows updates, deleting Winsocks and reinstalling TLS for local network. And putting the masterlist.yaml to LOOT folder, too. Something strange is going on. Anyway, thanks)
