### ISSUE TITLE
LOOT breaks on startup

### ISSUE THREAD

**Issue by SirJorb** [loot/loot#1171] opened 2019-12-22 07:18 UTC
[23:17:08.653548] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:17:10.028548] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (f9006d36620a1ee65e7d9c3cc4f40ccc4a4595ed): libgit2 error
[23:17:10.029548] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5761:9231)

Sorry if I'm not posting this right, haven't had to do this before.
Get this error when I first start up LOOT. It won't even load my mod list.

**Comment by CptMcSplody** [comment] 2019-12-22 07:22
@SirJorb Duplicate of #1158, please post a comment in that issue saying what operating system you're running, and try the suggestions given in that issue.

**Closed by CptMcSplody** 2019-12-22 07:22 UTC
Labels: duplicate
