### ISSUE TITLE
loot_get_version returns 8.0.1 in 9.1

### ISSUE THREAD

**Issue by Utumno** [loot/loot#596] opened 2016-07-06 14:21 UTC
It is very important to have this right - we print this in the bugdumb and it will result in enormous confusion (starting with me wondering if I use the right dll).

**Comment by WrinklyNinja** [comment] 2016-07-06 14:34
Which DLL did you use, the one in the [v0.9.1 release](https://github.com/loot/loot/releases/tag/0.9.1)?

**Comment by Utumno** [comment] 2016-07-06 15:05
Yep the one in LOOT.API.0.9.1-0-gdc24e10.32.bit.7z : https://github.com/loot/loot/releases/download/0.9.1/LOOT.API.0.9.1-0-gdc24e10.32.bit.7z

**Comment by Utumno** [comment] 2016-07-06 15:06
And here is the code we use to get the version: https://github.com/wrye-bash/wrye-bash/blob/114c83729aa50045cac4f381912007826d8048bf/Mopy/bash/loot.py#L242-L255

**Comment by WrinklyNinja** [comment] 2016-07-06 16:51
Oh, this is really stupid - the name of the executable changed a while back from `loot32.dll` to `loot_api.dll`, and the old DLL hung around in the build folder, and I forgot to update the packaging script...

So you are actually using the v0.8.1 API, the version isn't wrong.

**Comment by WrinklyNinja** [comment] 2016-07-06 16:57
The issue is fixed by 7d008179dfb94c8686c55c6d0418f58994393779, and I'll also remove the API archives from the v0.9.0 and v0.9.1 releases to avoid any further confusion (I could replace them, but that may also be confusing).

The next release will have a correctly-archived API, but until then I'll be making API snapshot builds available as normal.

**Closed by WrinklyNinja** 2016-07-06 16:57 UTC
Labels: bug
