### ISSUE TITLE
Cyclic Interaction

### ISSUE THREAD

**Issue by RoboticPlayer** [loot/loot#637] opened 2016-09-01 01:27 UTC
Whenever I try to sort my load order with LOOT (through MO), I get this error:

Failed to sort plugins. Details: Cyclic interaction detected between plugins "AnotherSortingMod-2016.esp" and "AnotherSortingMod-2016.esp". Back cycle: AnotherSortingMod-2016.esp

Here is my current load order that isn't sorted because it won't sort (duh): http://pastebin.com/Fdh7y8ZJ

**Comment by pStyl3** [comment] 2016-09-01 03:53
From which mod did that plugin came from? Please provide a link.

**Comment by RoboticPlayer** [comment] 2016-09-01 04:00
Another Sorting Mod 2016: http://www.nexusmods.com/skyrim/mods/72428/?

**Comment by WrinklyNinja** [comment] 2016-09-01 16:32
Please provide your debug logs, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by pStyl3** [comment] 2016-09-01 20:21
For your information, I'm not able to reproduce that sorting error (and the Skyrim masterlist.yaml doesn't contain any data related to that plugin).

**Comment by WrinklyNinja** [comment] 2016-09-01 22:45
Same here, hence the request for the logs, which may shed some light on the issue.

**Comment by RoboticPlayer** [comment] 2016-09-02 02:59
[CEFDebugLog.txt](https://github.com/loot/loot/files/451084/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/451085/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2016-09-02 06:01
It seems that your `AnotherSortingMod-2016.esp` has itself as a master in its header record. The one I downloaded from the link you provided doesn't, maybe try downloading it again and see if the issue still occurs?

**Comment by RoboticPlayer** [comment] 2016-09-02 12:20
Seems like that worked, will update if anything changes.

**Comment by WrinklyNinja** [comment] 2016-09-02 12:26
Closing this then, it can be reopened if it happens again.

**Closed by WrinklyNinja** 2016-09-02 12:26 UTC
Labels: invalid
