### ISSUE TITLE
Failed to sort-Cyclic Interaction(SSE)

### ISSUE THREAD

**Issue by EventHorizon27** [loot/loot#981] opened 2018-07-09 03:14 UTC
I've just generated DynDOLOD on SSE, and when I try to sort my load order, I get this error:Cyclic interaction detected between "DynDOLOD.esm" and "MajesticMountains.esp". Back cycle: MajesticMountains.esp, DynDOLOD.esm. As far as I can tell, the problem is that MajesticMountains.esp is a master of DynDOLOD.esm, but LOOT wants to put DynDOLOD.esm with the other .esm files, but also after MajesticMountains.esp.

**Comment by WrinklyNinja** [comment] 2018-07-09 10:07
If MajesticMountains.esp isn't flagged as a master, there's no way for LOOT to resolve this, masters can't load after non-masters, so you can't have DynDOLOD.esm depend on a non-master.

**Comment by EventHorizon27** [comment] 2018-07-09 17:11
This might not be the right place to ask but would it be better to change the plugin to a master through SSEEdit?

**Comment by CptMcSplody** [comment] 2018-07-09 21:51
@EventHorizon27 You'd have to report this to sheson on step forum, as it shouldn't be possible for `MajesticMountains.esp` to be set as a master for `DynDOLOD.esm`.
[Sheson's DynDOLOD Support](http://forum.step-project.com/forum/101-shesons-dyndolod-support/)

**Comment by T4GTR43UM3R** [comment] 2018-07-12 09:05
I'm currently on a holiday trip.
I will compare the esp and the esm at the weekend.
I'm sure that I will find the cause of the problem.
Changing the MajesticMountains.esp to an esm is a pretty bad idea.
Since most weather change the snow color this leads to horrible unfitting snow.
The esp should always be loaded after weather mods.

**Comment by sheson** [comment] 2018-07-15 22:19
This was a bug in an older DynDOLOD version. It was fixed with DynDOLOD 2.41 a while ago.

Have a look at the section "What to test" from the description of the [DynDOLOD Skyrim SE/VR BETA post](http://forum.step-project.com/topic/13029-dyndolod-241-skyrim-sevr-beta/) which also explains to look out for exactly this scenario.

**Comment by T4GTR43UM3R** [comment] 2018-07-15 22:35
I tested the latest version of DynDoLod today and there was no issue like expected.
I thought that it might be a cause of the dynamic creation of the esm.
Thank´s for the clarification.

**Comment by CptMcSplody** [comment] 2018-07-15 23:03
Okay marking this as closed. Thanks @EventHorizon27 @T4GTR43UM3R @sheson

**Closed by CptMcSplody** 2018-07-15 23:03 UTC
