### ISSUE TITLE
ESL-flagged ESPs with ESP masters don't break load order

### ISSUE THREAD

**Issue by Silarn** [loot/loot#865] opened 2018-01-22 18:53 UTC
Testing seems to indicate that ESL-flagged ESP files - while loading their records in the FE/F space - do seem to load based on load order and do not force ESP files to move into the ESL/ESM lord order.

This should mean that ESL-flagged ESPs could be supported while having ESP masters without breaking the actual load order.

Currently LOOT treats ESLs and ESL-flagged ESPs as identical.

**Comment by WrinklyNinja** [comment] 2018-01-23 17:22
This should be fixed as of 7e9d6436cdf1c8d48d01e863578266d8fe1e5c71, does [this build](https://bintray.com/wrinklyninja/loot/loot/0.12.1-11-g7e9d643_dev#files) work as you'd expect?

**Comment by Silarn** [comment] 2018-01-23 17:38
Great - I'll give it a try in a while.

**Comment by Silarn** [comment] 2018-01-24 01:33
Yeah - and I didn't see that closed ticket. Sorry.

**Comment by vensko** [comment] 2018-04-25 20:58
I've got a lot of ESL-flagged ESPs https://i.imgur.com/IJsnCku.png and all of them are grouped after ESMs in 0.12.5 https://i.imgur.com/UkfScEu.png
My new issue can be only created for invalid tests then.

**Comment by Silarn** [comment] 2018-04-25 22:51
Your list appears correct. ESL flagged ESPs would be sorted among your ESPs.

**Comment by vensko** [comment] 2018-04-25 23:36
Yet they are not, take a look at LOOT screenshot.

**Comment by WrinklyNinja** [comment] 2018-04-26 06:33
> Yet they are not, take a look at the LOOT screenshot.

I'm assuming the plugins in italics with the yellow circle icon are ESL-flagged ESPs? In which case I don't see any problems in the screenshot you provided. Please detail exactly what you think the problem is, a specific example of a couple of plugins you think are wrong and why you think that would help.

**Comment by vensko** [comment] 2018-04-26 10:30
> I'm assuming the plugins in italics with the yellow circle icon are ESL-flagged ESPs?
Yes.

> In which case I don't see any problems in the screenshot you provided.
On screenshot, all ESL-flagged ESPs are grouped after ESLs, while they should adhere to the ESP load, like MO2 shows them.
Normal ESPs are pushed under ESL-flagged ESPs: JRCCPatches.esp, Mammoth Hides.esp, Apocalypse - Magic of Skyrim.esp, etc. - all of them are pushed lower.

**Comment by WrinklyNinja** [comment] 2018-04-26 12:46
> On screenshot, all ESL-flagged ESPs are grouped after ESLs, while they should adhere to the ESP load, like MO2 shows them.

No, ESL-flagged ESPs load as ESLs. The only relevant difference is that if an ESL-flagged ESP has an ESP as a master, that ESP isn't force-loaded as an ESM, which it would if it was a master of an ESL file.

**Comment by WrinklyNinja** [comment] 2018-04-26 14:57
> No, asset conflicts are resolved on the left side in MO.

OK, what's Priority about then?

> Yes.

Well, that expectation is incorrect. How can LOOT match the Priority order when I've just demonstrated I don't understand what it represents?

**Comment by vensko** [comment] 2018-04-26 15:01
> OK, what's Priority about then?

This is plugin load order, as they are expected to be loaded by the game according to multiple tests.
When Skyrim loads plugins, it decides record priority by _when_ it's loaded, not _where_. Please, test it like I described here https://github.com/loot/loot/issues/865#issuecomment-384659081

**Comment by WrinklyNinja** [comment] 2018-04-26 15:11
> This is plugin load order

So... how does it differ from mod indices, at run time? I think this discussion has if nothing else shown that "load order" is an overloaded term, could you be more specific?

> When Skyrim loads plugins, it decides record priority by when it's loaded, not where.

I don't understand the distinction you're making between when and where, what is it?

> Please, test it like I described here #865 (comment)

I've tested this stuff in the past, and I'll do so again because maybe Bethesda changed something since the last time I looked (it happens), but I'm not going to run a test that involves MO, because it's involvement produces MO-unique effects I'm just not interested in providing support for. Do you see the outcome of your test differ between going through MO and just editing plugins.txt directly?

Reopening this issue as there's clearly *something* that needs to be gotten to the bottom of.

**Comment by vensko** [comment] 2018-04-26 15:52
> I don't understand the distinction you're making between when and where, what is it?

Where: into FE address space.
When: as plugins.txt suggests.

> Do you see the outcome of your test differ between going through MO and just editing plugins.txt directly?

The outcome is the same. I created two plugins with Skyrim.esm as the only master and created plugins.txt:
> *Normal ESP.esp
> *ESL-flagged ESP.esp

ESL-flagged ESP.esp still has higher priority in the game.

**Comment by vensko** [comment] 2018-04-26 15:56
> So... how does it differ from mod indices, at run time?

Apparently, mod indices no longer dictate record priority, only plugins.txt now matters (not sure what loadorder.txt does in SSE).

**Comment by WrinklyNinja** [comment] 2018-04-26 16:59
OK, I think we're almost on the same page now, here's links to discussions where I've posted about my own testing in case you want to cross-check things. Unfortunately they're not all in one place, but:

- [Plugin Files And You](https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp): several posts throughout that thread
- [TES5Edit](https://afkmods.iguanadons.net/index.php?/topic/3750-wipz-tes5edit/&do=findComment&comment=169289): several posts in the few pages after the linked post.
- #816 has a few posts on my findings amongst implementation discussion, and links to other relevant issues

Note that these don't cover (AFAIR) the current behaviour of ESL-flagged ESPs, because that changed later (you can see most of the discussion was done by November, and this issue got filed in January).

So, would it be accurate to say your issue is with how LOOT displays the load order, rather than what it actually does when it sorts? I can see there is a little inconsistency, and LOOT chooses to display ESLs in a way that doesn't make a lot of sense for ESL-flagged ESPs.

Here I've sorted `Bashed Patch, 0.esp` after `Blank - Copy.esp`, and the latter is ESL-flagged. This makes sense to me:

![screenshot 31](https://user-images.githubusercontent.com/2430738/39320054-e3c8b824-497a-11e8-95fe-3117766f3d3a.png)

I then sorted `Blank - Copy.esp` after `Bashed Patch, 0.esp`. This also makes sense to me:

![screenshot 30](https://user-images.githubusercontent.com/2430738/39320099-020d2928-497b-11e8-94b0-afd3afbb72c8.png)

However, if I then relaunch LOOT, its display is inconsistent:

![screenshot 32](https://user-images.githubusercontent.com/2430738/39320153-2c447d18-497b-11e8-9aff-59f4b455bb1b.png)

I think this inconsistency would make sense if `Blank - Copy.esp` were `Blank - Copy.esl`, because the runtime behaviour trumps what's in plugins.txt (similar to your where vs. when), but with in this case the runtime behaviour for resolving conflicts matches what's in plugins.txt, so the UI is misleading.

LOOT's still able to sort the plugins correctly, do you see differently?

> Apparently, mod indices no longer dictate record priority, only plugins.txt now matters (not sure what loadorder.txt does in SSE).

I don't understand how mod indices relate to loadorder.txt, but LOOT doesn't use loadorder.txt in SSE because it's made redundant with the changes SSE made to plugins.txt (i.e. to use asterisks to indicate active plugins).

**Comment by vensko** [comment] 2018-04-26 17:24
> So, would it be accurate to say your issue is with how LOOT displays the load order, rather than what it actually does when it sorts?

Yes, LOOT is able to sort ESL-flagged ESPs **and** save resulting load order, but displays them incorrectly after app restart.

I see a suggestion in the old thread to add decimal index, representing mod's order in plugins.txt https://github.com/loot/loot/issues/816#issuecomment-335001880 - this is the same thing as the Priority column in MO2.

**Comment by WrinklyNinja** [comment] 2018-04-27 10:24
Closing this as the issue discussed isn't the same as the OP's issue, so I've filed a new issue for it.

**Closed by WrinklyNinja** 2018-04-27 10:24 UTC
