### ISSUE TITLE
Loot won't open

### ISSUE THREAD

**Issue by aramyle** [loot/loot#524] opened 2016-01-07 16:58 UTC
[0104/042149:ERROR:main_delegate.cc(738)] Could not load cef_extensions.pak
[0104/131246:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0104/131250:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0104/131251:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0104/131302:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.
[0104/131302:WARNING:dns_config_service_win.cc(673)] Failed to read DnsConfig.

There is my Debug Log. I try opening LOOT and it just tries to load for a few seconds and then nothing. It worked on my pc about a week ago, not sure what has changed.

**Comment by WrinklyNinja** [comment] 2016-01-07 18:30
Could you try the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (0.8.1-116)?

**Comment by aramyle** [comment] 2016-01-07 21:54
Nope, getting the same issue. The first time I tried it said it couldn't detect libcef.dll, but the file was clearly in there. Every other attempt was the same as before. Deleted and redownloaded and same thing, just tries to load for a few seconds then nothing.

**Comment by Freso** [comment] 2016-01-07 22:21
Could it be UAC issue? What path is LOOT installed to? Have you tried placing LOOT outside of the Programs folders?

**Comment by aramyle** [comment] 2016-01-08 02:10
Yea, I've installed it in Program files in both C: and E: drives and now its all extracted into a folder on the desktop.

**Comment by Sharlikran** [comment] 2016-01-08 08:50
What happens if you delete all instances of LOOT and install it into C:\LOOT.  The program doesn't have to be installed into each drive and each game folder.  If LOOT can't find your install just run the official launcher of the Game.  For Skyrim it's SkyrimLauncher.exe and for Fallout 4 it's Fallout4Launcher.exe.  

For Fallout 4 though after you run the launcher you will have to use NMM or Wrye Flash to enable your mods because the Fallout Launcher will force the plugins to be disabled.

**Comment by WrinklyNinja** [comment] 2016-01-08 17:21
Could you please [provide](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully) your LOOTDebugLog.txt? Without that info debugging is just guesswork.

**Comment by aramyle** [comment] 2016-01-09 03:01
Did that, deleted everything related to LOOT off of my pc. Then installed it into C:\LOOT and still getting the same problem. Here is a link of my LOOTDebugLog.txt   

file:///C:/Users/Brandon/AppData/Local/LOOT/CEFDebugLog.txt

It's the same lines as I posted up top.

**Comment by Sharlikran** [comment] 2016-01-09 06:51
I see the link to the CEFDebugLog.txt and you are right it's the same as above but, that isn't the file we were talking about.  We are literally asking about the LOOTDebugLog.txt, what is the contents of that file?

![lootdebug](https://cloud.githubusercontent.com/assets/1912426/12214879/3281e1d6-b65a-11e5-98c8-c070a967ae2a.jpg)

I am not trying to be insulting with that picture either.  I had mentioned on the Bethesda site how to enable the debug log by editing the settings.yaml.  I have added the screen shot because if you don't have that file then that's a problem.

**Comment by aramyle** [comment] 2016-01-09 10:17
Ok, my mistake... I never changed it to true on my other settings file after you told me to make one .OLD. Here is the file you guys are looking for.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/83616/LOOTDebugLog.txt)

This is after 3 attempts at opening LOOT.

**Comment by WrinklyNinja** [comment] 2016-01-09 12:52
OK, something is pretty messed up... Have you tried deleting your `%LOCALAPPDATA%\LOOT` folder?

**Comment by FatherPootis** [comment] 2016-01-09 17:08
Deleting the %LOCALAPPDATA%\LOOT folder fixed it for me, thanks guys.

**Comment by WrinklyNinja** [comment] 2016-01-09 17:31
It must have been due to a somehow-corrupt settings file then. Sounds like I need to check that and handle it more gracefully if so.

**Comment by Freso** [comment] 2016-01-09 17:34
@FatherPootis Did you fully delete the %LOCALAPPDATA%\LOOT folder or did just rename it or put it in Trash? Any chance you could zip it up and upload it so we can inspect it?

**Comment by Sharlikran** [comment] 2016-01-09 17:34
@WrinklyNinja on the Bethesda thread in [post 99](http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/?p=24828726) I asked aramyle to rename the setting.yaml file so LOOT would make a new one.  For him that did not resolve the issue.  If aramyle deletes his %LOCALAPPDATA%\LOOT folder I am more inclined to believe it's the .git folders.

**Comment by Freso** [comment] 2016-01-09 17:35
Which is also why it would be nice if we could give the contents of the folder a look, to maybe pinpoint what got corrupted how, and thus knowing how to detect and handle it properly. :)

**Comment by Sharlikran** [comment] 2016-01-09 17:39
@aramyle if you can, please make a copy of or rename the %LOCALAPPDATA%\LOOT which is C:\Users\{{Username}}\AppData\Local\LOOT on my hard drive.  Then if you have a backup of it, and you delete the %LOCALAPPDATA%\LOOT folder which resolves your issue, then you could provide that copy as Freso has stated.  :smile:

**Comment by WrinklyNinja** [comment] 2016-01-09 18:06
> @WrinklyNinja on the Bethesda thread in post 99 I asked aramyle to rename the settings.yaml file so LOOT would make a new one. For him that did not resolve the issue. If aramyle deletes his %LOCALAPPDATA%\LOOT folder I am more inclined to believe it's the .git folders.

The crash happened far too early for that to be the cause - if it was the .git folder then it would happen when loading or updating the masterlist. Instead, it happened before or during the game settings being loaded.

Providing a copy of the folder would help though.

**Comment by supadoom** [comment] 2016-01-09 23:13
@WrinklyNinja I had a similar issue as this person while using the installer yet the archive version works fine. Not sure why just thought I'd let you know.

**Comment by aramyle** [comment] 2016-01-10 00:36
That worked guys, just deleted the folder and now the program runs... Awesome. Thanks alot

**Comment by aramyle** [comment] 2016-01-10 00:42
I have the folder still, not sure how to link you to the whole thing. 

[CEFDebugLog.txt](https://github.com/loot/loot/files/83901/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/83902/LOOTDebugLog.txt)

These are the 2 debug logs and the other 2 settings files won't link when I drop them in... If you know of a way I can place an entire folder in I'd be happy to do it if its going to help.

**Comment by Sharlikran** [comment] 2016-01-10 01:37
Those look like the old log files despite the fact that you deleted the LOOT folder.  Did you enable the log?  You can do that now in LOOT since it's running.  You would change that under settings but you have to restart LOOT IIRC.

As far as the folder goes you would have to use an archive program.  Normally I can right click the folder and use [7Zip](http://www.7-zip.org/) and it will package the entire folder.  You can use any Archive program you already have one but 7Zip is a free alternative if you need one.

**Comment by WrinklyNinja** [comment] 2016-01-10 08:41
> If you know of a way I can place an entire folder in I'd be happy to do it if its going to help.

Zip it, [here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) are the file formats issues support uploading for.

**Comment by Sharlikran** [comment] 2016-01-10 10:29
@aramyle if you have an archive program that makes a file listed in the link that WrinklyNinja provided that's perfect.  Just drag to attach it.  In the event you try to use 7Zip be sure to use it's feature to make a .zip file instead of a .7z file.

![zipfile](https://cloud.githubusercontent.com/assets/1912426/12221105/00e7fe42-b742-11e5-8f05-1f16b625f4ba.jpg)

**Comment by aramyle** [comment] 2016-01-10 19:08
Hmm, I did that and it and its not dropping in here. Its labeled as a zip file and I did everything through 7zip like you recommended. Not sure why it's not allowing me to do it. Gonna mess around with it some more, if I get it I'll just edit this post with it in.

**Comment by WrinklyNinja** [comment] 2016-01-10 19:32
You could alternatively upload it to something like Dropbox, OneDrive, Google Drive, etc.

**Comment by FatherPootis** [comment] 2016-01-11 22:05
Hi sorry my reply is a little late, I just deleted the folder completely
and tried relaunching the application. It started fine after that.

**Comment by WrinklyNinja** [comment] 2016-01-15 20:16
Could anyone who can replicate the issue please try doing so with the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (0.8.1-131)?

This build contains improvements to how LOOT loads the settings file, which means if that was the cause, the bug should be fixed and LOOT should open normally.

**Comment by runderscore** [comment] 2016-02-07 09:16
I was having this issue, but using the latest snapshot (LOOT v0.8.1-146-gb199982 (32 bit)) fixed it for me.

**Comment by WrinklyNinja** [comment] 2016-02-07 17:18
OK, closing this then.

**Closed by WrinklyNinja** 2016-02-07 17:18 UTC

**Comment by justicelordneshsuperman** [comment] 2016-07-03 03:14
ok i have problem with LOOT i can post you %LOCALAPPDATA%\LOOT   and screen shot with problem   so loot 091 worked fine and just stoped with white screen with loot name in tab    after deleting    %LOCALAPPDATA%\LOOT     and starting again  loot create files again in  %LOCALAPPDATA%\LOOT  and  same white screen,  so i tried (LOOT v0.8.1-146-gb199982 (32 bit)    and also same problem    do you want me to upload to you  %LOCALAPPDATA%\LOOT    ok im uploading    here it is     [0703/050331:ERROR:child_process_launcher.cc(505)] Failed to launch child process             
[CEFDebugLog.txt](https://github.com/loot/loot/files/344845/CEFDebugLog.txt)
#575
