### ISSUE TITLE
Loot stoped working , Masterfile will not update

### ISSUE THREAD

**Issue by Blatant1960** [loot/loot#883] opened 2018-02-23 00:02 UTC
Hi all
New to modding and using LOOT , it was running fine until this evening now i get the following.[23:50:11.451728] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:50:12.590523] [warning]: No masterlist present at C:\Users\Blatant\AppData\Local\LOOT\Skyrim\masterlist.yaml
[23:50:18.409809] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[23:50:18.410809] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
I have reinstalled it etc but still no good , some help would be appreciated .
Many thanks
Blatant.

**Comment by warmfrost85** [comment] 2018-02-23 00:09
This is a duplicate of #882

**Comment by WrinklyNinja** [comment] 2018-02-23 07:57
Yep, closing this.

**Closed by WrinklyNinja** 2018-02-23 07:57 UTC
