### ISSUE TITLE
Loot Error : remote 'origin' already exists:libgit2 error

### ISSUE THREAD

**Issue by Trelleon75** [loot/loot#1120] opened 2019-06-19 16:49 UTC
Here is what the log says:
[23:22:49.671924] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error

I have no trouble with Skyrim SE and I have 78 mods active, but when I try to update the masterlist for Fallout New Vegas the 'Oh no! something went wrong' message pops out. What am I doing wrong exactly?

**Comment by CptMcSplody** [comment] 2019-06-19 17:03
@Trelleon75 Can you provide a full debug log?
If you don't know how, details for doing so can be found here.
https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html

> Supplying Debug Logs For Application Issues
> 
> If you're experiencing an application issue, you should supply debug logs to help solve the issue. You can do this by following the instructions below.
> 
>     In LOOT's settings, toggle the Enable Debug Logging checkbox on.
>     Run LOOT again to replicate the issue.
>     Upload the log file generated at %LOCALAPPDATA%\LOOT\LOOTDebugLog.txt.

**Comment by Trelleon75** [comment] 2019-06-19 17:54
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3307337/LOOTDebugLog.txt)

There it is

**Comment by CptMcSplody** [comment] 2019-06-19 18:02
> [00:52:26.066500] [warning]: No masterlist present at C:\Users\ASUS\AppData\Local\LOOT\FalloutNV\masterlist.yaml

> [00:52:44.569509] [debug]: Using remote URL https://github.com/loot/falloutnv.git and branch v0.14
> [00:52:44.569531] [debug]: Setting up checkout options uUsing branch v0.14 and filename masterlist.yaml.
> [00:52:44.569548] [trace]: Checking for Git repository at: C:\Users\ASUS\AppData\Local\LOOT\FalloutNV
> [00:52:44.569748] [info]: Repository doesn't exist, cloning the remote repository.
> [00:52:44.570293] [trace]: Target repo path not empty, cloning into temporary directory.

Try deleting the %LOCALAPPDATA%\FalloutNV\.git folder (it may be hidden) it could be that the Git repository got corrupted somehow.

**Comment by Trelleon75** [comment] 2019-06-19 18:46
Hmm... I can't seem to find the git repository in the local app data. There is a folder made by vortex for plugins sorting titled 'falloutnv', but it contains no .git files.

I'm so clueless to all this

**Comment by CptMcSplody** [comment] 2019-06-19 19:05
It's hidden by default, make sure you have hidden items set to visible.

![image](https://user-images.githubusercontent.com/1944639/59793058-86db9800-92cd-11e9-947c-2f6d59534ec7.png)

![image](https://user-images.githubusercontent.com/1944639/59793019-6e6b7d80-92cd-11e9-9dc5-50071116ef12.png)

**Comment by Trelleon75** [comment] 2019-06-19 19:52
Uh yeah, the problem is I have set the hidden items to be visible, yet there's still no .git file to be found. Is this like a really rare case?

**Comment by CptMcSplody** [comment] 2019-06-19 20:01
And that's in`C:\Users\%username%\AppData\Local\LOOT\FalloutNV`?

**Comment by Ortham** [comment] 2019-06-19 20:01
This looks like loot/skyrim#252, but I've not seen anything else like this, and can't spot anything in LOOT's code that would cause this issue - it never tries to create any remotes, which is what I'd expect to be causing an error like `-4; remote 'origin' already exists`... That it happens when cloning a repository is even stranger, since there it's starting from scratch.

**Comment by Trelleon75** [comment] 2019-06-19 20:09
Yep.

**Comment by pStyl3** [comment] 2019-07-25 20:48
@Trelleon75 Do you still have this issue? New libloot and LOOT versions have been released a couple of weeks ago and it would be interesting if that (or anything else you might have tried) did change something for you.

**Comment by Trelleon75** [comment] 2019-07-26 06:23
@pStyl3  Still no changes. Is there any chance that this happens because I pirated the game? I didn't think that's the problem since I also pirated my skyrim and there's no problem, but I figured it's plausible

**Comment by Ortham** [comment] 2019-07-26 06:25
That won't be the cause, but I don't provide support when pirated games are involved, so closing this.

**Closed by Ortham** 2019-07-26 06:25 UTC
Labels: awaiting-feedback
