### ISSUE TITLE
Prerelease: Inconsistent load order for implicit ESMs/ESLs

### ISSUE THREAD

**Issue by Silarn** [loot/loot#833] opened 2017-10-22 09:44 UTC
Now that a build has been semi-released, I've found that the sorting seems to move implicitly-loaded ESMs/ESLs below optional ESMs/ESPs both when first loading the plugin data as well as after sorting.

Of course, this resort is lost on the implicitly loaded plugin files as soon as LOOT is rerun since these files are not recorded in the plugins.txt.

**Comment by Silarn** [comment] 2017-10-22 09:52
# Initial state:
![initial](https://user-images.githubusercontent.com/826174/31860730-a31b47ca-b6e4-11e7-866b-314bcb46347b.png)

# Sorted state:
![sorted](https://user-images.githubusercontent.com/826174/31860733-a832916e-b6e4-11e7-989f-7fa13a322486.png)

# Plugins.txt before and after applied sort:
![appliedplugins](https://user-images.githubusercontent.com/826174/31860736-aa65afde-b6e4-11e7-8401-d901c0a7b230.png)

**Comment by WrinklyNinja** [comment] 2017-10-22 10:19
This is just because LOOT doesn't know about which plugins are implicitly active, and the Fallout 4 and Skyrim SE masterlists haven't yet been updated with the relevant metadata.

**Comment by WrinklyNinja** [comment] 2017-10-27 21:33
This should now be fixed, I've updated the masterlists.

**Comment by Silarn** [comment] 2017-10-31 16:18
Just FYI the initial state of the plugins still seems to be off. The implicit files are being mixed with the custom files. LOOT corrects this after a sort but will reload the order with custom ESMs mixed with the core files again.

**Comment by WrinklyNinja** [comment] 2017-10-31 16:21
What do you mean by "reload the order"?

I'll look into why the initial state isn't correct.

**Comment by Silarn** [comment] 2017-10-31 18:07
Relaunching LOOT with the resorted order.

**Comment by WrinklyNinja** [comment] 2017-10-31 20:31
I can't replicate the initial order being wrong, but it may be related to the root cause of #838. Can you try after replacing the `loot_api.dll` in your LOOT install folder with [this one](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.1-28-gdccc787_crash-fix-win32.7z)?

**Comment by Silarn** [comment] 2017-10-31 22:44
I may not have the most recent prerelease loot build, that version seems to be causing a crash for me. Let me find that again.

**Comment by Silarn** [comment] 2017-10-31 22:53
[CEFDebugLog.txt](https://github.com/loot/loot/files/1432558/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1432559/LOOTDebugLog.txt)

**Comment by Silarn** [comment] 2017-10-31 23:03
As a side note, that build of LOOT API does seem to fix issues people were having using the integrated MO sort.

**Comment by Silarn** [comment] 2017-10-31 23:23
Okay, it works with the protobuf build. Testing.

**Comment by Silarn** [comment] 2017-10-31 23:25
Okay, yes. The protobuf build with the replaced api dll does seem to load correctly. 👍

**Comment by WrinklyNinja** [comment] 2017-11-03 19:25
Closing this as it's now fixed.

**Closed by WrinklyNinja** 2017-11-03 19:25 UTC
