### ISSUE TITLE
LOOT not opening except to empty white page

### ISSUE THREAD

**Issue by Papajack55** [loot/loot#1683] opened 2022-01-27 21:28 UTC
I don't realize what the problem is and it may be just me, BUT, my LOOT opens to a blank white page only. I have tried all different versions of LOOT, but not everyone.

Can anyone help please? I thank you in advance for any and all help.

**Comment by sibir-ine** [comment] 2022-01-27 21:30
@Papajack55 Please see this [Q/A](https://loot.github.io/docs/help/LOOT-FAQs.html#blank-window).

**Comment by sibir-ine** [comment] 2022-02-02 20:37
Closed as a duplicate of #974.

**Closed** 2022-02-02 20:36 UTC
Labels: duplicate
