### ISSUE TITLE
LOOT program is not showing up.

### ISSUE THREAD

**Issue by millhause** [loot/loot#577] opened 2016-05-22 13:48 UTC
I'm currently using the last build (LOOT.0.9.0-0-g44a0d85.32.bit) on windows 7. Yesterday i updated my old version to this one. My old version was working fine, same as this new version the first time i executed it. 

- During the update i didn't unninstall the old version, just overwrited the old files when asked.
- Today the program just dont respond anymore, like i never clicked to execute it.
- Old installation was on Program Files x86 folder.
- Once the program was not working anymore, i unninstalled it via lootunninstall.exe (or something like that) erasing the Data files when propted.
- Reinstalled it on the same folder. Nothing.
- Tried to execute as admin. Nothing
- Unninstalled it again and changed its folder to C:/LOOT. Nothing (same for execute as admin).
- Checked on AppData/local and roaming for LOOT forder. Couldnt find anything,
- Exectuted skyrim till game menu then got back to AppData/local and roaming. Nothing (same for execute loot).

- I hadn't installed anything else on my system or changed any settings in these past 2 days.
- My Java is updated.

Ps.Sorry for the bad english.

**Comment by WrinklyNinja** [comment] 2016-05-22 13:49
So there's no `%LOCALAPPDATA%\LOOT` folder?

**Comment by millhause** [comment] 2016-05-22 13:52
No. Both Local and Roaming have no trace of a LOOT folder. Even after i executed skyrim.

**Comment by millhause** [comment] 2016-05-22 13:55
I tried both, the installer .exe and the 7zip folder in this process by the way. Both had the same results.

**Comment by WrinklyNinja** [comment] 2016-05-22 13:56
Are you running LOOT through Mod Organizer, and were there any error messages when you ran v0.9.0 successfully the first time?

**Comment by WrinklyNinja** [comment] 2016-05-22 13:57
Also, try looking in Task Manager to see if there are any LOOT processes still running - maybe the last run didn't close properly?

**Comment by millhause** [comment] 2016-05-22 14:00
The first time i executed the v0.9.0 was right after its installation process ("open loot" option box). It didn't show any error massages at that time or today.
I already looked on task manager for the process... coldnt find any. Before or right after clicking the program icon.
I already shutted down my pc n turned it on again just to make sure.

**Comment by millhause** [comment] 2016-05-22 14:03
I forgot to mention, i use nexus mod manager but never executed loot through it. I always use its own icon to do it.

**Comment by WrinklyNinja** [comment] 2016-05-22 14:06
I'm not sure what could be going wrong, LOOT doesn't do much before it tries to create its app data folder...

What happens if you create the `%LOCALAPPDATA%\LOOT` folder then run LOOT?

**Comment by millhause** [comment] 2016-05-22 14:07
I'll try that. Does it matters if the folder have its name in captal letters or not?

**Comment by WrinklyNinja** [comment] 2016-05-22 14:08
It shouldn't, Windows' filesystem is case-insensitive, but make it uppercase anyway.

**Comment by millhause** [comment] 2016-05-22 14:10
Nop. Still the same behaviour. But this time i could see the Loot.exe on task manager for 1s. But it vanished with no windows warning.

**Comment by WrinklyNinja** [comment] 2016-05-22 14:12
And there's nothing in the LOOT folder you created?

**Comment by millhause** [comment] 2016-05-22 14:12
It still empty.

**Comment by WrinklyNinja** [comment] 2016-05-22 14:14
If you try running LOOT v0.8.1, does that still work?

**Comment by millhause** [comment] 2016-05-22 14:15
I dont have it anymore. The old files were overwritten when i installed this new version. Can i find the old version installer somewhere?

**Comment by WrinklyNinja** [comment] 2016-05-22 14:16
Yes, [here](https://github.com/loot/loot/releases/tag/v0.8.1).

**Comment by millhause** [comment] 2016-05-22 14:17
Thanks. I'll try that. =)

**Comment by millhause** [comment] 2016-05-22 14:19
YES! IT'S ALIVE! 
For some reason this version worked right from the bat.

**Comment by millhause** [comment] 2016-05-22 14:23
Its currently installed on program files x86, not using admin mode to execute.
The LOOT folder on AppData/Local now have 2 files (CEFDebugLog and settings) and 1 folder (skyrim).
Content from "CEFDebugLog": [0522/112513:ERROR:main_delegate.cc(730)] Could not load cef_extensions.pak

**Comment by WrinklyNinja** [comment] 2016-05-22 14:26
Well, the only code that changed since v0.8.1 that would be run before creating the app data folder is the code that gets the `%LOCALAPPDATA%` path, but I don't know why that isn't working for you. That, or it could be the CEF update is incompatible with your system for some reason, but that seems more unlikely.

I can make some code changes for you to test, but for now just stick to v0.8.1, and I'll let you know when a snapshot build is ready.

**Comment by millhause** [comment] 2016-05-22 14:30
If that will help you, sure.
Actually this old version, working, its completely fine for me.
Let me know if you need any other info. And thanks a lot for the Help WrinklyNinja =)

**Comment by WrinklyNinja** [comment] 2016-05-24 06:31
Could you try the latest [snapshot build]?

**Comment by WrinklyNinja** [comment] 2016-07-02 16:55
Could you try again with the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) in the `autocomplete-filenames-bash-tags` folder?

**Comment by WrinklyNinja** [comment] 2016-07-02 16:57
Actually, closing this as a duplicate of #575, since they seem to be the same issue.

**Closed by WrinklyNinja** 2016-07-02 16:57 UTC
Labels: backend, bug
