### ISSUE TITLE
Worked before latest update

### ISSUE THREAD

**Issue by scheuerman2** [loot/loot#905] opened 2018-03-02 08:14 UTC
I had version 0.12.3 and everything worked fine, I updated to 0.12.4 and now I get this error when trying to update the master list:

Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

This is the log in question:
[20:29:02.707855] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[20:29:02.796860] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[20:29:04.511958] [warning]: No masterlist present at C:\Users\Evil_J\AppData\Local\LOOT\Fallout4\masterlist.yaml
[20:29:14.191512] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[20:29:14.195512] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by SuperSandro2000** [comment] 2018-03-02 08:47
#882

**Comment by WrinklyNinja** [comment] 2018-03-02 09:08
Yep, duplicate of the above, nothing to do with the 0.12.4 update.

**Closed by WrinklyNinja** 2018-03-02 09:08 UTC

**Comment by scheuerman2** [comment] 2018-03-02 09:23
Thanks for the link, solved my problem, I can now update regularly.

Thanks to you as well Ninja, great program you made
