### ISSUE TITLE
Issues with Windows 7 Compatibility

### ISSUE THREAD

**Issue by mpldr** [loot/loot#1701] opened 2022-02-28 09:09 UTC
Hi,
LOOT does not start correctly on Windows 7 even with MSVC installed using the provided Link and 7zip-zstd installed using its installer. On Start the attached screen shows up, and remains. No Material Design UI, no nothing.
![2022-02-28-10-09-24](https://user-images.githubusercontent.com/33086936/155955534-459fa87f-86c7-447e-b33a-c0b8d9da20b0.png)

**Comment by Ortham** [comment] 2022-02-28 09:11
This is a duplicate of #974, fixed for the next release.

**Closed by Ortham** 2022-02-28 09:11 UTC
