### ISSUE TITLE
User groups not set to load after any other groups aren't saved to userlist

### ISSUE THREAD

**Issue by monax3** [loot/loot#1772] opened 2022-08-02 15:16 UTC
To reproduce:

1. Open the group editor
2. Create a new group
3. Drag an arrow from the group to any built-in group
4. Click Save
5. Click Sort Plugins

The result is the message "The group does not exist" until the group is deleted in the group editor

**Comment by sibir-ine** [comment] 2022-08-03 02:23
I can reproduce this in v0.18.3.

**Comment by Ortham** [comment] 2022-08-05 19:19
Yeah, this looks like the other half of the bug I fixed in 51d48aca3d233037dee0e5f61a50e1cfcafa54aa...

**Comment by Ortham** [comment] 2022-08-05 20:25
I think this is now fixed in the `misc` branch, @sibir-ine can you confirm?

**Comment by sibir-ine** [comment] 2022-08-06 03:08
Yup, that appears to have fixed it 👍

**Comment by Ortham** [comment] 2022-08-06 07:20
Fixed in 11d82bb4831477df958fd73f5033a3f3fb21cc56.

**Closed by Ortham** 2022-08-06 07:20 UTC
Labels: bug, backend
