### ISSUE TITLE
Installer 

### ISSUE THREAD

**Issue by capgames** [loot/loot#698] opened 2016-11-09 04:16 UTC
The installer restarts the PC with no dialog and no warning, this has happened twice, 1st time i lost quite a bit of work because of it. I have had this happen on 2 separate occasions, the 2nd time was to check to make sure.

I consider that because it causes an unwarranted restart, the installer is malware

**Comment by WrinklyNinja** [comment] 2016-11-09 07:50
Duplicate of #692.

**Closed by WrinklyNinja** 2016-11-09 07:50 UTC
