### ISSUE TITLE
Skyrim - Loot won't sort my plugins

### ISSUE THREAD

**Issue by Lizard2214** [loot/loot#886] opened 2018-02-24 12:12 UTC
Hi
I have above 6k hours playing Skyrim. I just love this game and I won't change that. 
I use Loot from looooong time, and I neveer have any issue. Never, ever......Tilll to yesterday. 
When I launch Loot everything is ok, but if I prees sort Plugins I receive message 

Error 
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

I Uninstall all mods and game as well. Clean everyting. But that dont help. 

At the moment I have only Skyrim with  DLC no any mods and Loot give me same message.

**Comment by brunoaugusto** [comment] 2018-02-24 12:24
https://github.com/loot/loot/issues/882

**Comment by WrinklyNinja** [comment] 2018-02-24 12:43
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Lizard2214** [comment] 2018-02-24 13:12
[12:08:27.835021] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[12:08:28.949084] [warning]: No masterlist present at C:\Users\Someone\AppData\Local\LOOT\Skyrim\masterlist.yaml
[12:09:34.089810] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[12:09:34.090810] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by WrinklyNinja** [comment] 2018-02-24 13:16
Yes, this is a duplicate of #882.

**Closed by WrinklyNinja** 2018-02-24 13:16 UTC
