### ISSUE TITLE
Loot error

### ISSUE THREAD

**Issue by Splendista** [loot/loot#897] opened 2018-02-26 18:25 UTC
My loot error after updating masterlist
I already search google about this error
I turn off firewall and antivirus
Reinstall loot

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1759799/LOOTDebugLog.txt)

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1759796/LOOTDebugLog.txt)
[23:02:46.055550] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

[23:02:46.102553] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic

[23:02:46.890598] [warning]: No masterlist present at C:\Users\astrcmpz\AppData\Local\LOOT\Skyrim\masterlist.yaml

[23:02:52.796936] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

[23:02:52.797936] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by WrinklyNinja** [comment] 2018-02-26 18:44
This is a duplicate of #882.

**Closed by WrinklyNinja** 2018-02-26 18:44 UTC
