### ISSUE TITLE
Empty space above plugin name

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1783] opened 2022-08-17 07:03 UTC
When decreasing the width of the LOOT window, some plugin cards will have additional empty space added to them above the plugin name, while others stay normal in that regard.

![grafik](https://user-images.githubusercontent.com/10406657/185054839-8000d129-a54d-43a0-9348-1a6f54a00df2.png)

Here's also a .gif showcasing the issue:

![LOOT_NpQYwG0ST2](https://user-images.githubusercontent.com/10406657/185055589-f28bba92-554c-4f68-832f-1b00e97b9ed6.gif)

**Comment by pStyl3** [comment] 2022-08-17 07:09
Also, it seems to me that the more information a plugin card holds besides the plugin name, the greater the potential is for this issue to occur. That being said, there are plugin with no messages and no bash tags below the plugin name, that still have empty space added to them (see `ccbgssse035-petnhound.esl` in the first image).

**Comment by Ortham** [comment] 2022-08-17 07:19
This isn't a size hint cache issue, as the size of the cards don't change when you mouse over them: it looks like this is something like a layout flow issue where some minimum width is being reached, like when a block of text will change where its soft line breaks are. 

The extra height only ever seems to be inserted above the plugin name, and by eye it looks like one text line height's worth of height. I can't spot any pattern in which cards break first though, some of the quickest to break in my load order have the shortest names and least icons, but then the next to go will be one with lots of icons or a longer name. I'll need to investigate this further.

**Comment by pStyl3** [comment] 2022-08-17 07:39
Say you have the following plugin cards:
```
A
B
C
D
E
```

Plugin card `A` and `C` have messages and/or bash tags listed under their plugin names.

It seems to me that in this case, plugin cards `B` and `D`, so the ones following `A` and `C`, will have the empty space above the plugin name. So with other words, `A` and `C` are flowing over into the plugin card immediately after them.

Does that make any sense?

**Comment by Ortham** [comment] 2022-08-17 15:12
Yes, it looks like you're on to something there: every case I see happens to a plugin under one with at least one message (though not all plugins with messages cause the next plugin to get the extra spacing).

**Comment by Ortham** [comment] 2022-08-17 21:26
After changing the styling to colour cards green and the list view background cyan, it looks like the cards are being put in the wrong place, i.e. there's nothing in the extra spaces. I had a look at the size hint cache to see if anything there looks wrong after resizing but all the sizes there look reasonable. 

Having said that, during resizing it looks like there's a round of updates where a much smaller width is used (so giving much larger heights): the width used to calculate the heights is the viewport width rather than the card widths, which are larger (hence the horizontal scroll bars). This seems to be because the minimum width reported by the layout is a lot smaller than the width at which the cards stop shrinking. I'm not yet sure why that is...

**Comment by Ortham** [comment] 2022-08-20 11:12
I've just pushed a change to the `fix-card-sizing` branch that seems to fix the card heights, @pStyl3 can you try it out and see if you still get the issue?

I figured out what the problem is: basically, the height of a card depends on its width due to text wrapping, and all cards should expand to fit the available width. That width is the width of the scrollable area, which is equal to the largest minimum width of all the cards in it (i.e. if the cards are squashed as narrow as they can get, the scrollable area will just fit the largest card). This is a problem because to know how wide to make the scrollable area, you need to know what all the cards' minimum widths are, and this is done by calculating all the card sizes, but to get the correct heights you need to know the width of the scrollable area...

The solution I've chosen is to prepare all of the cards used to calculate the sizes ahead of time so that when the size of a card is calculated the whole list of cards can be searched to find the largest minimum width. This does mean that I need to make sure all the cards are created whenever the underlying data is added to or updated, but I think I've covered that.

**Comment by pStyl3** [comment] 2022-08-20 11:29
> [13:24:01.688251] [error]: Caught exception when getting file revision, assuming file is not up to date: %USERPROFILE%\AppData\Local\LOOT\games\Fallout3\masterlist.yaml is not a regular file

Using `loot_0.18.3-37-g0ac980b_fix-card-sizing-win64.7z` LOOT crashes when updating the masterlist for a game the first time, and LOOTDebugLog.txt contains the above message.

**Comment by pStyl3** [comment] 2022-08-20 11:35
Aside from the mentioned issue of LOOT crashing, the problem with wrongly placed plugin cards seems to be fixed. 👍

Thanks!

**Comment by Ortham** [comment] 2022-08-20 16:55
Damn, it looks like the data changed signal is reaching the delegate before it reaches the code that updates the sizing cache...

I can avoid the crash by updating the cache in the delegate if it hasn't already been updated, but I can't figure out how to fix the order of signal processing - I think that is unlikely to result in sizing issues though.

@pStyl3 can you test again?

**Comment by pStyl3** [comment] 2022-08-20 17:15
With `loot_0.18.3-40-g912bc9d_fix-card-sizing-win64.7z` the crash is gone and and as with the previous snapshot, the plugin cards are getting placed correctly!

That being said, I've noticed the following behaviour:

![LOOT_Huy78pRquL](https://user-images.githubusercontent.com/10406657/185758849-100d93e7-0e43-47ee-ae88-1a2ea6bf0b4c.gif)

Now the cleaning info as well as the bash tags won't wrap correctly.

**Comment by Ortham** [comment] 2022-08-20 17:19
What happens if you mouse over one of the cards that has cut-off text?

**Comment by pStyl3** [comment] 2022-08-20 17:34
It's the correct build, but I'm also unsure about the exact reproduction steps. It doesn't seem to always happen .. I think this was after I disabled/reenabled the `Hide Bash Tags` and `Hide Sources` filter.

**Comment by pStyl3** [comment] 2022-08-20 17:58
I can pretty reliably reproduce the issue with `ccbgssse043-crosselv.esl` ([Elite Crossbows](https://en.uesp.net/wiki/Skyrim:Elite_Crossbows)) by
- first deleting the `LOOT` folder `%localappdata%`
- starting LOOT
- updating the SSE masterlist
- deactivating `Hide Bash Tags` and `Hide Sources` filter
- decreasing the width of the LOOT window

**Comment by pStyl3** [comment] 2022-08-20 18:15
> What happens if you mouse over one of the cards that has cut-off text?

Ups, I forgot to answer your question. 😛 There's nothing really happening, if I mouse over the wrongly wrapped elements.

**Comment by Ortham** [comment] 2022-08-20 18:37
I don't have `ccbgssse043-crosselv.esl`, but following those steps I do see USSEP's current bash tags get cut off. 

I think I see what's going on: when there's no masterlist, the general info card is very wide ("N/A: No masterlist prelude present" stretches it out). This cache entry sticks around after the card content changes (which creates a new cache entry), so card heights are calculated using too wide a width (basically the opposite problem to before).

Looks like I'll need to add cache invalidation after all.

**Comment by Ortham** [comment] 2022-08-20 23:35
@pStyl3 The latest `fix-card-sizing` build should fix that issue, can you confirm?

**Comment by pStyl3** [comment] 2022-08-21 03:40
Yes, it seems to have been fixed! Everything looks good now, with one last thing.
- delete the `LOOT` folder in `%localappdata%`
- start LOOT
- Update the masterlist

This will work as always, but LOOTDebugLog.txt will log the following:

> [05:36:34.246626] [error]: Caught exception when getting file revision, assuming file is not up to date: %USERPROFILE%\AppData\Local\LOOT\prelude\prelude.yaml is not a regular file
[05:36:34.310003] [error]: Caught exception when getting file revision, assuming file is not up to date: %USERPROFILE%\AppData\Local\LOOT\games\Oblivion\masterlist.yaml is not a regular file

**Comment by Ortham** [comment] 2022-08-21 08:07
Closing this as done as of 0f8060011ae06e5ca1b4bfaad22b479f232b9bae.

> This will work as always, but LOOTDebugLog.txt will log the following:

That's not new, but I've changed it so it won't try to get the revision if the file doesn't exist.

**Closed by Ortham** 2022-08-21 08:07 UTC
Labels: bug, ui
