### ISSUE TITLE
LOOT Sorting Issue 

### ISSUE THREAD

**Issue by IEatLittleBoys** [loot/loot#892] opened 2018-02-24 20:50 UTC
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1755218/LOOTDebugLog.txt)
I get these errors when trying to sort LOOT for TES Skyrim, non special edition

**Comment by pStyl3** [comment] 2018-02-24 21:51
Update LOOT to version 0.12.4, install all recommended Windows 7 updates and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.

This is a duplicate of #882.

**Closed** 2018-02-25 08:45 UTC
Labels: duplicate
