### ISSUE TITLE
Constant "Oh no, something went wrong!" error every time I launch LOOT

### ISSUE THREAD

**Issue by Warzychewka** [loot/loot#1164] opened 2019-10-24 14:08 UTC
Hi, I've made a github account to write about my LOOT issue. 

As stated in the topic, every time I launch the newest available version of LOOT it returns the "Oh no, something went wrong!" error and sends me to LOOTDebugLog.txt. It happens when I launch it through Mod Organizer 2 and when I try to launch it 'on its own', I've tried reinstalling but it didn't help.

Since I'd like to know what's the issue and be able to sort my load order, could you take a look at my Log and tell me what's causing the error?

(I've added my LOOTDebugLog as an attachment to this post, but if that doesn't work here's the pastebin link:)
https://pastebin.com/4gxF5aEj

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3767903/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2019-10-24 14:38
This looks like a duplicate of #1158, please post a comment in that issue saying what operating system you're running, and try the suggestions given in that issue.

**Closed by Ortham** 2019-10-24 14:38 UTC
