### ISSUE TITLE
LOOT(12.4/12.5) crashed on startup on MO.

### ISSUE THREAD

**Issue by millmill12345** [loot/loot#919] opened 2018-03-19 14:20 UTC
I get crashed on LOOT loading Skyrim LE with 250+ mods. This was never occurred by previous LOOT. Loading vanilla&DLC only, this issue is not occurred too.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1825296/LOOTDebugLog.txt)

**Comment by SuperSandro2000** [comment] 2018-03-19 17:41
Maybe you two should try it with MO2 as MO1 is severely out of date.

**Comment by WrinklyNinja** [comment] 2018-03-19 17:44
If an issue occurs when running through MO and doesn't when not, then it's a problem with MO and there's not a whole lot I can do about it.

**Comment by SuperSandro2000** [comment] 2018-03-19 18:19
If it does ocur with the Beta 0.2 build from Discord open an issue here: modorganizer2/modorganizer

**Comment by VOiDProXy** [comment] 2018-03-20 23:05
Like the previous posters, I too had issues with ModOrganizer (aka MO) and Load Order Optimization Tool (?) (aka LOOT) working recently as well,

I fixed the issue I was having by checking my LOOTDebugLog.txt inside %LOCALAPPDATA%\LOOT\
I found the following line near the bottom of the txt file:

>  Exception while executing query: No plugin "HighResTexturePack01.esp" exists.

I went to MO and for the sake of science, disabled each of my hundreds of individual "mods" on the left-hand side of MO. I do **not** believe that _you_ have to do this step, it's really painful to have to do this and I don't recommend it unless you're desperate or to find out if you have some bad mod screwing with LOOT.

Once my load order was down to the basic ESMs and ESPs, I re-enabled the HighResTexturePack (HRTP) ESPs and launched LOOT's executable from inside MO.
I received no "LOOT has stopped working sending your stuff to Microsoft's collective rectum" pop-up and there was no red error message at the top of Loot's notices. LOOT loaded up fine, displaying all mods I expected to see. Including the HRTP ESPs I had enabled.

So I closed out LOOT, went back to MO and deselected them (the HRTP ESPs) from my load order and checked my Archives tab to make sure they were checked there and proceeded to launch LOOT again. LOOT again was able to launch successfully and the empty HighResTexturePack## ESPs were once again gone from the load order. Great!

I'm now throwing a handful of mods on one at a time and LOOT seems to be back to its normal awesome self on my end. Hopefully, someone can benefit from this. In the end, I did update to the latest loot (the one that was released 3 days ago at the time of the post date) but never deleted my AppData for LOOT. That was going to be my next step after trying what I did.

In my case, I think the error was simply that LOOT was expecting one of the HRTP ESPs that I had disabled in MO because of the Archive feature in MO. If you have any empty ESPs disabled in MO, try to re-enable them and try to launch LOOT.

**Comment by SuperSandro2000** [comment] 2018-03-20 23:40
Tip: try selecting multiple items in the left mo tab and hit space.

**Comment by Ibbanez** [comment] 2018-04-07 16:32
Alright guys, I was having the same issues as this.  My first thought was to set LOOT.exe to run as Admin.  MO doesn't like this so much, and throws up an error saying that this is requesting elevated permissions, do you want to run, blah blah blah.  If you hit yes, it loads, then crashes like everyone else.  I started looking in the logs.  It looks like it can't connect to google for some reason for some fonts.. So I took off run as admin, went into my firewall, and gave full access to LOOT.exe, and now it loads from within MO.  This is loot 12.5.  I am on Windows 10 1709 64 bit ...  For those of you having issues, just try it.  Its working perfectly for me now.  Thanks.

**Comment by Ibbanez** [comment] 2018-04-08 00:53
well idk then,....  I literally added it to my firewall exceptions, and it no longer crashed from MO...  If that wasn't it, I'll still take it as I was able to sort and get it to not crash.  Thanks for responding though.  I'll recheck my logs now.

**Comment by Ibbanez** [comment] 2018-04-08 06:59
NVM, back to crashing.. Well it worked for a few times... Sigh...

**Comment by zxysm** [comment] 2018-04-10 17:11
Indeed, I also encountered the same problem and are preparing to replace MO 2.0.

**Comment by zxysm** [comment] 2018-04-11 05:56
Yes, upgrading to MO 2.x solves this problem.

**Comment by WrinklyNinja** [comment] 2018-05-26 16:41
Closing this as running LOOT through Mod Organiser is unsupported, as most issues reported by Mod Organiser users are caused by Mod Organiser, which I can't do anything about. This looks like such an issue.

**Closed by WrinklyNinja** 2018-05-26 16:41 UTC
