### ISSUE TITLE
Won't Save New Load Order Again

### ISSUE THREAD

**Issue by Nofsdad** [loot/loot#818] opened 2017-08-27 15:01 UTC
LOOT has stopped saving my load order again.  The latest error it throws is 
[07:45:27.129167] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic

Yesterday it was
[07:54:32.536422] [error]: libloadorder failed to set the load order. Details: "C:\Users\Tom_PC2\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error: Libloadorder error

Since I have no idea what any of that means I'm at a total loss as to what to do.  I'm in the middle of rebuilding my entire game so it comes at a particularly bad time too.

**Comment by WrinklyNinja** [comment] 2017-08-27 19:24
The `blocking load of resource` warning is intended behaviour. `"C:\Users\Tom_PC2\AppData\Local\Fallout4\plugins.txt" could not be written` is probably because your `plugins.txt` is read-only.

**Comment by WrinklyNinja** [comment] 2017-12-08 20:19
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed by WrinklyNinja** 2017-12-08 20:19 UTC
Labels: awaiting-feedback
