### ISSUE TITLE
Loot not seeing Fallout 4

### ISSUE THREAD

**Issue by RedWolf11** [loot/loot#544] opened 2016-02-24 22:55 UTC
does anybody else have this issue?

**Comment by Freso** [comment] 2016-02-24 23:02
What version of LOOT are you using? Where did you download it from?

**Comment by RedWolf11** [comment] 2016-02-24 23:05
https://loot.github.io/
8.1

**Comment by Freso** [comment] 2016-02-24 23:12
You need to use one of the snapshot builds then.

Duplicate of #504.

**Closed by Freso** 2016-02-24 23:12 UTC
Labels: duplicate
