### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by azdada4747** [loot/loot#1907] opened 2023-09-02 22:08 UTC
Hello, I have a problem.
When running LOOT gives an error: "failed to read plugin list ''

**Comment by pStyl3** [comment] 2023-09-02 22:14
Please enable debug logging in LOOTs settings, reproduce the issue, and provide us with the resulting `LOOTDebugLog.txt`.
See [Supplying Debug Logs For Application Issues](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log) for more information.

**Comment by azdada4747** [comment] 2023-09-03 07:02
[LOOTDebugLog.txt](https://github.com/loot/loot/files/12505332/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2023-09-03 07:15
It looks like you're using a very old version of LOOT, try updating to the latest release.

**Comment by azdada4747** [comment] 2023-09-03 07:27
I updated LOOT and tried again. Now another error is thrown:
failed to open to rewrite it
[LOOTDebugLog.txt](https://github.com/loot/loot/files/12505366/LOOTDebugLog.txt)

**Comment by pStyl3** [comment] 2023-09-03 07:35
The log shows that you are still not using the latest masterlist branch `v0.18`, but instead `v0.17`. Update to LOOT v0.20.0, if you haven't already, then go to `C:\%localappdata%` and delete the `LOOT` folder there. Then start LOOT, update your masterlist and try sorting your plugins once more. If it doesn't work out, make sure you've enabled debug logging within LOOTs settings (judging from your last log, I'm not sure you have), and provide us once again with your debug log.

**Comment by azdada4747** [comment] 2023-09-03 08:27
I installed LOOT v0.20.0 but it won't start. No errors are output. I have Windows 7

**Comment by pStyl3** [comment] 2023-09-03 08:54
Support for Windows 7 was removed in v0.20.0. As such, if you want to use LOOT while being on Windows 7, uninstall LOOT v0.20.0 and install the last version before the current one, so `LOOT v0.19.1`. All other steps from my previous post apply, so make sure the delete the `LOOT` folder in your local appddata folder.

**Comment by azdada4747** [comment] 2023-09-03 11:31
I apologize for the delays and thank you so much for the quick replies.

I installed LOOT v0.LOOT v0.19.1 but when I start it I get an error:

entry Procedure point createdxgifactory2 could not be located in DLL dxgi.dll

 If I download this dll and try to run it again, I get an error:

entry Procedure point SystemParametersInfoForDpi could not be located in DLL USER32.dll

**Comment by pStyl3** [comment] 2023-09-03 18:57
https://github.com/loot/loot/issues/1638#issuecomment-1003327684

Okay, so the "problem" (in your case) stems not only from Windows 7 alone, but also the fact that we reimplemented LOOTs GUI using Qt in `v0.18.0`. Therefore you might need to use the version prior to that, which is `LOOT v0.17.0` - then with the `v0.17` masterlist branch.

Which isn't ideal, obviously. The `v0.17` masterlist branch doesn't receive any updates anymore, nor do I can *or* want to recommenend using an outdated version of LOOT. My advise can only be, that you install a new OS, Windows 10 or 11.

Since we cannot provide any more (useful) support and the users problems stems from using an very old OS, I'll close this issue.

**Closed by pStyl3** 2023-09-03 18:57 UTC
Labels: invalid
