### ISSUE TITLE
Masterlist update error

### ISSUE THREAD

**Issue by EscondeR** [loot/loot#1173] opened 2019-12-22 19:51 UTC
Upon trying to update (download after fresh install) the masterlist for SSE, I get the following error:

`[22:44:01.002510] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:44:02.418591] [warning]: No masterlist present at C:\Users\ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[22:44:02.773612] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[22:44:03.228638] [warning]: No masterlist present at C:\Users\ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[22:44:05.161748] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[22:44:23.658806] [error]: Could not delete temporary repository path "C:\Users\836D~1\AppData\Local\Temp\LOOT-Skyrim Special Edition-2fd8a611-00f8-489b-808f-26d0f1466bd3": remove_all: Îòêàçàíî â äîñòóïå.
: "C:\Users\836D~1\AppData\Local\Temp\LOOT-Skyrim Special Edition-2fd8a611-00f8-489b-808f-26d0f1466bd3"
[22:44:24.710866] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (ab002f55736572732fd090d0b4d0bcd0b8d0bdd0): libgit2 error
[22:44:24.711867] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5761:9231)`

Masterlists for Morrowind, Oblivion, Fallout NV, Fallout 4 and even regular Skyrim (LE) are updating normally at the same time (same LOOT version, same session, w/o restart).
Please assist with that issue!
It looks like the latest masterlist for SSE is corrupt.

**Comment by CptMcSplody** [comment] 2019-12-23 01:48
Duplicate of https://github.com/loot/loot/issues/1158

**Closed by CptMcSplody** 2019-12-23 01:48 UTC
Labels: duplicate
