### ISSUE TITLE
Improve groups editor further

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1750] opened 2022-05-02 23:27 UTC
@IllusiveMan196 made a few suggestions & raised some issues with the groups editor that I've further investigated & compounded on here, along with a few suggestions of my own. They can of course be rejected or split into separate issues as deemed appropriate:

### Bugs

- [x] Don't delete unconnected groups on saving & exiting (either at all or just when the group has plugins)
- [x] Don't display plugins assigned to deleted group as assigned to first group alphabetically in metadata editor (maybe display deleted group name if possible or some sort of truncated error message like _Group unavailable_ or _Group deleted_?)

### Minor improvements

- [x] Save groups editor window position & size
- [x] Add **Reset** button to reset groups graph node positions to default
- [x] Add confirmation prompt before exiting without saving (i.e., through the __Close__ or __Cancel__ buttons) if any changes were made

**Comment by Ortham** [comment] 2022-05-08 15:31
The two bugs have been fixed in 51d48aca3d233037dee0e5f61a50e1cfcafa54aa and 9c6eb8e5c7f70d6cc1722eca252968628d63aa9a.

**Comment by Ortham** [comment] 2022-08-06 21:33
Saving the groups editor window position has been implemented in 0f9e0504e0a1fa327fe1584f74e0677030e6098d.

**Comment by sibir-ine** [comment] 2022-08-07 00:35
Testing it & all it appears to save is maximized state. Also, when closing the maximized window through the _Save_ or _Cancel_ buttons, the contents of the window appear to be reset to their original size:

![image](https://user-images.githubusercontent.com/69141501/183270118-ddbb794f-2287-4a80-bf19-df604be4754a.png)

**Comment by Ortham** [comment] 2022-08-07 06:27
> The only oddity I noticed is that when the window is maximized & closed using the exit button specifically, the previous window size is overwritten with the maximized window size.

That seems to be a Qt bug, because it doesn't happen when I:

1. maximise the window
2. close the window
3. close LOOT
4. reopen LOOT
5. reopen the window
6. un-maximise it

but does happen if I:

1. maximise the window
2. close the window
3. reopen the window
4. un-maximise it.

The change I made only deals with saving positions when LOOT is closed, window positions were already remembered while LOOT stays open, that's out-of-the-box behaviour.

**Comment by Ortham** [comment] 2022-08-07 06:31
Also I started to implement the reset layout button for the groups editor, but it turns out that there isn't a single layout - resetting multiple times in a row will flip positions around the horizontal axis, e.g.

![image](https://user-images.githubusercontent.com/2430738/183278293-ad23974c-1b5f-44e7-9450-2c3c31b620e1.png)

![image](https://user-images.githubusercontent.com/2430738/183278299-49ee528a-602f-4e08-bb32-d3ddcc27ba2a.png)

![image](https://user-images.githubusercontent.com/2430738/183278308-599a3c1a-765f-4c54-87c3-e4110f1b915e.png)

So I think calling this a "reset" would be wrong, maybe it should be named something like "auto-layout" instead? I'm struggling to come up with an obvious term for this...

**Comment by sibir-ine** [comment] 2022-08-07 07:00
Maybe something like _Auto calculate layout_ or _Auto calculate positions_? Or with _compute_ instead since it's shorter? Or maybe _Auto arrange nodes_ or _Auto arrange groups_? _Auto arrange_ might even be enough on its own.

**Comment by Ortham** [comment] 2022-08-07 08:20
I've gone with "Auto arrange groups" in the `auto-arrange-groups`, what do you think?

**Comment by sibir-ine** [comment] 2022-08-07 08:36
It works really well 👍

**Comment by Ortham** [comment] 2022-08-07 08:42
For the confirmation prompt, would you consider moving group positions around in the graph to be a change worth prompting about, or is that just for node and edge changes?

**Comment by sibir-ine** [comment] 2022-08-07 08:46
Yeah, I think it's worth including rearrangements. If a user spends some time rearranging their groups to make them easier to work with, I imagine it would also be quite frustrating if they accidentally closed the window without saving & lost that time.

**Comment by Ortham** [comment] 2022-08-07 12:02
I've added a prompt when closing the groups editor with unsaved changes in the `prompt-groups-editor-discard` branch.

**Comment by sibir-ine** [comment] 2022-08-07 12:08
Works great 👍

**Comment by pStyl3** [comment] 2022-08-10 14:59
1. Open groups editor
2. Move a group to a different position
3. Auto arrange groups
4. Close the groups editor via `Cancel`

This will be recognized as an unsaved change and therefore I need to decide if I want to discard these changes or not. I get that technically the groups position has been changed two times (first manually, then by the auto arrage feature), though for the user everything is the same before and after.

Should we change it so that in such a case the change is "silently discarded" automatically, or that this isn't recognized as a change to begin with?

**Comment by Ortham** [comment] 2022-08-21 12:30
@pStyl3 I've made changes in the `better-change-detection` branch, can you try it out and see what you think?

**Comment by pStyl3** [comment] 2022-08-21 12:47
It seems to work, but only when `Save` has been used within the groups editor at least once. The first time you open the groups editor, simply clicking on the X button immediately afterwards to close it will ask me, if I want to discard changes or not.

**Comment by Ortham** [comment] 2022-08-21 12:53
I can't replicate that - it might be because too much was going into your userlist before, can you share it?

**Comment by pStyl3** [comment] 2022-08-21 12:57
I've deleted the `LOOT` folder in `%localappdata%` beforehand, so there was no userlist invovled.

Here's another gif:

![LOOT_StYrLBEDu7](https://user-images.githubusercontent.com/10406657/185791981-5e68ffe2-d152-42ad-a50a-0345e628c354.gif)

**Comment by Ortham** [comment] 2022-08-21 12:59
OK, I don't know what changed but I'm getting it now.

**Comment by Ortham** [comment] 2022-08-21 13:05
Oh right, it's because if you don't have any positions saved, the first time you open the editor it'll set them, so there will have been changes, just not anything you care about. I'll add an exception for that case.

**Comment by Ortham** [comment] 2022-08-21 14:00
@pStyl3 that should now be fixed in the latest build, can you test again?

**Comment by pStyl3** [comment] 2022-08-21 14:10
Confirmed to be fixed.

I don't know if it's intended or not, but using the auto arrange feature with the latest snapshot will log this warning:

> [16:07:40.513817] [warning]: Failed to set node positions from stored data: Failed to set node positions, could not find position for Dynamic LOD

`Dynamic LOD` is the last group from SSE. It seems that the log always mentions the individual games' last group.

**Comment by Ortham** [comment] 2022-08-21 14:23
I don't think that's new, but I've changed it to not even try if there is no stored data to set positions from.

**Comment by Ortham** [comment] 2022-08-21 14:38
Done as of 0a4eb568a916fba058ec0e9b4cfcbd165f52cedc - I've moved the two big new features that were originally in the OP into separate tickets.

**Closed by Ortham** 2022-08-21 14:38 UTC
Labels: bug, enhancement, ui
