### ISSUE TITLE
LOOT error -17 "unknown certificate check failure"

### ISSUE THREAD

**Issue by Clover10123** [loot/loot#894] opened 2018-02-24 23:08 UTC
I'm running Win 8 on my computer. LOOT is suddenly giving me these error messages when I try to update my masterlist.

[16:57:17.484730] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[16:57:22.431353] [error]: "True Soldiers.esp" requires "Weapons & Armor Fixes_Remade.esp", but it is missing.
[16:57:22.435353] [error]: "True Soldiers.esp" requires "Weapons & Armor Fixes_Remade.esp", but it is missing.
[17:01:59.286256] [error]: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[17:02:42.245672] [error]: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

Ignore the middle two, I was still installing some files.  But I try to update the master list, and it gives me the same error each time.  Loot was working just fine a few days ago. What is going on and how do I fix this?

**Comment by SuperSandro2000** [comment] 2018-02-24 23:45
Dupe #882

**Comment by pStyl3** [comment] 2018-02-25 07:24
Update LOOT to version 0.12.4, install all recommended Windows updates and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.

As SuperSandro2000 said, this is a duplicate of issue 882.

**Closed** 2018-02-25 08:35 UTC
Labels: duplicate
