### ISSUE TITLE
Add filter to show only warning & error messages

### ISSUE THREAD

**Issue by Prepubescent-Blastoise** [loot/loot#1715] opened 2022-03-12 22:09 UTC
It would be nice to have a way to acknowledge warnings/errors to make them disappear until the masterlist warning updates. Currently the right pane of Loot is very busy and if I have addressed a warning, I'd rather remove that one warning as opposed to hiding them all, which is what I currently do.

It would also nice to have a dedicated tab to view all warnings/errors, or be able to double click/right click the error line to view a summary as opposed to searching through a list of hundreds of plugins to find them.

**Comment by Ortham** [comment] 2022-03-12 22:51
The first paragraph is a duplicate of #1083.

What do you mean by clicking the error line, what error line?

**Comment by Prepubescent-Blastoise** [comment] 2022-03-12 22:53
Meaning the top of the right pane where is says: Errors: X number

**Comment by Ortham** [comment] 2022-03-13 00:28
For viewing only warnings and errors, does the combination of the following filters not have the same effect?

- Hide Bash Tags
- Hide Sources
- Hide notes
- Hide messageless plugins

**Comment by Ortham** [comment] 2022-03-14 11:53
The content filters were fixed in 82ca7e01ca7a8307d1937b3a5e8160e775e25156.

**Comment by pStyl3** [comment] 2022-03-29 21:13
Seems to work. 👍

**Comment by Ortham** [comment] 2022-03-30 07:30
Done in dfd96b03780659e72fd357496031d0e7ef336298.

**Comment by sibir-ine** [comment] 2022-07-16 03:35
Would it be possible to restore the previous filter configuration when disabling this filter instead of disabling all of the included filters? We disable **Hide Bash Tags** & **Hide Sources** by default, so it's a bit awkward for this intended behavior to be undone by using a filter that doesn't immediately appear to be related.

**Comment by Ortham** [comment] 2022-08-15 17:59
> @Ortham, would it be possible to restore the previous filter configuration when disabling this filter instead of disabling all of the included filters? We disable **Hide Bash Tags** & **Hide Sources** by default, so it's a bit awkward for this intended behavior to be undone by using a filter that doesn't immediately appear to be related.

@sibir-ine I've done this in the `filter-memory` branch, try it out and see if it behaves as you expect?

**Comment by sibir-ine** [comment] 2022-08-16 02:41
Yup, it works 👍

**Comment by Ortham** [comment] 2022-08-16 19:48
Done in 1bdee986301ddc300df0afad2a61cd2d21a74da2.

**Closed by Ortham** 2022-08-16 19:48 UTC
Labels: enhancement, ui
