### ISSUE TITLE
Blank UI when launched through Mod Organiser

### ISSUE THREAD

**Issue by reybalgs** [loot/loot#482] opened 2015-08-31 07:22 UTC
Hi,

I've been using LOOT alongside Mod Organizer for a long time, and I was pretty surprised when, for some reason, LOOT isn't showing anything at all when I launched it through MO. It's been working fine in the past few days, however.

[Here's how it looks like on my end](http://i.imgur.com/xZut0Vj.png). The window shows up fine but nothing else follows. As you can see I can't do anything useful with the UI not actually showing up. Minimizing and restoring the window doesn't work.

At that time I was using LOOT 0.7, so I checked the repo if there's a new release. Turns out 0.8 is already out so I updated (by grabbing the latest installer). However, the problem still persists.

I tried running LOOT directly from Explorer inside its directory. The UI is blank for quite some time, but after about a minute or two it starts up normally, however, it's not really useful for me at that point as I use MO and all my third-party ESMs and ESPs are absent from the list. Running LOOT through MO still doesn't work. I could try waiting for it and hope it works after maybe an hour but having to wait hours just so that I can manage my load order is a frustrating idea.

I turned on `enableDebugLogging` in the `settings.yaml` file, ran LOOT through MO again, and here's the resulting log:

    [0831/150942:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
    [0831/150942:ERROR:main_delegate.cc(567)] Could not load locale pak for en-US
    [0831/150942:WARNING:resource_bundle.cc(501)] locale resources are not loaded
    [0831/150942:ERROR:child_process_launcher.cc(479)] Failed to launch child process
    [0831/150942:ERROR:child_process_launcher.cc(479)] Failed to launch child process

Apologies in advance if all the information I've submitted isn't that quite helpful. I'll be ready to answer any follow up questions that you may have. Additionally I'll also try checking if this is an MO issue (I currently use an outdated version of MO), and I'll update this issue if anything useful turns up.

Cheers,

**Comment by reybalgs** [comment] 2015-08-31 07:24
Just updated MO to 1.3.8. LOOT still doesn't show up after launching it through MO, after 2 minutes of waiting.

**Comment by reybalgs** [comment] 2015-08-31 07:38
Used MO's built in "Sort" function which is apparently also built on LOOT, it didn't work, then I tried launching LOOT again and it seems to work now. No idea why. Anyway, I think this issue could be closed now, apologies if I wasted anybody's time trying to look into this when I could have fixed it myself. I'm kind of curious as to what caused it in the first place though.

**Comment by WrinklyNinja** [comment] 2015-08-31 08:59
[Try adding](https://github.com/loot/loot.github.io/wiki/LOOT-FAQs#loots-window-is-blank-when-im-starting-it-through-mod-organizer-whats-up) the `--single-process` argument when launching LOOT through MO.

**Comment by pStyl3** [comment] 2015-08-31 09:12
Hey @reybalgs
Would you mind answering me a few questions? But before that, here's the solution to "bypass" the problem:

Click on MO's [gear icon](http://abload.de/img/1qdjc6.png) to open up the [Modify Executables](http://abload.de/img/2kuj1v.png) window and add `--single-process` in the "Arguments" field of your LOOT entry (instead of `--game=Skyrim` as in the second picture). That will bypass the problem, that is unfortunately still given even with the very latest pre-release builds of LOOT (snapshot 0.8.0-7) and MO (pre-release build 1.3.9).

Questions:
- Where do you have MO/Steam/LOOT installed to? Could you provide file paths?
- Do you run any of the above mentioned folders with administrator rights?
- What are your [User Account Control](https://en.wikipedia.org/wiki/User_Account_Control) settings (UAC)? [Here](http://windows.microsoft.com/en-us/windows7/how-do-i-change-the-behavior-of-user-account-control-by-using-the-slider) is a link which shows how you can access the UAC settings.
- Are you a premium user on Nexus?
- What is the max. speed your internet connection is capable of while downloading files? Do you usually max. out this speed when downloading mods from the Nexus?
- Do you, by chance, did experience the blank screen after you performed the following process:
1) Close MO.
2) Download a file from the Nexus, so that MO gets automatically started through this act of downloading said file.
3) Try to run LOOT from within MO.

Because, that is a way some people have found is a reliable way to reproduce the blank screen bug (while some others still cannot reproduce it using this method). Or, do you experience the blank screen if you follow this second procedure:
1) Start MO normally.
2) Try to run LOOT from within MO.

I know these are a lot of (sensitive) questions, but it would really help to further pin down the exact reproduction steps, if you could answer them. Thank you!

**Comment by reybalgs** [comment] 2015-08-31 09:45
To answer your questions:

* Where do you have MO/Steam/LOOT installed to? Could you provide file paths?

  LOOT's installed inside the default Program Files (x86) dir on my C: volume, while Steam (actually just the library) and MO are installed in a separate drive/volume (E:\Games\).

* Do you run any of the above mentioned folders with administrator rights?

  No, because I don't think that's a good idea.

* What are your User Account Control settings (UAC)? Here is a link which shows how you can access the UAC settings.

  It's set to the default for Windows 7, which is "Notify me only when programs try to make changes to my computer".

* Are you a premium user on Nexus?

  No.

* What is the max. speed your internet connection is capable of while downloading files? Do you usually max. out this speed when downloading mods from the Nexus?

  My download speed on the Nexus typically caps at 500kB/s, though a lot of outside factors usually bring this down to around 300kB/s max.

* Do you, by chance, did experience the blank screen after you performed the following process:

  I did what you told me and yes, LOOT's UI doesn't show up when I start MO by clicking on an NMM link on the Nexus. If it helps, I didn't let the download of the mod I clicked finish before I started LOOT through MO.

* Or, do you experience the blank screen if you follow this second procedure:

 Did that but LOOT runs as it normally should now.

I haven't read the FAQs well enough so I neglected to try out the `--single-process` argument, sorry about that. I'll stick that arg in my MO executable settings for LOOT for now until the issue gets fixed.

Hope this helps.

**Comment by WrinklyNinja** [comment] 2015-09-20 09:29
Reopening this to hopefully reduce duplicate issue reports.

**Comment by FletcherVK** [comment] 2015-12-17 19:36
I began having this problem - maybe 2 or 4 weeks ago? Running ModOrganizer as administrator solved the problem. But I had been using them together fine, and never had to run MO as administrator before.

(FYI, yes, the --single-process argument does allow me to open MO normally.)

**Comment by WrinklyNinja** [comment] 2016-03-08 22:24
@pStyl3 reported that this was fixed after f46f9f96e00f5a9e1dce33fd46664e7a41d2f517, so Chromium's sandboxing was probably having issues with MO's method of launching applications. I'll leave this issue open until v0.9 ships though, to keep avoiding duplicate issues.

**Comment by pStyl3** [comment] 2016-03-10 19:21
Yes, from my point of view and to my best knowledge, this issue was fixed by that change. I also can confirm, that snapshot `LOOT v0.8.1-231-g543158b (32 bit)` (so several iterations later than the snapshot build that introduced the fix) is "still" working correctly. As I see it, LOOT 0.9.0 will fix the issue for everyone.

**Comment by WrinklyNinja** [comment] 2016-05-30 10:52
Closing this now that v0.9.0 has shipped.

**Closed by WrinklyNinja** 2016-05-30 10:52 UTC
