### ISSUE TITLE
Skyrim sorting plugins error

### ISSUE THREAD

**Issue by Lodrex** [loot/loot#895] opened 2018-02-26 15:27 UTC
Since the last update i'm getting an error message and plugins won't get sorted, here is the log:

> [17:22:36.874550] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
> [17:22:36.936554] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> [17:22:38.078619] [warning]: No masterlist present at C:\Users\Kostas\AppData\Local\LOOT\Skyrim\masterlist.yaml
> [17:22:42.248857] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
> [17:22:42.249858] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
>     at onFailure (http://loot/ui/js/query.js:43:16)

**Comment by WrinklyNinja** [comment] 2018-02-26 16:01
Duplicate of #882.

**Closed by WrinklyNinja** 2018-02-26 16:01 UTC
