### ISSUE TITLE
Error Whenever I Try Sort Load Order

### ISSUE THREAD

**Issue by Hemi177** [loot/loot#884] opened 2018-02-23 07:07 UTC
Every time I have loot sort my load order I run into an error message, this is what is says in the debug log.
[02:03:50.513223] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[02:03:55.949534] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[02:03:55.949534] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
I have no clue what it means, anyone have any idea?

**Comment by WrinklyNinja** [comment] 2018-02-23 07:56
Duplicate of #882.

**Closed by WrinklyNinja** 2018-02-23 07:56 UTC
