### ISSUE TITLE
Just downloaded the update and constantly getting error message.

### ISSUE THREAD

**Issue by xasam24** [loot/loot#1177] opened 2020-01-12 20:57 UTC
Here is the entire debug log from my most recent session:

[12:28:10.789044] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[12:29:02.959711] [error]: Exception while executing query: exists: The filename, directory name, or volume label syntax is incorrect.
: "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim Radioactive -.*\.esp"
[12:29:03.037934] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5761:9231)

When I go into Settings, the Skyrim path includes nothing about "Skyrim Radioactive," which is not a file that exists in the directory.

**Comment by Ortham** [comment] 2020-01-13 16:56
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by CptMcSplody** [comment] 2020-04-22 12:43
@xasam24 @Ortham Duplicate of #1181 #1199  #1200 

> > : "D:\Steam\steamapps\common\SkyrimVR\Data\Skyrim Radioactive -.*.esp"
> > : "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim Radioactive -.*.esp"
> 
> ```yaml
>       - 'Skyrim Radioactive -.*\.esp'
> ```
> 
> That metadata is only present in an older version v0.10 of the SSE/SVR masterlist.
> _v0.15_ is the current and supported branch.
> Make sure `AppData\Local\LOOT\settings.toml` has the right settings for branch.
> 
> ```
> [[games]]
> 	branch = "v0.15"
> 	folder = "Skyrim Special Edition"
> 	repo = "https://github.com/loot/skyrimse.git"
> 	type = "Skyrim Special Edition"
> 	name = "TES V: Skyrim Special Edition"
> [[games]]
> 	branch = "v0.15"
> 	folder = "Skyrim VR"
> 	repo = "https://github.com/loot/skyrimse.git"
> 	type = "Skyrim VR"
> 	name = "TES V: Skyrim VR"
> ```
> 
> If that's correct then try deleting the entire contents of `AppData\Local\LOOT`.
> Then run LOOT outside your mod manager and update the masterlist.

**Comment by CptMcSplody** [comment] 2020-05-10 07:47
Closing this as the solution provided has worked in the other cases.

**Closed by CptMcSplody** 2020-05-10 07:47 UTC
Labels: duplicate
