### ISSUE TITLE
LOOT cannot detect or update masterlist

### ISSUE THREAD

**Issue by lsr-7** [loot/loot#1161] opened 2019-10-18 17:57 UTC
So, LOOT was working fine yesterday, but when i ran the app this morning, the setting screen showed up, Although i found it weird, i hitted aplly and got an error message:

> Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

Checked the LOOTDebugLog, and got the following informations:

> [14:38:20.018310] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[14:38:21.203378] [warning]: No masterlist present at C:\Users\UsernameL\AppData\Local\LOOT\Skyrim\masterlist.yaml
[14:39:16.374534] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (df0029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
[14:39:16.378534] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5817)

Later i found out that, if i select "TES V Skyrim" in the game selection list and hit "Sort Load Order", LOOT does load my plugins and load order, but provides no information about my "Masterlist Revision" and "Masterlist Date".

Since i could not solve the issue, i tried to download and install LOOT's latest version, but it did not work. LOOTDebugLog returns the following:

> [14:11:29.441191] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[14:11:31.276295] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (500029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
[14:11:41.734894] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (1c0029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
[14:11:41.735894] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5817)

Possible solutions that i've already tried, but didn't solve the issue:

Installing Microsoft EasyFix from issue #882 
Delete "Skyrim" folder from Appdata>Local>LOOT  and let LOOT generate a new one (did it several times).
Uninstall and reinstall LOOT version 0.14.5 (did it several times).
Uninstall and reinstall LOOT version 0.14.6 (did it several times).

Appreciate any helpful replies.

**Comment by CptMcSplody** [comment] 2019-10-18 18:05
Duplicate of #1158

**Closed by CptMcSplody** 2019-10-18 18:05 UTC
