### ISSUE TITLE
Microsoft Easy Fix 51044 that enables TLS 1.1/1.2 support interferes with FF14 launcher

### ISSUE THREAD

**Issue by Crishendo** [loot/loot#906] opened 2018-03-03 05:17 UTC
I don't know if this is the best place for this, but I have even less of an idea about where else to go for a potential fix, so apologies in advance if this all a waste of your time, since it technically isn't an issue with LOOT itself, just the fix. 

Running windows 7, had the whole masterlist update issue, read through the stuff here, found the fix ([specifically this one](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in)) and installed it. LOOT works beautifully, but a day later I go to sign into Final Fantasy XIV and as soon as I log into the launcher it throws me an error ([Specifically this one](https://i.imgur.com/EIFMZg7.png)). I looked for a good day and a half for fixes to this, thinking the only change I made remotely recently was this for LOOT. Lo and behold after a system restore to the point the fix made itself, FF14 launches fine. After further testing of running both FF14 and LOOT, installing the fix, and checking both again, I confirmed this was the precise issue. I'm not entirely 100% sure how the FF14 launcher works, but I do know it utilizes Internet Explorer in some way, and the easy fix page mentions that it makes changes for TLS 1.1 and 1.2 for IE. 

So my question after all this is: **Is there a way to find what specific changes the Easy Fix makes?** I've tried making my own registry edits the page itself mentions (Specifically making 'DefaultSecureProtocols' at HKEY_LOCAL_MACHINE\...WINHTTP with a value of 800 and then A00 for 1.2 and 1.1/1.2) and this seems to change nothing, FF14 works fine, and LOOT doesn't. So I'm wondering if I could find the changes the fix makes so I can do it myself while avoiding the IE changes if possible.

Again, I'm sorry if this is the complete wrong place for this, but I just have no idea where to go for the answers I need.

**Comment by WrinklyNinja** [comment] 2018-03-03 08:48
Duplicate of #900, see there for the solution.

**Closed by WrinklyNinja** 2018-03-03 08:48 UTC
