### ISSUE TITLE
Loot crashes on startup

### ISSUE THREAD

**Issue by Lanconis** [loot/loot#680] opened 2016-11-03 03:51 UTC
I have seen other people's issues and solutions but cannot correct mine with your advice. As soon as I launch LOOT it crashes (tried administrator etc.) and there is no appdata/local/LOOT file to delete. Windows 7 - Fallout 4 mods. I have put the crash log below for you. Can you offer any advice?

Folder contents:
![image](https://cloud.githubusercontent.com/assets/23228350/19955368/aff531b4-a1e5-11e6-8d99-097bc2998bba.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	LOOT.exe
  Application Version:	0.9.2.0
  Application Timestamp:	57a19bfa
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23543
  Fault Module Timestamp:	57d2f8a2
  Exception Code:	c0000005
  Exception Offset:	0004e6df
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	5129
  Additional Information 1:	a877
  Additional Information 2:	a87751724e225ffcdd7aaed29770c8da
  Additional Information 3:	a436
  Additional Information 4:	a436974db0058271cd8adc44b29b7079

**Comment by WrinklyNinja** [comment] 2016-11-03 06:34
Have you tried the latest dev snapshot build?

**Comment by Lanconis** [comment] 2016-11-03 07:34
Sorry am not familiar with where to find latest dev snapshot. Can you explain this a little to me? Thanks for the speedy response. :)

**Comment by WrinklyNinja** [comment] 2016-11-03 07:39
[Here](https://bintray.com/wrinklyninja/loot/LOOT/0.9.2-139-gc27e55c_dev), download the 7z archive.

**Comment by lespea** [comment] 2016-11-07 00:08
Same issue with 0.10 in Win10.  I get to the first run page and if I hit apply the exe crashes. I can hit cancel and it will say no supported games were detected and if I try to update the masterllist or even click the sort button it will crash.  Tested with both the installer and the dev build.  Both log files are short so i'll paste them inline.  Installed in a a "non-root path" and also tried running w/admin privs just in case to no avail.

CEFDebugLog.txt: `[1106/180350:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak`

LOOTDebugLog.txt

```
[18:02:21] [trace]: Updating existing games and adding new games.
[18:02:21] [trace]: Setting "TES IV: Oblivion" name to: TES IV: Oblivion
[18:02:21] [trace]: Setting "TES IV: Oblivion" master file to: Oblivion.esm
[18:02:21] [trace]: Setting "TES IV: Oblivion" repo URL to: https://github.com/loot/oblivion.git
[18:02:21] [trace]: Setting "TES IV: Oblivion" repo branch to: v0.10
[18:02:21] [trace]: Setting "TES IV: Oblivion" game path to: ""
[18:02:21] [trace]: Setting "TES IV: Oblivion" registry key to: Software\Bethesda Softworks\Oblivion\Installed Path
[18:02:21] [trace]: Setting "TES V: Skyrim" name to: TES V: Skyrim
[18:02:21] [trace]: Setting "TES V: Skyrim" master file to: Skyrim.esm
[18:02:21] [trace]: Setting "TES V: Skyrim" repo URL to: https://github.com/loot/skyrim.git
[18:02:21] [trace]: Setting "TES V: Skyrim" repo branch to: v0.10
[18:02:21] [trace]: Setting "TES V: Skyrim" game path to: ""
[18:02:21] [trace]: Setting "TES V: Skyrim" registry key to: Software\Bethesda Softworks\Skyrim\Installed Path
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" name to: TES V: Skyrim Special Edition
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" master file to: Skyrim.esm
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" repo URL to: https://github.com/loot/skyrimse.git
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" repo branch to: v0.10
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" game path to: "G:\Steam\steamapps\common\Skyrim Special Edition"
[18:02:21] [trace]: Setting "TES V: Skyrim Special Edition" registry key to: Software\Bethesda Softworks\Skyrim Special Edition\Installed Path
[18:02:21] [trace]: Setting "Fallout 3" name to: Fallout 3
[18:02:21] [trace]: Setting "Fallout 3" master file to: Fallout3.esm
[18:02:21] [trace]: Setting "Fallout 3" repo URL to: https://github.com/loot/fallout3.git
[18:02:21] [trace]: Setting "Fallout 3" repo branch to: v0.10
[18:02:21] [trace]: Setting "Fallout 3" game path to: ""
[18:02:21] [trace]: Setting "Fallout 3" registry key to: Software\Bethesda Softworks\Fallout3\Installed Path
[18:02:21] [trace]: Setting "Fallout: New Vegas" name to: Fallout: New Vegas
[18:02:21] [trace]: Setting "Fallout: New Vegas" master file to: FalloutNV.esm
[18:02:21] [trace]: Setting "Fallout: New Vegas" repo URL to: https://github.com/loot/falloutnv.git
[18:02:21] [trace]: Setting "Fallout: New Vegas" repo branch to: v0.10
[18:02:21] [trace]: Setting "Fallout: New Vegas" game path to: ""
[18:02:21] [trace]: Setting "Fallout: New Vegas" registry key to: Software\Bethesda Softworks\FalloutNV\Installed Path
[18:02:21] [trace]: Setting "Fallout 4" name to: Fallout 4
[18:02:21] [trace]: Setting "Fallout 4" master file to: Fallout4.esm
[18:02:21] [trace]: Setting "Fallout 4" repo URL to: https://github.com/loot/fallout4.git
[18:02:21] [trace]: Setting "Fallout 4" repo branch to: v0.10
[18:02:21] [trace]: Setting "Fallout 4" game path to: ""
[18:02:21] [trace]: Setting "Fallout 4" registry key to: Software\Bethesda Softworks\Fallout4\Installed Path
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" name to: Nehrim - At Fate's Edge
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" master file to: Nehrim.esm
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" repo URL to: https://github.com/loot/oblivion.git
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" repo branch to: v0.10
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" game path to: ""
[18:02:21] [trace]: Setting "Nehrim - At Fate's Edge" registry key to: Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1\InstallLocation
[18:02:21] [trace]: Removing deleted games.

```

**Comment by equeim** [comment] 2016-11-09 22:47
I have the same issue.

**Comment by Lanconis** [comment] 2016-11-09 22:51
Thanks Ninja that new dev shot sorted out the issue. For anyone who is experiencing the same thing i suggest you read the comments from WrinklyNinja.

**Comment by lespea** [comment] 2016-11-10 03:45
The newest dev release did not solve fix it for me (also tried the latest 10 dev release)

**Comment by equeim** [comment] 2016-11-10 10:22
> The linked dev release did not solve fix it for me (also tried the latest 10 dev release)

Same here.

**Comment by WrinklyNinja** [comment] 2016-11-10 10:45
Closing this as @Lanconis has verified the issue is fixed.

@lespea Your issue is not a crash on startup, please file a new issue for it.

@equeim Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). You have given me absolutely no information to go on, not even whether it's a crash on startup or @lespea's crash on applying a sort. If it's a crash on startup, please post your logs in this issue, if they're a different crash please file a new issue.

**Closed by WrinklyNinja** 2016-11-10 10:45 UTC
