### ISSUE TITLE
LOOT Crash 

### ISSUE THREAD

**Issue by emilie-glorieux** [loot/loot#707] opened 2016-11-23 15:46 UTC
Hi, I'm sorry to bother you but, I made nothing else than installing mods for Skyrim.
I wanted to launch LOOT but It's not launching and say this.
I tried to re-install and searched about the Local appdata folder, but I didn't find it.
![loot](https://cloud.githubusercontent.com/assets/18654334/20568230/178358ae-b19c-11e6-968b-e17dcd347085.JPG)

**Comment by WrinklyNinja** [comment] 2016-11-23 17:09
Which version of LOOT are you using?

**Comment by emilie-glorieux** [comment] 2016-11-23 17:46
I have the lastest version of LOOT ans Win 10

**Comment by WrinklyNinja** [comment] 2016-11-23 18:02
> I have the lastest version of LOOT ans Win 10

It would be good if you gave an actual version number: your idea of "latest version" may not match mine, and if this needs to be revisited at some point in the future it saves me having to work out what exact version that would be.

**Comment by emilie-glorieux** [comment] 2016-11-23 18:06
Yeah sorry, I took the v0.10.1 I suppose.
I can't launch it so I can't check.

**Comment by WrinklyNinja** [comment] 2016-11-23 18:06
Try with [this snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.10.1-12-g1806e62_dev).

**Comment by emilie-glorieux** [comment] 2016-11-23 18:08
Euh, sorry but how do I download it?

**Comment by WrinklyNinja** [comment] 2016-11-23 18:08
https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-12-g1806e62_dev.7z

**Comment by emilie-glorieux** [comment] 2016-11-23 18:09
I have the same error.

**Comment by WrinklyNinja** [comment] 2016-11-23 18:10
Do any of the previous [releases](https://github.com/loot/loot/releases) work?

**Comment by emilie-glorieux** [comment] 2016-11-23 18:13
The 0.9.2 seems to be working.

**Comment by WrinklyNinja** [comment] 2016-11-23 18:57
Hmm, a few other people have had trouble with the switch from v0.9.2 to v0.10, I'll try downgrading CEF to the version used in 0.9.2 and link to the build once it's up.

**Comment by WrinklyNinja** [comment] 2016-11-23 19:23
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-14-g7114789_downgrade-cef.7z).

**Comment by emilie-glorieux** [comment] 2016-11-24 07:18
I have the same error than before.

**Comment by WrinklyNinja** [comment] 2016-11-24 08:09
Do you have the [MSVC 2015 x86 redistributable](http://download.microsoft.com/download/9/a/2/9a2a7e36-a8af-46c0-8a78-a5eb111eefe2/vc_redist.x86.exe) installed?

**Comment by emilie-glorieux** [comment] 2016-11-24 10:26
Yes

**Comment by WrinklyNinja** [comment] 2016-11-24 17:52
I don't know why LOOT broke for you between 0.9.2 and 0.10.0 then, because the only two possibly relevant changes I can think of were the CEF update (downgrading didn't work) and the introduction of the MSVC redist dependency (which you've got).

**Comment by WrinklyNinja** [comment] 2016-12-04 12:15
Can you try installing [this MSVC redist](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe) and see if that fixes the issue?

**Comment by WrinklyNinja** [comment] 2017-01-11 17:51
The latest snapshot build may also fix this, as it includes an updated CEF.

**Comment by WrinklyNinja** [comment] 2017-06-05 16:32
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.

**Closed by WrinklyNinja** 2017-06-05 16:32 UTC
Labels: awaiting-feedback
