### ISSUE TITLE
Installer can't find MSVC redist.

### ISSUE THREAD

**Issue by wesleys92** [loot/loot#1560] opened 2021-07-24 13:33 UTC
Hello. When I go to install LOOT, I get a 404 Not Found error when downloading additional resources.

**Comment by sibir-ine** [comment] 2021-07-24 21:48
@wesleys92 I can't reproduce this with the v0.16.1 installer, are you installing an older version? Are you experiencing any connectivity issues? If you can't get it to work, you can install the [archive](https://github.com/loot/loot/releases/download/0.16.1/loot_0.16.1-0-g18e28e9_0.16.1.7z) & [MSVC redist.](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe) separately.

**Comment by dReAmWiELdErX** [comment] 2021-07-24 22:08
I am having this same issue with the latest installer.

**Comment by dReAmWiELdErX** [comment] 2021-07-24 22:10
Yeah, and the seemingly ancient installers are working either. This is such a waste of time.

**Comment by sibir-ine** [comment] 2021-07-24 22:11
@dReAmWiELdErX Please see my comment to wesleys92.

**Comment by Ortham** [comment] 2021-07-24 22:21
The redist link is 404'ing for me too... Looks like we'll need to update the download links.

**Comment by sibir-ine** [comment] 2021-07-24 22:23
It works fine for me 🤷

**Comment by Ortham** [comment] 2021-07-24 22:24
Maybe it's a temporary outage then 🤷

**Comment by unwishedjack** [comment] 2021-07-25 15:28
I also cannot install, having the exact same issue

**Comment by Ortham** [comment] 2021-07-25 18:00
To add to the confusion, if I run the installer in a Windows Sandbox instance, the MSVC redist download works, but if I try opening the URL the installer uses in Edge in the same Sandbox instance, I get a 404...

**Comment by Ortham** [comment] 2021-07-26 21:57
I've tried to introduce a couple of mitigations for this in commit 523d9a94c2198c82508caa168e335729206502af in the `msvc-redist` branch:

* We now link to the latest MSVC 2015/2017/2019 redistributable using the same URL as Microsoft provide instead of linking to a specific older version of the 2017 redist, so that the link is hopefully more likely to stay working (though the current 404s seem to be happening sporadically across all redist versions). It also means that if any future bump in the redist requirement is less likely to mean users need to install a newer version (as they version they have may already be new enough).
* The installer now checks if the installed redist version is older than the required version, rather than checking if the required version is installed, as newer versions are backwards-compatible but the installer would treat having a newer version installed the same as not having the redist installed at all. This stops the installer trying to download and install the redist unnecessarily in many cases, avoiding download issues entirely.

The version of the redist that the installer checks for hasn't changed - it's probably a more recent version than is strictly required, but AFAIK Microsoft don't publish any information about redist version changes or how to tell what redist version a given executable needs (beyond the major version). Because we use a third-party system (GitHub Actions) to build our executables, we don't control the compiler version used (beyond the major version, i.e. MSVS 2017 vs 2019), so the required redist version could (I think) potentially change without warning...

**Comment by Ortham** [comment] 2021-12-21 18:11
Closing this now that the changes are included in v0.17.0.

**Closed by Ortham** 2021-12-21 18:11 UTC
