### ISSUE TITLE
Add ability to override masterlist metadata

### ISSUE THREAD

**Issue by potens1** [loot/loot#1149] opened 2019-09-29 21:09 UTC
Hello,

First, thank you for your hard work !

I understand perfectly the reason why you did not permit that, to force users to report masterlist problems/enhancements/entries. 

I have right now a entry that was reported in masterlist and rejected, it does not matter why and what but this is an example. Author of the mod that has two esp say esp-A before esp-B, masterlist says the other way, a user reported it, the issue was rejected because "it does not matter (more or less)".
So the situation is, if I want to respect the author instructions, I've added my own "load after" rule but loot stop sorting since the "masterlist requirement" can not be discarded and now the result is a cyclic interaction.

For the records, the issue in masterlist https://github.com/loot/skyrimse/issues/268, please understand I don't complain about the decision of not applying the modification, the case is an example, but what can users do when this kind of case happens (reported to masterlist, user is aware of what should be done but can not apply)

**Comment by Ortham** [comment] 2019-09-30 16:41
I think this is a bit of an edge case: on the one hand you don't feel strongly enough about the change to contest it being rejected, but on the other you still feel strongly enough to seek to contradict the masterlist for your own use.

Forcing feedback is the main reason why I chose to disallow overriding the masterlist for most metadata, but another reason is that if you were able to override a masterlist entry, you make the change once but it has the effect of then hiding future changes in that entry from you. You end up maintaining an "alternate history" version of the masterlist, but without any insight into what the "official history" is, so it's not obvious to you what you're missing out on. It might also introduce breakage where for example plugins A and B are changed together in the masterlist to sort differently, but because you've overridden A's metadata, you don't get that change, and now you only have B's part of the masterlist change, which might cause incorrect sorting.

(These are real problems for groups, which are the only metadata that userlists *can* override. Users have encountered such breakage when they've overridden groups and the masterlist has changed "beneath" them.)

With a (mostly) additive userlist, you don't need to worry much about what's changing in the masterlist. As soon as you start to override the masterlist, you take on additional risk of mangling things, and I don't want to make that easy for users.

Personally, I think you're best off maintaining a personal fork of the masterlist with your change. It's more effort than if LOOT were to allow you to override the masterlist in your userlist, and requires a little more technical know-how, but at least it exposes what's actually going on to you.

**Comment by CptMcSplody** [comment] 2019-11-24 17:23
> For the records, the issue in masterlist [loot/skyrimse#268](https://github.com/loot/skyrimse/issues/268), please understand I don't complain about the decision of not applying the modification, the case is an example, but what can users do when this kind of case happens (reported to masterlist, user is aware of what should be done but can not apply)

For Immersive Armors even the author makes the point that the order doesn't matter.

> Note : LOOT and MO2 may put ArmorCompilation.esp first - if the game runs leave the load order as is. 

![image](https://user-images.githubusercontent.com/1944639/69498261-a199e480-0edd-11ea-9bfe-60e3de307ead.png)

The important part is that both `Hothtrooper44_ArmorCompilation.esp` and `Hothtrooper44_Armor_Ecksstra.esp` are active to load Hothtrooper44_ArmorCompilation.bsa and `Hothtrooper44_Armor_Ecksstra.bsa`.

**Comment by Delgathar** [comment] 2020-06-26 23:30
I want to say that I'm in total agreement with the op. The more I roll up my sleeves and dig into loot, xEdit, and Mator Smash, the more I run into problems created by the master list really being an expression of some unknown poster's preferences than a hard rule that should be imposed on the user unless they go to great lengths to correct it.  I had one a couple of days ago and wrote out my own version of this issue.  Then decided no run with it a little longer, and I got another circular error today that I can't fix

The basic premise of LO is "Where these two mods conflict, I want mod X to win over mod Y."  A certain percentage of errors are just ignored because LO doesn't solve problems, it just hides them.  They could be fixed by a manual compatibility patch, but this can take hours to make right, and the main strength of Loot and MS is fixing load orders that are constantly changing. Mator Smash gives the ability to reduce the number of broken entries, but it can require a different LO because MS is better at handling some entries than others.  MS can't merge everything.  What can't be merged a rule can be made, however when two mods share the same rule, the difference comes back to Load order, but now the user is trying to solve a difference compatibility problem that the one in the master list.

Honestly, when Loot first came out.  There was no real master list.  All it did was look at the ESP masters and then order by group.  Everyone was told that a Master list wasn't needed anymore.  Which was fine.  Then there was a change of heart and we have this ever-growing master list that is becoming less and less helpful and more of a hindrance with every iteration.  I like being told that my esp needs to be cleaned, or having master list _recommendations_ re-order my list by default, or have a reference that there is an incompatibility with another mod or a general fix is recommended.  But the master list should only be a recommendation, not an unalterable rule imposed on the user. I'd rather go back to no master list if that is the way things are going to be.

**Comment by CptMcSplody** [comment] 2020-06-27 03:34
> the more I run into problems created by the master list really being an expression of some unknown poster's preferences

There are a lot of different things influencing the masterlist. One of the main things is time, it would take too much time for contributors to order every single mod perfectly and account for every scenario. There are more users than contributors, so user feedback is essential for finding issues.

For Skyrim SE most of the rules come directly from the mod authors, the Skyrim LE masterlist, user feedback and/or as a result of testing. Some rules are for consistency, you can't have A after C if C needs to be after B and B has to be after A. Other rules in place are to prevent sorting errors where the plugins have been placed in a group.

>  Then decided no run with it a little longer, and I got another circular error today that I can't fix.

If users don't report these issues then we'll assume there isn't a problem.

**Comment by Delgathar** [comment] 2020-06-29 17:39
> There are a lot of different things influencing the masterlist. One of the main things is time, it would take too much time for contributors to order every single mod perfectly and account for every scenario. There are more users than contributors, so user feedback is essential for finding issues.

Yes.  This is exactly why Masterlist orders should only be suggestions, not arbitrarily enforced on the user.  They aren't the kind of issues that I feel the need to enforce on other users so I wouldn't report them, I'd just make a manual rule.  Most mods don't only affect one thing.  They affect many different things, sometimes stuff that is out of scope, or some in-scope changes that another mod does better.  Also, I might simply disagree with the philosophy behind some placements in general, such as placing lighting mods (ELFX) high where the primary changes are lost to other mods that only include the record as a reference for another record.  I changed this once and had a hard time figuring out what the problem was because the circular error popup didn't even reference ELFX.

> Some rules are for consistency, you can't have A after C if C needs to be after B and B has to be after A. Other rules in place are to prevent sorting errors where the plugins have been placed in a group.

Yes.  But the problem here is "NEED" does it need to go in x order because of the mod's defined masters.  Or does it "NEED" to be in x order because the mod author wants her edits to win, but maybe I the user don't want those edits to win.  For my usage, I might want A after C and conclude that B doesn't really need to come after A, nor C after B.  Or a new mod D might come out that makes mod B obsolete, but works better when mod A follows C and mod B is removed.

> If users don't report these issues then we'll assume there isn't a problem.

Most of my issues are specific to my usage.  They aren't the kind of issues that I feel the need to enforce on other users.  Most mods don't only affect one thing.  They affect many different things, and which should override is really a matter of individual preference.  Also, some of these orders are based on the state of Mator Smash.  If the problems I've reported to MS get fixed then the order that I've set will need to be changed, or might not matter.

Reporting isn't really the issue, it is getting pushback on my issues, and seeing other people get pushback on their issues.  But it would be nice if when I changed a meta-rule, there were an option to report it within the client.  That might encourage more people to report.  Generally, I'd assume that if a user considered themselves advanced enough to sort the list themselves, then they are advanced enough to deal with the order changing as their mod list evolves. If you really feel that a user should have some way of knowing that a mod's needs have changed, a periodic check of user conflicts with the master list and a notification that X mods with user defined rules have had changes to their ML data.  If the problem is hiding changes from the user, then don't hide them.

Thank you.

**Comment by ev3nst** [comment] 2021-01-02 11:51
>  Then there was a change of heart and we have this ever-growing master list that is becoming less and less helpful and more of a hindrance with every iteration. I like being told that my esp needs to be cleaned, or having master list recommendations re-order my list by default, or have a reference that there is an incompatibility with another mod or a general fix is recommended. But the master list should only be a recommendation, not an unalterable rule imposed on the user. I'd rather go back to no master list if that is the way things are going to be.

This is the exact problem im having right now with hard coded load after rules on Cutting Room Floor.esp.. such a big record file is enforced to load after almost every kind of mod basically forcing me to make this mod late loader which is unrealistic and makes no sense at all. I like how loot allows making your own groups and i had no problem.

Just because of these forced rules im thinking of dropping the mod entirely because its more logical for me to drop 1 mod in order to save my hours of work on those customized group orders, manually created patches and so on. This is the only mod i have found that causes this much problem with these rules.

**Comment by pStyl3** [comment] 2021-01-02 13:18
These are the plugins that `Cutting Room Floor.esp` ([Modpage](https://www.nexusmods.com/skyrimspecialedition/mods/276)) is set to load after via SSE's masterlist:
```
3DNPC.esp
Audio Overhaul Skyrim.esp
Immersive Sounds - Compendium.esp
Enhanced Landscapes.esp
EnhancedLightsandFX.esp
Immersive Encounters.esp
Tamriel Reloaded HD SE.esp
TouringCarriages.esp
Undeath.esp
UnlimitedBookshelves.esp
WhiterunHoldForest.esp
```
11 plugins. `Cutting Room Floor.esp` also has no Group assigned to it, so it falls into the `default` Group, where most plugins are. In a test sort I just did, with a load order consisting out of 169 plugins, it was placed in spot 46. As such, I don't think saying that this plugin loads `after almost every kind of mod` is a correct assessment.

Regarding the topic of this issue, I don't really see the need to expand the users ability to override what is written within the masterlist, past what is already possible through the Groups Editor, for the reasons Ortham has given.

**Comment by Ortham** [comment] 2022-02-04 23:17
I'm going to close this as `wontfix` as while the concerns raised are valid, I still think that adding the ability to override the masterlist is not an appropriate solution. If as a user you object to something in the masterlist (be it related to load order or some other metadata) you're free to provide that feedback to the maintainer(s), who may make changes in response to that feedback. If that's not enough, you have a few options:

1. You use a custom masterlist that works for you. You lose the benefits of any improvements to the official masterlist (unless you keep it in sync), but if you have a fairly static set of mods then that's probably fine (since by definition your custom masterlist's load order gives you one you're happy with, and any other metadata would be informative but probably not crucial to an existing mod set).
2. If it's the load order changes you object to, but you still want to benefit from the other metadata the masterlist provides, just don't use LOOT to set your load order, or run its sorting once to get everything roughly in place and then tweak your load order manually after that.

**Closed by Ortham** 2022-02-04 23:17 UTC
Labels: enhancement
