### ISSUE TITLE
Started Modding Fallout NV, LOOT Stopped Working

### ISSUE THREAD

**Issue by wyatt0781** [loot/loot#868] opened 2018-01-27 17:48 UTC
https://imgur.com/a/e8ZEC

This seems to be the main issue, but now nothing in LOOT is working, my Skyrim sorting which wass working fine yesterday, and all I have done since then is download mods for Fallout NV

https://imgur.com/a/gqBDH

There are also a large number of these, this happened after I disabled some things COMODO was blocking, before it was only the image above. I have got no clue what it is doing or how to fix it.

**Comment by WrinklyNinja** [comment] 2018-01-27 21:26
This seems like it's probably the same issue as #858. Could you link me to where you got one or more of the plugin's you're seeing the "error code 3" error for? Error code 3 is `ESP_ERROR_STRING_CONTAINS_NUL`, which could be a problem with the plugin or my parsing code.

**Comment by wyatt0781** [comment] 2018-01-28 00:27
https://www.nexusmods.com/newvegas/mods/55744/

This is the first one that I saw, want me to try and compile the rest of them?

In the meantime, does that mean that there is nothing I can do? I tried to use FOMM's BOSS sorter but it found no masterlist

**Comment by wyatt0781** [comment] 2018-01-28 00:31
Update: This is all it is telling me now

https://imgur.com/a/KQfRt

Ive only been modding seriously for a bout a month, Im at a loss as to how to fix any of this

**Comment by wyatt0781** [comment] 2018-01-28 01:02
I read the other post, and it seems New Vegas Bounties III is the problem, but It will not let me delete it. It goes through half the process through NMM and stops (while saying it hasn't) it is not in the mods folder I have for NMM. 

https://imgur.com/a/Tmnb9

It shows one and two, this might be because I halted the uninstallation, but I do not know.

**Comment by wyatt0781** [comment] 2018-01-28 01:03
LOOT is working now! I managed to uninstall NV Bounties III

**Comment by WrinklyNinja** [comment] 2018-01-28 19:33
Well, `FreesideOpen - NewVegasBountiesIII.esp` has a master that contains an extra trailing null byte, i.e. the escaped string after removing the null terminator is `FreesideOpen.esm\0`. I count this as corruption, but it may work in game because the game could just see the first null and ignore how long the string is supposed to be (which generally will be the case in C++ code).

I could update esplugin to behave the same way, but it might be better to flag up such corruption in case it signals more significant issues.

**Comment by WrinklyNinja** [comment] 2018-01-28 20:08
Closing this as a duplicate of #858.

**Closed by WrinklyNinja** 2018-01-28 20:08 UTC

**Comment by WrinklyNinja** [comment] 2018-01-28 20:10
...and I edited the wrong issue's title...
