### ISSUE TITLE
libloadorder failed to set the load order

### ISSUE THREAD

**Issue by DankRafft** [loot/loot#958] opened 2018-06-02 17:41 UTC
With the newest release of LOOT I get the following error:

`[19:37:56.292411] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[19:37:56.292491] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[19:37:56.293018] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\Daniel\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)`

I haven't had this issue before the update. I run LOOT through MO2 in case it matters.

**Comment by WrinklyNinja** [comment] 2018-06-02 17:42
Please upload your full debug log.

**Comment by DankRafft** [comment] 2018-06-02 17:44
`[19:43:55.052679] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[19:43:55.070430] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[19:44:03.763921] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[19:44:03.764169] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[19:44:03.764738] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\Daniel\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)`

That's all it contains.

**Comment by WrinklyNinja** [comment] 2018-06-02 17:49
Make sure you've got debug logging enabled in your settings.

**Comment by DankRafft** [comment] 2018-06-02 17:57
https://1drv.ms/t/s!AsPOI2bGwtK0g18qPFNtV9Lyfp5A

**Comment by WrinklyNinja** [comment] 2018-06-02 18:04
Yep, duplicate of #956, see my last comment there.

**Closed by WrinklyNinja** 2018-06-02 18:04 UTC
