### ISSUE TITLE
Character encoding issue in language settings

### ISSUE THREAD

**Issue by 3ventic** [loot/loot#1759] opened 2022-05-24 12:34 UTC
![image](https://user-images.githubusercontent.com/3998628/170035372-7afc3568-a6d5-499e-9fa8-36db00025274.png)

Character encoding mismatch somewhere in printing the language names in the settings dropdown in 0.18.3.

**Comment by sibir-ine** [comment] 2022-05-24 12:47
I've only ever observed this after updating, & I don't recall being able to reproduce it consistently.

**Comment by Ortham** [comment] 2022-05-24 14:02
@3ventic Thanks, I can replicate with that. Turns out it's nothing to do with LOOT, it's the installer that mangles the settings file when it tries to set LOOT's language to the same language as you selected for the installer.

**Comment by sibir-ine** [comment] 2022-05-25 05:01
I can confirm that it's been fixed.

**Comment by Ortham** [comment] 2022-05-25 05:51
Fixed in 652ea58aa67e14ef1ea9a6d0a4bb9335f8be4521.

**Closed by Ortham** 2022-05-25 05:51 UTC
Labels: bug
