### ISSUE TITLE
error code 12

### ISSUE THREAD

**Issue by mrchaos500** [loot/loot#484] opened 2015-09-18 20:57 UTC
every time i try to sort the plugins i get Error code: 12; Failed to update the masterlist. Details: An error occurred while trying to clone the remote masterlist repository.
any solutions? i have the current .80 build. running windows vista 32bit. LOOT has admin privileges. i really hope you can help since BOSS is no longer a valid organizer

**Comment by WrinklyNinja** [comment] 2015-09-18 21:17
Are you on Windows Vista?

**Comment by mrchaos500** [comment] 2015-09-19 22:45
yes

**Comment by WrinklyNinja** [comment] 2015-09-20 09:21
Then this is a duplicate of #477. The latest snapshot build contains a fix.

**Closed by WrinklyNinja** 2015-09-20 09:21 UTC
Labels: bug, duplicate
