### ISSUE TITLE
Extend duration of status bar messages

### ISSUE THREAD

**Issue by Glanzer-modder** [loot/loot#1729] opened 2022-03-20 01:33 UTC
I already reported this issue (#1724) but that is now closed. I verified this is still an issue in 0.18.1. I definitely get no message in the bottom left of my screen when LOOT makes no changes to the load order.

**Comment by Glanzer-modder** [comment] 2022-03-20 01:39
AHA I found what is going on. The message DOES appear, but is only there for about 3 seconds and then disappears. So it's not a bug per se. I would ask that the message be there permanently until replaced by another message. I usually just walk away from my PC or put LOOT in the background and work on other tasks when it's sorting. Just a suggestion.

**Comment by Ortham** [comment] 2022-03-23 18:46
The current message lifetime is 5 seconds, I think that's the same as it was in earlier versions of LOOT: the difference is that it's much less noticeable than the pop-up box that was displayed before.

I think part of the problem is that while most notification texts are displayed (roughly) immediately after triggering the action they're notifying of (e.g. copying/clearing metadata is pretty much instantaneous), masterlist update and sorting take more time (though masterlist update is quite fast). I guess this allows the user's attention to wander and means it's more likely they'll miss the notification.

I think for sorting the obvious solution would be to display the notification in a dialog that the user has to interact with to dismiss, but that doesn't work so well for masterlist update, as that can happen in the middle of a combined update-and-sort process.

| | Update didn't happen | Masterlist and/or prelude unchanged | Masterlist and/or prelude updated |
|--|--|--|--|
| **Sorting didn't happen** | No communication necessary | Notify of no change after update completes | Inform of change after update completes? The general info card already updates, so maybe that's not necessary.
| **Sorting made no changes** | Notify of no change after sorting completes | ?  | ?
| **Sorting made changes** | No need to inform? The toolbar buttons are replaced. | ? | ?

**Comment by Glanzer-modder** [comment] 2022-03-23 21:28
Yeah I'd prefer a pop-up box I'd have to interact with when no sorting changes are made. All the other notifications are fine. And if I'm the only one reporting this, it's probably not a big issue anyway. Thanks!

**Comment by Ortham** [comment] 2022-03-29 18:10
I've added the dialog in the `sorting-notification-dialog` branch. It doesn't include any info about any masterlist updating done, because I don't think that's important enough to repeat (since the new ID and date are already given in the general info card).

**Comment by Glanzer-modder** [comment] 2022-03-29 19:30
Has the change been committed? I downloaded the latest masterlist  but didn't see any change in the messages after sorting with no changes.

**Comment by Glanzer-modder** [comment] 2022-03-29 19:59
Oh duh, it's not a masterlist change, it's a LOOT app change. Ok, I'll wait until the new version is released! :)

**Comment by Ortham** [comment] 2022-03-29 20:01
You can download a snapshot build to try from [here](https://loot.jfrog.io/ui/native/loot/sorting-notification-dialog/).

**Comment by Glanzer-modder** [comment] 2022-03-29 20:22
Yes, the new version gives the informative popup. Much better IMHO. Thank you!

**Comment by pStyl3** [comment] 2022-03-29 20:33
The new dialog plays a Windows error sound when opened, that should ideally be silenced.

That being said, can this change be made toggleable, so that I can choose if I like the old way or the new one via dialog? I can see why the dialog can be handy if the sorting takes a lot of time, however, I for one don't expect my sorting to take very long since the number of plugins I use is in the range of 100-200. As such I don't necessarily need to be informed through a to be opened dialog if sorting makes no changes.

**Comment by pStyl3** [comment] 2022-03-29 20:43
![grafik](https://user-images.githubusercontent.com/10406657/160703134-3ff324a0-c036-46c8-8b34-e1f45fea5d5a.png)

Another approach could be to display the X button next to "Sorting made no changes" in the bottom left corner. The message (and the button) could be displayed until something else replaces the Smnc message or the X button is pressed.

Though I don't know how feasible that is.

**Comment by Ortham** [comment] 2022-04-20 20:39
> The new dialog plays a Windows error sound when opened, that should ideally be silenced.

The sound that plays for `QMessageBox::critical()` (which displays the X in a red circle icon) is "Windows Foreground" and the sound that plays for `QMessageBox::information()` (which displays the i in a blue circle icon) is "Windows Background". The new dialog uses the latter. (As an aside, there are a lot of sounds in the Sound Control Panel window that I've never heard...)

Playing the sound seems to be a Windows accessibility feature, and so while it can be disabled I'm inclined not to.

> That being said, can this change be made toggleable, so that I can choose if I like the old way or the new one via dialog?

Yes, that could be a setting. I'd default it to displaying the dialog.

> Another approach could be to display the X button next to "Sorting made no changes" in the bottom left corner. The message (and the button) could be displayed until something else replaces the Smnc message or the X button is pressed.

Unfortunately while that can be done, I think the fact the message can be replaced means the user happening to mouse over something else could replace the message so that it's not seen.

**Comment by Ortham** [comment] 2022-04-22 17:09
@pStyl3 The `sorting-notification-dialog` branch now includes a setting to toggle the use of a dialog, can you try it out and see if you've got any more suggestions for improvement?

**Comment by pStyl3** [comment] 2022-04-22 17:39
The new dialog window seems to work as intended.

**Comment by Ortham** [comment] 2022-04-22 18:04
Closing this as it's done as of 0cc5edc070580169f7301696558390b04776b6fe.

**Closed by Ortham** 2022-04-22 18:04 UTC
Labels: enhancement, ui
