### ISSUE TITLE
Application won't start.

### ISSUE THREAD

**Issue by MarCoelho** [loot/loot#639] opened 2016-09-05 03:26 UTC
LOOT won't start, it doesn't even get far enough to generate a log, I tried debugging it on VS, to figure out what was the issue, but the only thing i got was the following error:
Unhandled exception at 0x01396D88 in LOOT.exe: Fatal program exit requested.

**Comment by MarCoelho** [comment] 2016-09-05 09:56
After reading a few closed issues, tried spamming LOOT.exe like crazy, eventually a blank LOOT screen opened, and a log was generated, spamming again with the --single-process argument eventually worked, still don't know why i need to spam it for a working process to eventually open, help would be appreciated.

**Comment by WrinklyNinja** [comment] 2016-09-07 16:41
Closing this as a duplicate of #575: try the fixed build linked to in that issue.

**Closed by WrinklyNinja** 2016-09-07 16:41 UTC
