### ISSUE TITLE
Active plugin icon

### ISSUE THREAD

**Issue by bitdman** [loot/loot#564] opened 2016-04-17 01:18 UTC
Fallout4.esm has the only active plugin showing.......All mod boxes are checked and green.....I'm not sure if the other mods are active or not

**Comment by pStyl3** [comment] 2016-04-17 09:30
Which exact version of LOOT do you use? And do you use Fallout 4 v1.4 (normal) or do you participate in the Survival Mode Beta?

**Comment by bitdman** [comment] 2016-04-17 18:19
Thank you for the quick reply.....I'm using the latest 8.1 version and I don't have the beta version of fallout 4... Hope this is enough info.

**Comment by WrinklyNinja** [comment] 2016-04-17 18:27
v0.8.1 doesn't support Fallout 4, you need to use a snapshot build for that.

**Comment by bitdman** [comment] 2016-04-18 18:28
I thought I had the latest snapshot buld.   what is the latest?

**Comment by WrinklyNinja** [comment] 2016-04-18 19:34
It was `0.8.1-301-g6cafd65`, but I've just [uploaded](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) a new build, `0.8.1-311-g2ab555c`.

**Comment by bitdman** [comment] 2016-04-18 19:38
Ok I'm a couple snapshots behind. I'll install the new one and see what happens....Thancks

**Comment by Aeradom** [comment] 2016-04-20 03:46
I too am having this issue, and am using NMM though. I also have an issue though that even before that, I was having trouble with the loot not wanting to sort (it was mostly in alphabetical order except for like the first 10 or so mods). I did get the mods to finally show up on there, but it was only after fiddling with the .txt files. But now it's not working. I'll be sending you the stuff, but just wanted to let you know I too have this issue.

**Comment by WrinklyNinja** [comment] 2016-04-20 08:09
> Also I'm using Wrye Flash to install the mods. Might that be a reason for only the FO4.esm showing as activated?

It's probably the case that Wrye Flash is just not activating them. Also, there is no `FO4.esm`: I know what you mean in this instance, but if you're trying to describe issues, accuracy and specificity are very important.

> I too am having this issue, and am using NMM though.

Are the plugins that you're expecting to show as active listed in your `plugins.txt`? If not, then they're not active, and LOOT is working correctly.

> I also have an issue though that even before that, I was having trouble with the loot not wanting to sort (it was mostly in alphabetical order except for like the first 10 or so mods).

As I commented in reply to loot/fallout4#13, that doesn't sound like an issue.

**Comment by bitdman** [comment] 2016-04-20 19:22
I apologize for the inaccuracy. Yes it is the fallout4.esm that is showing as 'active'....All other .esm and .esp files including the DLC's do not have the green check mark, but do show up in the plugins text.

**Comment by WrinklyNinja** [comment] 2016-04-20 19:49
> All other .esm and .esp files including the DLC's do not have the green check mark, but do show up in the plugins text.
> 
> To be clear....I'm not asking if the mods are being sorted. But are they getting activated? If they show in the 'plugins.txt' does that mean I can be certain that they are active?

LOOT doesn't active or deactivate plugins, but if they're in your plugins.txt, then they're active, and LOOT should be showing a green check mark for them, so it sounds like something is going wrong... Can you supply your LOOTDebugLog.txt?

**Comment by bitdman** [comment] 2016-04-21 00:03
I guess you don't need that log anymore? Looks like you already fixed it.   Thank you so much!

**Comment by WrinklyNinja** [comment] 2016-04-21 05:24
I didn't do anything, but OK...

**Comment by bitdman** [comment] 2016-04-21 17:25
Strange!!!! The only thing I did was let Steam update the beta.....I undid the update choice to no betas and now it's back to only "fallout4.esm" having a check mark.....but I think you have more important things to work on, so wait on this issue, It might fix it's self

**Comment by bitdman** [comment] 2016-04-22 17:29
[LOOTDebugLog(A).txt](https://github.com/loot/loot/files/232286/LOOTDebugLog.A.txt)
[LOOTDebugLog(B).txt](https://github.com/loot/loot/files/232288/LOOTDebugLog.B.txt)

Here are 2 Logs I think that log 'B' is the one that had all mods checked with green check, then 'A' is back to only fallout4.esm checked. Maybe these will tell you something....Cheers!

**Comment by bitdman** [comment] 2016-04-22 23:47
[LOOTDebugLog.txt](https://github.com/loot/loot/files/232691/LOOTDebugLog.txt)

This log is from loot I am using now...all check marks are there......I'll leave you alone now....you can close this comment if you want

**Comment by WrinklyNinja** [comment] 2016-04-23 06:56
Hmm, log A shows that `DLCworkshop01.esm`, `DLCRobot.esm` and `Fallout4.esm` are the only plugins in your Data folder when LOOT scans it, whereas the other two logs show many more plugins are installed when LOOT scans your Data folder. When you ran LOOT for log A, did any other plugins even show up?

**Comment by Freso** [comment] 2016-04-23 10:54
Are you running LOOT through Mod Organiser? (I get LOOT not seeing MO's "virtual folder" about half the time I start up LOOT via MO2.)

**Comment by bitdman** [comment] 2016-04-23 20:50
I haven't had any success running LOOT thru MO2. I'm using Wrye 307.09  by its self no MO2 This log has the three DLC's + 6 mods, nothing but fallout 4 has a green check. Wrey Flash boxes are all checked and green. When nothing in the load order gets changed by LOOT is it normal for the 'apply' button not to show after running LOOT?



[LOOTDebugLog.txt](https://github.com/loot/loot/files/233142/LOOTDebugLog.txt)
.

**Comment by WrinklyNinja** [comment] 2016-04-24 07:39
@pStyl3 has found that my latest snapshot builds are unintentionally built with support for the Fallout 4 1.5 beta load order system, not the non-beta system as intended, so that'll be why they're not showing up. Mystery solved, I think.

**Comment by pStyl3** [comment] 2016-04-24 08:13
Which should mean, if @bitdman is using [snapshot 301](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AADUm2brDPVtdtAifjBovws6a/LOOT%20v0.8.1-301-g6cafd65%20%2832%20bit%29.7z?dl=0) (as long as he is using version 1.4 of Fallout 4), the active plugin hooks should display them correctly.

That said, once 1.5 of Fallout 4 goes live, THEN the newest snapshot with support for 1.5 needs to be used (and the plugins.txt will need to changed, so that every ACTIVE plugin has a leading asterisk * in front of it's entry (see [this](https://github.com/WrinklyNinja/libloadorder/issues/27)).

**Comment by WrinklyNinja** [comment] 2016-04-24 10:27
I'll delete snapshot 311 and build a new snapshot with the correct version of libloadorder for FO4 1.4.

**Comment by WrinklyNinja** [comment] 2016-04-24 10:46
OK, snapshot 312 is up.

**Comment by bitdman** [comment] 2016-04-24 19:45
It's all good here....lots of green check marks.    Next....whats with the warning about Loot not being sorted this session? Do we need to run LOOT before every game start?

**Comment by WrinklyNinja** [comment] 2016-04-24 20:34
> It's all good here....lots of green check marks. Next....whats with the warning about Loot not being sorted this session? Do we need to run LOOT before every game start?

No, that message is informing you that you haven't sorted your load order since opening LOOT.

@pStyl3 This one is your fault. :stuck_out_tongue:

**Comment by pStyl3** [comment] 2016-04-24 21:12
@WrinklyNinja Now, now wrinkly. Freso suggested the "no changes"-thingy in 523, and Nazeen asked for "you have not sorted your load order in this session" in 528 .. not me. I suggested to add the message about cyclic errors :smile:

Anyway, good to see that LOOT now works for you @bitdman

**Comment by WrinklyNinja** [comment] 2016-04-24 21:21
It's all these new messages, they leave me confused!

Since the issue is resolved, I'll close this.

**Closed by WrinklyNinja** 2016-04-24 21:21 UTC
