### ISSUE TITLE
masterlist cannot update

### ISSUE THREAD

**Issue by IofEyes** [loot/loot#1172] opened 2019-12-22 08:08 UTC
Hello, LOOT was working exceptionally all day on Skyrim SE, then starting producing this error in the last 2 hours:
 [00:03:19.153212] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (02006d36620a1ee65e7d9c3cc4f40ccc4a4595ed): libgit2 error
[00:03:19.154212] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
[LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/3992249/LOOTDebugLog.txt)

I tried deleting the %AppData%/Local/LOOT folder, reinstalling LOOT, and running it on an unmodded Skyrim SE, and this error still occurred. Any hints to fix this? Thanks in advance.

Extra info: Running Win7, no new system updates, Steam copy of Skyrim SE.

**Comment by CptMcSplody** [comment] 2019-12-22 11:39
@IofEyes Duplicate of #1158, try the suggestions given in that issue.

**Closed by CptMcSplody** 2019-12-22 11:39 UTC
Labels: duplicate
