### ISSUE TITLE
Loot issue 

### ISSUE THREAD

**Issue by Josniff3021** [loot/loot#1688] opened 2022-02-04 07:37 UTC
I've downloaded loot a half dozen times by now and saved it in different places, regardless of which place I pick, mods don't show up when I launch the loot app seperate of mod organizer 2, and when I do launch loot through mod organizer 2 all I get is a white screen. I've restarted the pc, Uninstalled the mods/loot/game and regardless of what I do, I'm still getting a white screen. Any help would be greatly appreciated!

**Comment by sibir-ine** [comment] 2022-02-04 08:25
Make sure to always launch LOOT once outside of MO2 when installing/updating LOOT, then run it inside MO2 to sort your mods. For the white screen issue, please see this [Q/A](https://loot.github.io/docs/help/LOOT-FAQs.html#blank-window). If you continue to experience issues with running LOOT inside MO2, please see this [Q/A](https://loot.github.io/docs/help/LOOT-FAQs.html#mo).

**Comment by Josniff3021** [comment] 2022-02-04 18:40
when I run the "--single process" argument i get a message that says "file not found"

**Comment by Josniff3021** [comment] 2022-02-04 18:42
the "--disable-gpu" peramiter gets me the same "file not found" message.

**Comment by sibir-ine** [comment] 2022-02-04 22:09
Did you put those arguments in the arguments field for your LOOT shortcut in MO2? Please post a screenshot to be sure.

**Comment by sibir-ine** [comment] 2022-02-16 07:55
Closing this as a duplicate of #974.

**Closed by sibir-ine** 2022-02-16 07:55 UTC
Labels: awaiting-feedback
