### ISSUE TITLE
Git query operation fails while executing. No commit ID match.

### ISSUE THREAD

**Issue by Astrogrinder** [loot/loot#1158] opened 2019-10-18 02:01 UTC
![Безымянный](https://user-images.githubusercontent.com/56706217/67059677-b0fd7380-f162-11e9-865d-107ffe3fe8cc.png)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3741919/LOOTDebugLog.txt)
Hi! Thank you for your amazing work. LOOT always worked perfectly but today it suddenly started doing this. I tried to delete it completely (from AppData/Local too) and reinstall two or three times but this error remained. The first time I run the program after reinstallation it understands that I'm trying to sort mods for Oblivion and sees the mods (like on screenshot), but second, third times and so on it just shows this error seemingly unaware of Oblivion and my mods. Also, Plugins.txt not set to read-only and all the file names of ESPs are in English.
What can I do about it?

Thanks in advance!

P.S. Sorry for bad English, it is not my native language

**Comment by info999** [comment] 2019-10-18 06:13
Same here for skyrim

**Comment by onimale** [comment] 2019-10-18 17:31
Same issue
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3745049/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment] 2019-10-18 17:38
@Astrogrinder @info999 @onimale 

Have you **enabled** debug logging in LOOT settings?
If not, then do so and upload a full _LOOTDebugLog.txt_.
![image](https://user-images.githubusercontent.com/1944639/67115390-ff982580-f1d5-11e9-82f1-9202da269976.png)

**Comment by onimale** [comment] 2019-10-18 17:46
Enabled
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3745090/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment] 2019-10-18 18:07
https://github.com/loot/loot/issues/1161#issue-509230496
posted by @lsr-7 
> 
> 
> So, LOOT was working fine yesterday, but when i ran the app this morning, the setting screen showed up, Although i found it weird, i hitted aplly and got an error message:
> 
> > Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
> 
> Checked the LOOTDebugLog, and got the following informations:
> 
> > [14:38:20.018310] [warning]: Blocking load of resource at [https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic](https://fonts.googleapis.com/css?family=Roboto+Mono:400,700%7CRoboto:400,300,300italic,400italic,500,500italic,700,700italic)
> > [14:38:21.203378] [warning]: No masterlist present at C:\Users\UsernameL\AppData\Local\LOOT\Skyrim\masterlist.yaml
> > [14:39:16.374534] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (df0029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
> > [14:39:16.378534] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
> > at onFailure (http://loot/ui/app.bundle.js:5039:5817)
> 
> Later i found out that, if i select "TES V Skyrim" in the game selection list and hit "Sort Load Order", LOOT does load my plugins and load order, but provides no information about my "Masterlist Revision" and "Masterlist Date".
> 
> Since i could not solve the issue, i tried to download and install LOOT's latest version, but it did not work. LOOTDebugLog returns the following:
> 
> > [14:11:29.441191] [warning]: Blocking load of resource at [https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic](https://fonts.googleapis.com/css?family=Roboto+Mono:400,700%7CRoboto:400,300,300italic,400italic,500,500italic,700,700italic)
> > [14:11:31.276295] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (500029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
> > [14:11:41.734894] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (1c0029e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
> > [14:11:41.735894] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
> > at onFailure (http://loot/ui/app.bundle.js:5039:5817)
> 
> Possible solutions that i've already tried, but didn't solve the issue:
> 
> Installing Microsoft EasyFix from issue #882
> Delete "Skyrim" folder from Appdata>Local>LOOT and let LOOT generate a new one (did it several times).
> Uninstall and reinstall LOOT version 0.14.5 (did it several times).
> Uninstall and reinstall LOOT version 0.14.6 (did it several times).
> 
> Appreciate any helpful replies.

**Comment by Astrogrinder** [comment] 2019-10-18 18:28
> @Astrogrinder @info999 @onimale
> 
> Have you **enabled** debug logging in LOOT settings?
> If not, then do so and upload a full _LOOTDebugLog.txt_.
> 
> ![image](https://user-images.githubusercontent.com/1944639/67115390-ff982580-f1d5-11e9-82f1-9202da269976.png)

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3745202/LOOTDebugLog.txt)
Enabled now

**Comment by CptMcSplody** [comment] 2019-10-18 18:29
> Enabled
> [LOOTDebugLog.txt](https://github.com/loot/loot/files/3745090/LOOTDebugLog.txt)

```log
[13:45:58.771658] [error]: 
Could not check or read potential symlink path 
"E:\Games\SteamLibrary\steamapps\common\Skyrim\": 
symlink_status: 
The parameter is incorrect.: "E:\Games\SteamLibrary\steamapps\common\Skyrim\"
```


```
[13:46:00.898780] [info]: 
Attempting to open Git repository at: C:\Users\oni\AppData\Local\LOOT\Skyrim
[13:46:00.900780] [trace]: Getting the Git object for HEAD.
[13:46:00.902780] [trace]: Generating hex string for Git object ID.
[13:46:00.903780] [trace]: Getting the Git reference for HEAD.
[13:46:00.904780] [trace]: Getting commit for ID.
[13:46:00.904780] [error]: 
Exception while executing query: 
Git operation failed. 
Details: -3; object not found - no match for id (f4022f55736572732f6f6e692f41707044617461): libgit2 error
```

**Comment by CptMcSplody** [comment] 2019-10-18 18:35
@Astrogrinder Did you reinstall Oblivion?
```
[21:22:36.472728] [error]: Cannot set the current game: the game with folder "Oblivion" is not installed.
[21:22:36.472728] [error]: Exception while executing query: Cannot set the current game: the game with folder "Oblivion" is not installed.
```
That usually means the registry entry for the game has been removed, which happens when it's reinstalled or verified.
Launching the game once will set up the registry entry.

**Comment by Astrogrinder** [comment] 2019-10-18 18:46
I installed another copy of Oblivion last week to separate directory to get some files from a clean version of the game and then deleted it leaving the current version the only one. Since then I launched Oblivion many times and LOOT was working just fine.

Just before this error started to occur, I deleted the old version of "Reneers Guard Overhaul". I tried to put it back but error remained.

I also launched Oblivion several times today but the error in LOOT won't go away

**Comment by Astrogrinder** [comment] 2019-10-18 18:52
Launched Oblivion another time, then tried LOOT - error still there

**Comment by Astrogrinder** [comment] 2019-10-18 19:08
Installed Easy Fix. Nothing changed

**Comment by pStyl3** [comment] 2019-10-18 19:14
@Astrogrinder @info999 @onimale Which Operating System and which Anti Virus software do you use?

**Comment by Astrogrinder** [comment] 2019-10-18 19:17
Windows 7 SP1
ESET Internet Security 12.2.30.0

**Comment by pStyl3** [comment] 2019-10-18 19:28
Also, please clarify when exactly the error happens. On startup? While trying to sort? While trying to update the masterlist?

In any case, go to `%localappdata%\LOOT` and open `settings.toml` with Notepad/Notepad++.
Change these two values to false:
```
updateMasterlist = false
enableLootUpdateCheck = false
```
Save the file. Try to start LOOT once more. Did that change anything?

**Comment by Astrogrinder** [comment] 2019-10-18 19:33
On startup. Changed values as recommended - nothing changed besides the absence of "loading" box

**Comment by pStyl3** [comment] 2019-10-18 19:38
Since you are using Windows 7, have you [enabled TLS 1.2 support](https://loot.github.io/docs/help/LOOT-FAQs.html#tls) (see the last point)? If no, please do so and try again.

**Comment by Astrogrinder** [comment] 2019-10-18 19:42
I have installed easy fix earlier

**Comment by pStyl3** [comment] 2019-10-18 19:46
Do you have added LOOT to the exception list of your anti virus software? If no, please try to do that (or temporarily disable your AV) and try to start LOOT once more.

**Comment by Astrogrinder** [comment] 2019-10-18 19:57
Added to exceptions - nothing changed, disabled AV - nothing changed

**Comment by pStyl3** [comment] 2019-10-18 19:59
What is your install location for LOOT?

**Comment by Astrogrinder** [comment] 2019-10-18 20:00
C:\Games\Oblivion Gold\LOOT

**Comment by pStyl3** [comment] 2019-10-18 20:02
Please install it in `C:\Games\LOOT` or preferable `D:\LOOT` and try again.

**Comment by Astrogrinder** [comment] 2019-10-18 20:17
Now, when I first launched LOOT from ned directory, it found my Skyrim but not found Oblivion. I tried to sort Skyrim mods and the program did this:
![Unnamed](https://user-images.githubusercontent.com/56706217/67124916-41d45d80-f1fc-11e9-8025-c7e152b01f1c.png)
Unfortunately, I didn't save debug log. But here is debug log from the second launch:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3745519/LOOTDebugLog.txt)
Now it was looking like before, not even showing Skyrim files

**Comment by pStyl3** [comment] 2019-10-18 20:27
Okay, let's try another approach. Uninstall LOOT and delete the LOOT folder in `%localappdata%`. Then download [LOOT 0.14.0](https://github.com/loot/loot/releases) and install that one. Are you able to start LOOT now? If yes, uninstall LOOT, download and install LOOT 0.14.1, and try again. Repeat untill you find the LOOT version that doesn't want to start anymore.

**Comment by Astrogrinder** [comment] 2019-10-18 20:36
Nothing changed... Exactly the same result

**Comment by pStyl3** [comment] 2019-10-18 20:40
Please try [LOOT 0.13.0](https://github.com/loot/loot/releases/tag/0.13.0) and [LOOT 0.12.0](https://github.com/loot/loot/releases/tag/0.12.0) as well.

**Comment by Astrogrinder** [comment] 2019-10-18 20:42
0.13.0 works! Starting to go up the versions

**Comment by Astrogrinder** [comment] 2019-10-18 20:56
0.13.6 works but 0.14.0 doesn't

**Comment by pStyl3** [comment] 2019-10-18 20:58
[Changelog for 0.14.0](https://loot.readthedocs.io/en/latest/app/changelog.html#id16)

Did you use the installer of LOOT, or the preconfigured 7z archives?

**Comment by Astrogrinder** [comment] 2019-10-18 21:00
Archives. Should I use the installer?

**Comment by Ortham** [comment] 2019-10-18 21:02
> 0.13.6 works but 0.14.0 doesn't

Thanks for that, between 0.13.6 and 0.14.0 libgit2 was updated from 0.27.4 to [0.27.7](https://github.com/libgit2/libgit2/releases/tag/v0.27.7), which included security and bug fixes ([0.27.5](https://github.com/libgit2/libgit2/releases/tag/v0.27.5), [0.27.6](https://github.com/libgit2/libgit2/releases/tag/v0.27.6)).

Though if 0.14.0 has been out for 10 months, and this issue only started to get reported in the past few weeks, so I'm not sure what the connection is.

**Comment by Ortham** [comment] 2019-10-18 21:08
> Archives. Should I use the installer?

I don't think it'll matter either way, this seems related to LOOT's code or some corruption of the local masterlist repositories rather than anything done or not done by the installer.

**Comment by Astrogrinder** [comment] 2019-10-18 21:12
So... What should I do now? Use the 0.13.6 for a while?

**Comment by Astrogrinder** [comment] 2019-10-18 21:13
Or can I somehow help further locate a problem?

**Comment by Ortham** [comment] 2019-10-18 21:14
I don't have any ideas right now for figuring out what the cause is.

Deleting your `%LOCALAPPDATA%\LOOT\<game>\.git` folder (it might be hidden) and letting LOOT download a new masterlist is reported to fix it, it would be interesting to know if it ever happens again after doing that.

**Comment by pStyl3** [comment] 2019-10-18 21:17
Though Astrogrinder has deleted the entire LOOT folder in `%localappdata%` before to no avail. The question really is why this problem started to occur only recently and only for a few people (and not for all).

**Comment by pStyl3** [comment] 2019-10-18 21:19
Some Windows Updates to Windows 7 that meddle with the MSVC 2017 x86 redistributable?

**Comment by Astrogrinder** [comment] 2019-10-18 21:20
![Unnamed1](https://user-images.githubusercontent.com/56706217/67128989-0179dd00-f206-11e9-8ae9-477a0710f19a.png)
Guys... It works. I deleted .git and it started to work! But Masterlist Revision and Date are now unknown

**Comment by pStyl3** [comment] 2019-10-18 21:21
Which LOOT version is that?

**Comment by Astrogrinder** [comment] 2019-10-18 21:21
0.14.6

**Comment by pStyl3** [comment] 2019-10-18 21:24
So .. deleting the entire LOOT folder in `%localappdata%` doesn't work, but deleting the `%LOCALAPPDATA%\LOOT\<game>\.git` folder does? :confused:

**Comment by Astrogrinder** [comment] 2019-10-18 21:26
Yup

**Comment by Astrogrinder** [comment] 2019-10-18 21:26
mIsTeRy

**Comment by pStyl3** [comment] 2019-10-18 21:27
Did you left the `%localappdata%\LOOT` folder untouched after the successful run of 0.13.6? Or did you also delete it before trying 0.14.6 once again?

**Comment by Astrogrinder** [comment] 2019-10-18 21:31
Deleted

**Comment by pStyl3** [comment] 2019-10-18 21:32
Then it didn't work, then you deleted the `.git` folder, then it started to work once again?

**Comment by Astrogrinder** [comment] 2019-10-18 21:33
Yes, exactly

**Comment by pStyl3** [comment] 2019-10-18 21:36
And in that now-working-state, with 0.14.6, what happens if you update your masterlist from within LOOT?

**Comment by Astrogrinder** [comment] 2019-10-18 21:40
Oh. Error. Again
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3745772/LOOTDebugLog.txt)

**Comment by Astrogrinder** [comment] 2019-10-18 21:44
But it seems like load order was sorted just fine...

**Comment by pStyl3** [comment] 2019-10-18 22:00
Please uninstall LOOT and delete your `%localappdata%` folder. Install 0.14.6 once again, start LOOT. The error should occur. Go to `%LOCALAPPDATA%\LOOT\<game>\` and archive the .git folder (with 7zip or some similar archiving tool). Please upload the archive here.

**Comment by Astrogrinder** [comment] 2019-10-18 22:11
[git.zip](https://github.com/loot/loot/files/3745828/git.zip)
Here it is

**Comment by Andrewpug** [comment] 2019-10-18 22:11
hey guys did you always launch loot and then just sort plugins immedialty?
 if so try to launch loot and then update masterlist the button whit the arrow down and then sort

**Comment by Astrogrinder** [comment] 2019-10-18 22:12
> hey guys did you always launch loot and then just sort plugins immedialty?
> if so try to launch loot and then update masterlist the button whit the arrow down and then sort



> Oh. Error. Again
> [LOOTDebugLog.txt](https://github.com/loot/loot/files/3745772/LOOTDebugLog.txt)

This happened

**Comment by Andrewpug** [comment] 2019-10-18 22:14
check LOOT.FAQs page the last question in there

**Comment by pStyl3** [comment] 2019-10-18 22:15
He already has @Andrewpug, see the conversation above.

**Comment by onimale** [comment] 2019-10-18 22:24
> @Astrogrinder @info999 @onimale Which Operating System and which Anti Virus software do you use?

Also windows 7
IObit Malware Fighter

sorry for late reply

**Comment by pStyl3** [comment] 2019-10-18 22:33
Can you also confirm, that LOOT 0.13.6 works for you, while LOOT 0.14.0 doesn't @onimale ? Also, does deleting the `%LOCALAPPDATA%\LOOT\<game>\.git` folder fix your problem (sort of) with LOOT 0.14.6 as well?

**Comment by onimale** [comment] 2019-10-18 22:34
Will confirm when it finishes uninstalling 0.14.x

**Comment by onimale** [comment] 2019-10-18 22:39
ok 0.13.6 does work flawlessly

**Comment by onimale** [comment] 2019-10-18 22:46
> Can you also confirm, that LOOT 0.13.6 works for you, while LOOT 0.14.0 doesn't @onimale ? Also, does deleting the `%LOCALAPPDATA%\LOOT\<game>\.git` folder fix your problem (sort of) with LOOT 0.14.6 as well?

Yes, deleting `%LOCALAPPDATA%\LOOT\<game>\.git` does (sort of) fix it

**Comment by lsr-7** [comment] 2019-10-18 22:49
@pStyl3 i’m so sorry for step in the conversation like that, but since i’m facing the exact same issue reported here and i’m very interested in its solution, i just wanna confirm that LOOT 0.13.6 worked for me too, and deleting the .git folder caused the same outcome reported by Astrogrinder.

**Comment by floppyD** [comment] 2019-10-19 04:49
Just letting you guys know that I'm also having this issue. Windows 7 x64 - LOOT 0.14.6. It was working fine like 2 days ago. Already tried reinstalling and removing the %appdata folder completely, but nothing.
Here's the log, clean install
```[01:43:03.870733] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[01:43:05.344818] [warning]: No masterlist present at C:\Users\Thiago\AppData\Local\LOOT\Morrowind\masterlist.yaml
[01:43:05.391820] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[01:43:14.150321] [warning]: No masterlist present at C:\Users\Thiago\AppData\Local\LOOT\Skyrim\masterlist.yaml
[01:43:14.176323] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[01:44:06.643324] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (033e29e75a7220bbc40f0b32d47e896032366dd0): libgit2 error
[01:44:06.645324] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5757:9194)
```

**Comment by pStyl3** [comment] 2019-10-19 07:25
@lsr-7 No need to be sorry, you're providing valuable feedback. What Operating System do you use?
@floppyD Does deleting your `%LOCALAPPDATA%\LOOT\<game>\.git` folder also (sort of) fix your issue?

@Astrogrinder @info999 @onimale @lsr-7 @floppyD 
Which language does your Operating System use?

**Comment by Astrogrinder** [comment] 2019-10-19 08:29
Russian

**Comment by onimale** [comment] 2019-10-19 19:03
English

**Comment by floppyD** [comment] 2019-10-19 19:31
@pStyl3 Looks like deleting that folder fixes it. I've launched LOOT 3 times and sorted in every session and got no errors.
Brazilian Portuguese.

**Comment by lsr-7** [comment] 2019-10-19 20:23
@pStyl3 Windows 7 - Portuguese (BR)

Today i tried to run version 0.14.6 again, and got the same error. So i unistalled it, deleted the LOOT folder in LocalAppData, and installed the 0.13.6 version. After running this old version and updating the masterlist (which i was able to do, 'cause it was the old app version), i returned to LOOT's folder located in LocalAppData and copied both ".git folder" and "masterlist.yaml", in order to use them to replace LOOT's 0.14.5 files (my last functional app version). Strangely, after i unstalled version 0.13.6, deleted both folders located in "Program Files" and "LocalAppData", and reinstalled 0.14.5, LOOT STARTED TO WORK AGAIN. Not only i was able to sort my load order, but to update my masterlist as well. I didn't even have to replace the files, like i was thinking of. Now i'm afraid to try version 0.14.6 and start the nightmare again lol. 

Think i'll keep LOOT's 0.14.5. Thank you all for you attention.

**Comment by onimale** [comment] 2019-10-19 23:31
0.14.5 also works for me

**Comment by Astrogrinder** [comment] 2019-10-20 00:12
I just checked — for me too!

**Comment by Astrogrinder** [comment] 2019-10-20 00:13
Wait a minute... 0.14.6 works too! Like nothing happened

**Comment by lsr-7** [comment] 2019-10-20 02:41
Cheers!

**Comment by Warzychewka** [comment] 2019-10-24 16:33
I've experienced the similiar on-startup "Oh no" error as described in this topic every time I've tried to launch LOOT (either via Mod Organizer 2 or on its own) in the last few days and the user Ortham instructed me to post and try some fixes described here.

It seems that my problem has been resolved by reinstalling LOOT a few more times (and clearing both its install folder and AppData one).

Sadly, I'm not excatly sure what I did - I know I changed my install folder from _[Skyrim folder]\LOOT_ to _D:\LOOT_ (as suggested in one of the above posts) which resulted in the program no longer recognizing Skyrim as an installed game (it defaulted to my Fallout New Vegas and the selection option for Skyrim was 'greyed-out') and returning a new DebugLog problems (however I did not copy them anywhere before I accidentally fixed the issue -- I didn't expect I will).
Somehow I've managed to resolve it by either manually typing Skyrim's install path in Loot's settings (if it actually did anything), moving its folder back to Skyrim's one and clearing-and-restoring AppData a few times.

As I've said, I'm not sure what have I done but my LOOT suddenly started up without errors, recognized Skyrim as installed game and sorted my load order. It was a fresh-start with first-time tips, though. I've restarted it a few times to check -- and it seems to work, at least for now.

Here's the pastebin link for my previous DebugLog, for reference: https://pastebin.com/4gxF5aEj
My OS is Windows 7 Ultimate, currently no antivirus (unistalled it about a  week and a half ago). I'm using the current available version of LOOT (0.14.6?).

But, as I've said, it all now works. I'm not sure why and I'm sorry I couldn't provide more specific details of what I did/messed up -- I'm sure it could help others who'll experience that issue. The fact it worked after reinstalling is weird to me, as I've tried that before to no effect. I'm also not sure why it did not recognize Skyrim as an installed game -- it's an issue I also have with the newest version of Wrye Bash, so it's a weird coincidence. I don't have much use for the latter program so I didn't try to fix it.

I've decided to post here anyway as an update of sorts to my previous topic referenced above.

**Comment by SirJorb** [comment] 2019-12-22 08:27
Using Windows 7 here, and was working fine until partway through today. Deleting the folder from local appdata as mentioned above sort of works, in that I can launch it and sort once, but after that the same error pops right back up again.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3992272/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment] 2019-12-22 11:41
https://github.com/loot/loot/issues/1172#issue-541439961
Posted by @IofEyes 
> Hello, LOOT was working exceptionally all day on Skyrim SE, then starting producing this error in the last 2 hours:
>  [00:03:19.153212] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (02006d36620a1ee65e7d9c3cc4f40ccc4a4595ed): libgit2 error
> [00:03:19.154212] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
> [LOOTDebugLog.txt](https://github.com/loot/skyrimse/files/3992249/LOOTDebugLog.txt)
> 
> I tried deleting the %AppData%/Local/LOOT folder, reinstalling LOOT, and running it on an unmodded Skyrim SE, and this error still occurred. Any hints to fix this? Thanks in advance.
> 
> Extra info: Running Win7, no new system updates, Steam copy of Skyrim SE. 
>

**Comment by IofEyes** [comment] 2019-12-22 14:58
Thanks @CptMcSplody for directing me to the correct post. I've enabled debugging and here in the LOOTDebugLog.text

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3992599/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment] 2019-12-23 01:48
https://github.com/loot/loot/issues/1173#issue-541535164
Posted by @EscondeR 
> Upon trying to update (download after fresh install) the masterlist for SSE, I get the following error:
> 
> `[22:44:01.002510] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> [22:44:02.418591] [warning]: No masterlist present at C:\Users\ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
> [22:44:02.773612] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
> [22:44:03.228638] [warning]: No masterlist present at C:\Users\ÐÐ´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
> [22:44:05.161748] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
> [22:44:23.658806] [error]: Could not delete temporary repository path "C:\Users\836D~1\AppData\Local\Temp\LOOT-Skyrim Special Edition-2fd8a611-00f8-489b-808f-26d0f1466bd3": remove_all: Îòêàçàíî â äîñòóïå.
> : "C:\Users\836D~1\AppData\Local\Temp\LOOT-Skyrim Special Edition-2fd8a611-00f8-489b-808f-26d0f1466bd3"
> [22:44:24.710866] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (ab002f55736572732fd090d0b4d0bcd0b8d0bdd0): libgit2 error
> [22:44:24.711867] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
>     at onFailure (http://loot/ui/app.bundle.js:5761:9231)`
> 
> Masterlists for Morrowind, Oblivion, Fallout NV, Fallout 4 and even regular Skyrim (LE) are updating normally at the same time (same LOOT version, same session, w/o restart).
> Please assist with that issue!
> It looks like the latest masterlist for SSE is corrupt.

**Comment by pStyl3** [comment] 2021-01-24 14:47
Can we close this issue? Unless I'm mistaken, the issue hasn't shown up in at least one year, and in the meantime versions 0.15.0, 0.15.1 and 0.16.0 have been released.

**Comment by Ortham** [comment] 2021-01-24 14:59
I think closing this is reasonable, given the lack of recent reports.

**Closed by Ortham** 2021-01-24 14:59 UTC
Labels: bug
