### ISSUE TITLE
Add warning messages when using ESL plugins in Skyrim VR and Fallout 4 VR

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1949] opened 2023-12-16 23:09 UTC
LOOT treats Skyrim VR like Skyrim SE, and Fallout 4 VR like Fallout 4, but the VR versions do not support plugins with a .esl file extension and do not recognise the light flag when it is set.

A new complication is that there's now an SKSEVR [plugin ](https://www.nexusmods.com/skyrimspecialedition/mods/106712?tab=description) that adds support for Skyrim SE's recently-supported extended object ID range in ESL plugins.

It would be good if LOOT warned users appropriately, e.g.

- If .esl plugins are installed and the SKSEVR plugin is not installed, warn that the plugins won't be recognised by the game.
- If a non-.esl light plugin is installed and the SKSEVR plugin is not installed, maybe warn that the plugin will not load as a light plugin?
- If a light plugin and the SKSEVR plugin are installed, warn that the game must be launched using SKSEVR.

pStyl3 has a VR headset and a copy of Skyrim VR so could help test. More context is also in Discord [here](https://discord.com/channels/473542112974077963/496196499890241546/1185465994462896128)

**Comment by pStyl3** [comment] 2024-05-05 18:50
Some months ago I've run a few tests to check Skyim VR's behaviour. See this [Discord Link](https://discord.com/channels/473542112974077963/496196499890241546/1185607355602305125) for the whole conversation.

The results were:
- VR ignores the `ESL` flag, `.esm` and `.esp` plugins with it will load normally
- `.esl` plugins will not work in VR

Using the above mentioned mod [Skyrim VR ESL Support](https://www.nexusmods.com/skyrimspecialedition/mods/106712/) and all it's requirements
[SKSEVR](https://www.nexusmods.com/skyrimspecialedition/mods/30457/)
[Engine Fixes VR](https://www.nexusmods.com/skyrimspecialedition/mods/62089/)
[VR Address Library for SKSEVR](https://www.nexusmods.com/skyrimspecialedition/mods/58101/)

.. I could succesfully load `AcolyteMasks.esl` from [DragonPriest Retexture - SE](https://www.nexusmods.com/skyrimspecialedition/mods/41713/) in VR - which wasn't possible before.

**Comment by pStyl3** [comment] 2024-05-05 19:54
Definition:
- a `.esp` with `ESL` flag is a `Light Plugin`
- a `.esm` with `ESL` flag is a `Light Master`
- a `.esl` is a `Light Master`

Given the above notation, I would suggest the following message, in case at least one Light Master or Light Plugin has been found, but the ESL support mod hasn't been installed:

> It appears you have installed at least one Light Master or Light Plugin, but [Skyrim VR ESL Support](https://www.nexusmods.com/skyrimspecialedition/mods/106712/) seems to be missing. Please ensure you have correctly installed Skyrim VR ESL Support and all it's requirements.

(It's a variation of [&missingRequirementXforY](https://github.com/loot/prelude/blob/v0.21/prelude.yaml#L624))

If I were to write the condition for that message in the masterlist, I would probably write:
`condition: 'file("([^\.]+\.esl)") and not file("SKSE/Plugins/skyrimvresl.dll")'`

But that would only find `.esl` plugins and not `.es[mp]` plugins with the `ESL` flag.

This probably should be enough to handle the issue.

**Comment by Ortham** [comment] 2024-05-07 16:44
The approach I've taken in the `skyrimvr-light-plugins` branch is to have multiple different messages for different plugin types, plus for FO4VR the .esl message says that the plugin won't be loaded, while for light-flagged .esm and .esp plugins the message says they'll be loaded as normal masters/plugins.

**Comment by Ortham** [comment] 2024-05-08 21:06
@pStyl3 Can you test the `skyrimvr-light-plugins` branch build with Skyrim VR to see if it works as expected?

**Comment by pStyl3** [comment] 2024-05-08 22:33
I'll take a look in a bit, but first some small sidenote: our SKSEVR latest version check in the masterlist may not work as intended right now (and thus it has been confusing me for some time).

Our masterlist entry:
```yaml
# Latest Version
  # SKSE VR
  - <<: *versionOldX
    subs: [ '**[SKSE VR](https://skse.silverlock.org)**' ]
    condition: 'version("../skseVR_loader.exe", "0.2.0.12", <) and file("../skseVR_loader.exe")'
  - <<: *versionUpToDateX
    subs: [ '**SKSE VR**' ]
    condition: 'version("../skseVR_loader.exe", "0.2.0.12", >=) and file("../skseVR_loader.exe")'
```
The current SKSEVR from [silverlock](https://skse.silverlock.org/) "Current VR build 2.0.12 (game version 1.4.15)" includes `sksevr_loader.exe` and it's version is `0.2.0.12` - so far so good.

However, SKSEVR is also available on [Nexus](https://www.nexusmods.com/skyrimspecialedition/mods/30457/) and the Nexus' version is stated to be the same as on silverlock (2.0.12). That being said the version of `sksevr_loader.exe` from the Nexus download is `0.2.0.11`

This seems to be an oversight from the SKSE team. @ianpatt You might want to push a fix for this to the SKSEVR Nexus page.

This means that right now people can download the "latest" SKSEVR from Nexus, and LOOT tells them that they do not use the latest SKSEVR version (since `sksevr_loader.exe` from that download is only of version `0.2.0.11`).

**Comment by pStyl3** [comment] 2024-05-08 22:46
![grafik](https://github.com/loot/loot/assets/10406657/e231ba98-2fce-4206-b3a5-cd414a678c6e)

This message triggerd correctly, but I would suggest to display it as an error instead of a warning.

**Comment by pStyl3** [comment] 2024-05-08 23:09
Also working with a `ESL` flagged `.esp`

![grafik](https://github.com/loot/loot/assets/10406657/df4a494a-49c5-4e6e-a913-9ae6588c7a16)

**Comment by pStyl3** [comment] 2024-05-08 23:13
Also working with a `ESL` flagged `.esm`

![grafik](https://github.com/loot/loot/assets/10406657/79ffaeab-be22-4ec4-9de9-7eb8519d8d86)

**Comment by pStyl3** [comment] 2024-05-08 23:20
When using the above mods while the ESL support mod is disabled, `LOOTDebugLog.txt` will include:

```
[01:17:20.060564] [warning]: "ApachiiHair.esm" is a light plugin but the game does not support light plugins.
[01:17:20.061555] [warning]: "AcolyteMasks.esl" is a light plugin but the game does not support light plugins.
[01:17:20.062071] [warning]: "SofiaFollower.esp" is a light plugin but the game does not support light plugins.
```
Which I guess is intended behaviour.

**Comment by ianpatt** [comment] 2024-05-09 00:05
> This seems to be an oversight from the SKSE team. @ianpatt You might want to push a fix for this to the SKSEVR Nexus page.

Fixed, thanks for letting me know. This was from when Nexus was managing the page themselves.

**Comment by pStyl3** [comment] 2024-05-09 05:42
> Fixed, thanks for letting me know. This was from when Nexus was managing the page themselves.

Thank you!

**Comment by pStyl3** [comment] 2024-05-09 18:08
Using `loot_0.22.3-69-gbc5a440_skyrimvr-light-plugins-win64.7z` now. I think this is better.

![grafik](https://github.com/loot/loot/assets/10406657/10083b08-f31c-47ea-9eae-9b876c7c6a82)

**Comment by Ortham** [comment] 2024-05-09 18:52
OK, done in b70691a527bfb9c3a3b8bdf22f6741c2bea23583.

**Comment by Ortham** [comment] 2024-05-10 16:17
I don't see that, does it happen if you launch LOOT right into Fallout 4, or did you switch games? I noticed I missed a couple of updates to move constructors that might explain this.

**Comment by pStyl3** [comment] 2024-05-10 16:29
I can pretty reliably trigger the issue, if after starting LOOT I go into the settings and save-close the settings window, and then sort the load order.

**Comment by Ortham** [comment] 2024-05-10 16:32
@pStyl3 can you try with this build? https://github.com/loot/loot/actions/runs/9035099363

**Comment by pStyl3** [comment] 2024-05-10 16:41
That build seems to have fixed the issue. 👍

**Closed** 2024-05-17 20:17 UTC
Labels: enhancement
