### ISSUE TITLE
Loot Application Crashes when i sort oblivons load order

### ISSUE THREAD

**Issue by FunkyPixie** [loot/loot#793] opened 2017-06-18 13:11 UTC
I dont know why but when i click on sort load order in the oblivion area the application just crashes 
Here are the debug logs

[CEFDebugLog.txt](https://github.com/loot/loot/files/1083097/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1083104/LOOTAPIDebugLog.txt)

I read the how to report issues helpfully page and i hope i've given enough information

**Comment by WrinklyNinja** [comment] 2017-06-18 13:45
Try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-13-gb4b650b_dev.7z).

**Comment by FunkyPixie** [comment] 2017-06-18 16:27
hmmm same thing seems to happen (I clicked on the sort plugins button and after it updates the master list the program crashes during sorting)

Here are the debug logs
[CEFDebugLog.txt](https://github.com/loot/loot/files/1083205/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1083206/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1083207/LOOTDebugLog.txt)

I dont know what's happening as its never happened before.

**Comment by FunkyPixie** [comment] 2017-06-18 16:28
Oh and it only seems to happen with oblivion, when i click on sort plugins with fallout new vegas it sorts it with crashing

**Comment by WrinklyNinja** [comment] 2017-06-18 16:34
Oh, wait, I linked you to the wrong thing, the fix hasn't been integrated into LOOT yet. Replace the `loot_api.dll` in your LOOT install with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.0-8-gc975de6_dev-win32.7z).

It looks like `Moner ring.esp` is corrupt in some way, LOOT can't read it properly and that's causing the crash. The above DLL should change it so that it just doesn't appear in LOOT.

**Comment by FunkyPixie** [comment] 2017-06-18 20:28
Haha It works. Thank you soo much for helping

**Comment by WrinklyNinja** [comment] 2017-06-19 06:57
Closing this as a duplicate of #787 then.

**Closed by WrinklyNinja** 2017-06-19 06:57 UTC
