### ISSUE TITLE
Loot does not run on proton

### ISSUE THREAD

**Issue by suamor** [loot/loot#1936] opened 2023-11-01 11:08 UTC
I have tried out the latest available stable version of proton and a later (staged) version but everytime loot is crashing.
I needed to research because I wanted to exclude issues in my setup.

This proton prefix works with mo2 and other programs. All the messages shown during start have nothing to do with the crash.
There were several changes in Qt6.5 that causes now issues with proton (and maybe older Windows 10 releases).

Here are the collected issue report and merge request (for wine) that could solve the issue (I do not build wine myself):
https://github.com/Modorganizer2/modorganizer/issues/372
https://gitlab.winehq.org/wine/wine/-/merge_requests/3931 (is on hold because tests are missing).

Summary: I need to downgrade loot to a version that does not use Qt 6.5 (and can't build later version with QT 6.4 myself since I don't have windows). (Linux version can't obviously not be used from mo2).

Workaround: Use Loot 0.19.1 or find a build service (by forking loot) that builds 0.22.0 with Qt6.4.

Version tested: Loot 0.22.0 (uses Qt 6.5.3.0)
Also not working: Loot 0.21 (Qt 6.5.2), 0.20 (Qt 6.5.1).

**Comment by Ortham** [comment] 2023-11-01 11:15
Duplicate of #1886, I suggest you re-post there to keep everything in one place.

**Closed by Ortham** 2023-11-01 11:15 UTC
Labels: duplicate, linux
