### ISSUE TITLE
Masterlist won't update if user temp folder changed

### ISSUE THREAD

**Issue by damnsalvation** [loot/loot#561] opened 2016-04-11 23:03 UTC
I had the user environment TEMP and TMP variables set to G:\UserTemp\Local\Temp
Opened loot to order skyrim, which I had just reinstalled. Tried to update masterlist, got a filesystem access error. Forget the exact error, but it was a 'could not modify' listing directories:
C:\Users...\LOOT\skyrim
G:\UserTemp\Local\Temp{random}

procmon showed LOOT.exe tried to open G:\UserTemp\Local\Temp{random}, and was denied because it didn't exist

From Log:
[0409/171435:ERROR:main_delegate.cc(738)] Could not load cef_extensions.pak

Since it looked like look was trying to use a generated temp folder, but without actually creating it first, I changed my TEMP and TMP variables back to the defaults. It worked. Masterlist updated just fine. Then I realized I should report the bug so I thought I'd change the variables back to get the exact error that popped up. But it didn't. Not sure why, maybe because it didn't need to update again.
It's a pretty rare set of circumstances, so not exactly a high priority.

Permissions were correct.

**Comment by WrinklyNinja** [comment] 2016-04-12 05:05
Did `G:\UserTemp\Local\Temp` exist before you ran LOOT? It probably expects the temporary directory to exist when it tries to create a folder in it (which can happen during masterlist update, yes).

**Comment by damnsalvation** [comment] 2016-07-12 21:52
Oh, sorry I never replied, but yes

**Comment by Tal2baro** [comment] 2016-08-25 20:59
I just installed the v0.9.2 with the same kind of setup than damnsalvation and I just had the same problem that I also solved changing back the temp variables back to default in my windows profile.

Seems this bug has to be re-opened

**Comment by WrinklyNinja** [comment] 2016-08-26 05:42
> I just installed the v0.9.2 with the same kind of setup than damnsalvation and I just had the same problem that I also solved changing back the temp variables back to default in my windows profile.

Please supply your debug log as described in [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Tal2baro** [comment] 2016-08-26 20:27
Please find attached the logs.

To reproduce the bug : 
- I changed again my temp variables to custom ones in my profile
- I moved the masterlist and .git folder found in my Loot\Skyrim folder to a backup folder
- I launched Loot from windows file explorer and clicked on the masterlist update button found next to the sort button.

Hope it helps
[CEFDebugLog.txt](https://github.com/loot/loot/files/440087/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/440088/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2016-08-27 09:55
Does `D:\Temp\59b4-55b8-4db5-2724` exist?

**Comment by Tal2baro** [comment] 2016-08-28 20:19
No it doesn't.

I even tried to look for it before to acknowledge the error in LOOT in hope to find it and the masterlist within. In vain.

Don't know if it can come from it, but the temp variables can be written with and without the "\" at the end. Could this be the problem ??

**Comment by WrinklyNinja** [comment] 2016-08-29 14:26
I tried replicating the bug following your instructions, I changed the TEMP and TMP environmental variables to `C:\Temp`, but it worked for me (and I could see the temporary folder get created in the correct place).

> Don't know if it can come from it, but the temp variables can be written with and without the "\" at the end. Could this be the problem ??

No, that shouldn't be an issue, because the path in the log (`D:\Temp\59b4-55b8-4db5-2724`) has a backslash, so it's getting added.

The error message is `Accès refusé: "C:\Users\Dam\AppData\Local\LOOT\Skyrim", "D:\Temp\59b4-55b8-4db5-2724"`, and the previous action is to grant write permissions to `C:\Users\Dam\AppData\Local\LOOT\Skyrim`, so are you sure you've got write permission for `D:\Temp`? Does running LOOT as admin work?

**Comment by Tal2baro** [comment] 2016-08-29 19:43
Running LOOT as admin didn't work. That was my first try to solve the problem.
I checked the security parameters of D:\Temp : Authenticated users have modification, administrators full control. This is a folder that I created before setting the temp variables. Strangely my profile is not listed...
I checked also the local/LOOT folder parameters : My profile has full access and so administrators.

**Comment by Tal2baro** [comment] 2016-08-29 19:48
Adding my profile with full control to D:\Temp doesn't change anything....
Should I tell you that I'm running Windows 10 rev 1511 ?

**Comment by WrinklyNinja** [comment] 2016-08-30 17:56
I don't think that should matter, I'm running Win10 too. What happens if you change your temp folder so that it's on the C drive (if you can)?

**Comment by Tal2baro** [comment] 2016-08-31 20:23
I just tried setting temp to `C:\Temp`. It worked like a charm !
It has the same security settings as `D:\Temp` ....

**Comment by WrinklyNinja** [comment] 2016-09-01 16:25
OK, so it's something to do with being on a different drive, that gives me a lead at least...

**Comment by WrinklyNinja** [comment] 2016-09-15 08:17
This should now be fixed in [this snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.9.2-66-g20b296a_masterlist-update-fix#files), could someone please confirm?

Unfortunately I couldn't figure out why moving a folder to a different drive was causing an issue, it shouldn't have done so according to the WinAPI functions being called, so I sidestepped the issue by keeping the temporary folder inside the LOOT data directory, and not using the user's temporary directory.

**Comment by Tal2baro** [comment] 2016-09-17 13:23
I tried the build successfully.
My temp was set to 'D:\temp', I backed up the masterlist, backed up my actual LOOT and replaced by the snapshot.
I launched LOOT, asked for the masterlist update and then sorted my plugins. Everything went without any issues.

Thanks for your work !

**Closed** 2016-09-17 13:28 UTC
Labels: bug
