### ISSUE TITLE
Failed to launch child process (sames as #233)

### ISSUE THREAD

**Issue by Mordicus** [loot/loot#487] opened 2015-09-20 03:42 UTC
Hello: Using MO 1.3.11 and LOOT 0.80 I have the same issue describe here:
https://github.com/loot/loot/issues/299

Loot works when launched alone, when launched from MO it displays a blank window.

And here:
LOOT's window is blank when I'm starting it through Mod Organizer. What's up?
Mod Organizer 1.2.10 has a bug preventing LOOT 0.7.0 from working properly. This will be fixed with Mod Organizer 1.2.11, but until that is released, you will need to downgrade to Mod Organizer 1.2.9.
https://github.com/loot/loot.github.io/wiki/LOOT-FAQs/835ebf3b205fad6ee32b57565d339d57cff3cdfc

Here is the log:
[0920/112647:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
[0920/112647:ERROR:main_delegate.cc(567)] Could not load locale pak for en-US
[0920/112647:WARNING:resource_bundle.cc(501)] locale resources are not loaded
[0920/112647:ERROR:child_process_launcher.cc(479)] Failed to launch child process
[0920/112647:ERROR:child_process_launcher.cc(479)] Failed to launch child process

My system: Win7 SP1 x64

**Comment by WrinklyNinja** [comment] 2015-09-20 09:32
This is a duplicate of #299, #463 and #482, and the [FAQ](https://github.com/loot/loot.github.io/wiki/LOOT-FAQs#loots-window-is-blank-when-im-starting-it-through-mod-organizer-whats-up) contains a workaround, so closing this.

As far as I can tell, the issue is caused by the way MO's profiling feature works (or occasionally doesn't) with LOOT's multi-process architecture. There's unlikely to be anything I can do about that, but any further discussion that may take place should happen in #482.

**Closed by WrinklyNinja** 2015-09-20 09:32 UTC

**Comment by Mordicus** [comment] 2015-09-20 18:04
I've tried adding "--single-process" argument to LOOT in MO, it worked! Thanks for the link.
