### ISSUE TITLE
Issue after update (Skyrim Radioactive -..esp| Old masterlist v0.10)

### ISSUE THREAD

**Issue by Extront** [loot/loot#1199] opened 2020-04-22 12:14 UTC
[07:48:54.618467] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[07:48:57.792550] [error]: Exception while executing query: exists: The filename, directory name, or volume label syntax is incorrect.
: "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim Radioactive -.*\.esp"
[07:48:57.794270] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5761:9231)
[07:49:41.791847] [error]: Exception while executing query: exists: The filename, directory name, or volume label syntax is incorrect.
: "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Skyrim Radioactive -.*\.esp"
[07:49:41.792499] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5761: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5761:9231)

**Comment by CptMcSplody** [comment] 2020-04-22 12:17
Duplicate of https://github.com/loot/loot/issues/1181

@Extront 

> > : "D:\Steam\steamapps\common\SkyrimVR\Data\Skyrim Radioactive -.*.esp"
> 
> ```yaml
>       - 'Skyrim Radioactive -.*\.esp'
> ```
> 
> That metadata is only present in an older version v0.10 of the SSE/SVR masterlist.
> _v0.15_ is the current and supported branch.
> Make sure `AppData\Local\LOOT\settings.toml` has the right settings for branch.
> 
> ```
> [[games]]
> 	branch = "v0.15"
> 	folder = "Skyrim VR"
> 	repo = "https://github.com/loot/skyrimse.git"
> 	type = "Skyrim VR"
> 	name = "TES V: Skyrim VR"
> ```
> 
> If that's correct then try deleting the entire contents of `AppData\Local\LOOT`.
> Then run LOOT outside your mod manager and update the masterlist.

**Comment by Extront** [comment] 2020-04-22 12:21
That worked, thank you!

**Comment by CptMcSplody** [comment] 2020-04-22 12:26
> That worked, thank you!

You're welcome. I've updated the title to hopefully make it easier for other users to find the solution.

**Closed by CptMcSplody** 2020-04-22 12:26 UTC
Labels: duplicate
