### ISSUE TITLE
Creates unnecessary folder on C

### ISSUE THREAD

**Issue by Merisal** [loot/loot#740] opened 2016-12-30 08:44 UTC
Everytime you start LOOT it creates a folder named **Program** directly on C:\.
After a restart of your computer you'll get the message from Windows that there is a folder named Program which can cause issues on Windows and the option to rename it.

Renaming the folder will cause in the creation of a new one if you start LOOT again.

It does not depend on which way you use to start LOOT (shortcut out of MO or the exe directly).

**Comment by WrinklyNinja** [comment] 2016-12-30 09:12
This looks like a duplicate of #737, except that you're saying LOOT creates the folder even when run outside of MO, which I've never seen, nobody has ever mentioned before, and there's nothing in the code that should come close to doing that.

Where did you install LOOT to, and what are the values of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{F1B32785-6FBA-4FCF-9D55-7B8E7F157091}\Relative Path` and `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{F1B32785-6FBA-4FCF-9D55-7B8E7F157091}\Relative Path` in your Registry?

**Comment by Merisal** [comment] 2016-12-30 09:37
Reinstalled LOOT to have a clean installation and removed the other installation I used for Skyrim Legendary.
At this point there are no folders created anymore. Looks like MO had a problem with the older version of LOOT I used for Skyrim Legendary on a seperate installation path. 

I apologize for the double entry.

**Closed** 2016-12-30 09:43 UTC
Labels: duplicate, invalid
