### ISSUE TITLE
Zyklische Interaktion because 2 master but one of them is no master

### ISSUE THREAD

**Issue by Dreifels** [loot/loot#1512] opened 2021-05-24 23:22 UTC
I get error message when try to sort load order:
"Zyklische Interaktion zwischen "PiratesNorth.esp" und "DynDOLOD.esm" festgestellt:
PiratesNorth.esp
 [Master]
DynDOLOD.esm
 [Master Flag]
PiratesNorth.esp"
However, PiratesNorth.esp is no master.

1st I installed PiratesNorth.esp with ESM flag, then I got the message above, I exit and removed the ESM flag from PiratesNorth.esp, then startet new. So PiratesNorth.esp no longer has the flag.
Nevertheless, I still get same message, means, LOOT does not notify that the file has changed, probably ready from cache and not from real .

The debug log reads
"[01:20:30.424100] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[01:20:31.416061] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[01:20:34.741271] [error]: Failed to sort plugins. Details: Cyclic interaction detected: PiratesNorth.esp --[Master]-> DynDOLOD.esm --[Master Flag]-> PiratesNorth.esp
[01:20:34.751322] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4403: Error: Sortieren der Plugins fehlgeschlagen. Details: see general messages for details.
    at cl (http://loot/ui/app.bundle.js:4403:22320)"

**Comment by MacSplody** [comment] 2021-05-25 00:07
> DynDOLOD.esm
>  [Master Flag]
> PiratesNorth.esp"

`DynDOLOD.esm` has an **ESM** flag because it's an `.esm`, but `PiratesNorth.esp` does not have an **ESM** flag.

> PiratesNorth.esp
>  [Master]
> DynDOLOD.esm

It seems like your copy of `DynDOLOD.esm` has `PiratesNorth.esp` as a master file, which is causing the sorting error.
Not sure how that could happen, did you sort your mods before building DynDOLOD?

**Comment by MacSplody** [comment] 2021-05-25 00:14
The file on the Nexus has an **ESM** flag. [Pirates of The North SSE](https://www.nexusmods.com/skyrimspecialedition/mods/28985)
![image](https://user-images.githubusercontent.com/1944639/119421264-3c06fe00-bcf6-11eb-9b74-d9232401bd35.png)

Did you build DynDOLOD by any chance and then unflag the file?

**Comment by Dreifels** [comment] 2021-05-25 00:20
1) no it is nt that mod you send image from
It is file PiratesNorth.esp of mod Shumer
https://www.nexusmods.com/skyrimspecialedition/mods/28039
Original the modder set the esp (all three ESPs of the mod)  with ESM flag, but after I got the error message I removed the flag, but nevertheless got same errror message.

**Comment by MacSplody** [comment] 2021-05-25 00:44
>        Original the modder set the esp (all three ESPs of the mod)  with ESM flag, but after I got the error message I removed the flag, but nevertheless got same errror message.

Can your restore the ESM flag to the ESPs or reinstall them and try sorting again?

I can only replicate it if I have `PiratesNorth.esp` as a master file of `DynDOLOD.esm` and then removed the ESM flag from `PiratesNorth.esp`.

**Comment by Dreifels** [comment] 2021-05-25 01:37
I uninstalled DynDoLod output and let it generate a new output. With that I got no error message.
But it is curious nevertheless, as before (my first install of v. 3.8 update) it did work fine. But as the esp was bad in SSEdit, I did clean it, and after that I got the error., even if I had removed the ESM flag. Looks for me as LOOT did read from cache not from real new files, as the load order had be different w/o the ESM flag. (and now it is different than before)

**Comment by sibir-ine** [comment] 2021-05-25 05:33
@Ortham would know for sure, but I'm pretty sure LOOT reloads all plugin data each time you sort. It doesn't cache any plugin data.

> I get error message when try to sort load order:
"Zyklische Interaktion zwischen "PiratesNorth.esp" und "DynDOLOD.esm" festgestellt:
PiratesNorth.esp
 [Master]
DynDOLOD.esm
 [Master Flag]
PiratesNorth.esp"
However, PiratesNorth.esp is no master.
> 
> 1st I installed PiratesNorth.esp with ESM flag, then I got the message above

This doesn't make sense, the error is essentially saying "`DynDOLOD.esm` has `PiratesNorth.esp` as a master, so it has to load after, but `DynDOLOD.esm` has a master flag (which `PiratesNorth.esp` doesn't), so `PiratesNorth.esp` has to load after," hence the cyclic interaction. This specific interaction can't have happened if `PiratesNorth.esp` had a master flag. That means the master flag was removed from `PiratesNorth.esp` before you ran LOOT. Can you please try to reproduce this issue from scratch (i.e., keep the master flag on `PiratesNorth.esp`, regenerate DynDOLOD, run LOOT)? If it doesn't happen again, the master flag must've gotten removed from `PiratesNorth.esp` before you ran LOOT.

**Comment by Dreifels** [comment] 2021-05-25 13:36
again, to better understanding log version:
1) I hade installed the shumer mod log time,while bith, shumer NWa.esp and PiratesNorth.esp had no ESM flag, but ShumerWorld only.
2) I always had Dyndolod installed incl. these mod, running fine
3) Now I made an update of shumer, the original shumer files do have all 3 files flagged as ESM
4) made NO update of DynDoLod output, all was fine
5) made translation and SSEditAutoclean for ShumerNWa and Pirates North but let the original ESM flag exist, made NO DynDoLod update - and now got this error message
6) removed the ESM flags for both,  ShumerNWa and Pirates North, made no DynDoLod update, and nevertheless got the error althoght ESM was removed.
7) uninstalled DynDoLod, made now DynDoLod output, so now instalaled new DnyDoLod along with ShumerNWa and Pirates North both NO ESM Flag and it works fine.

**Comment by Ortham** [comment] 2021-05-25 19:35
> @Ortham would know for sure, but I'm pretty sure LOOT reloads all plugin data each time you sort. It doesn't cache any plugin data.

That's correct.

**Comment by sibir-ine** [comment] 2021-05-26 12:48
@Dreifels That's why I'd like to see if you can reproduce the issue. Neither Mac nor I can, so the best we can offer you right now is to tell you to regenerate DynDOLOD for your new load order (which you already have & it has resolved the cyclic interaction).

From your summary, the best that I can guess at what happened is that, somehow, `PiratesNorth.esp` got added to `DynDOLOD.esm`'s master files list & its ESM flag got removed at some point before or during step 5. If `PiratesNorth.esp` didn't have an ESM flag to begin with, DynDOLOD shouldn't have added it as a master to `DynDOLOD.esm`. If you can reproduce that, then that's definitely something worth reporting to them, but we can't do anything about it. Also, if it somehow did have `PiratesNorth.esp` as a master, you would've gotten this cyclic interaction much earlier.

Since you didn't regenerate DynDOLOD after installing the version of `PiratesNorth.esp` with the ESM flag, regardless of whether `DynDOLOD.esm` had `PiratesNorth.esp` as a master, you shouldn't have gotten that specific cyclic interaction from this. `DynDOLOD.esm` would've been able to load after `PiratesNorth.esp` with no problem as there are no longer two different hard-coded rules forcing each plugin to load after the other.

If this is just a one-off issue, then it's most likely the fault of some weirdness unrelated to LOOT (i.e., `DynDOLOD.esm` somehow having `PiratesNorth.esp` as a master & `PiratesNorth.esp` somehow losing its ESM flag without you noticing, maybe from some automated tool or manually by accident), so just make sure to regenerate DynDOLOD when any changes (at the very least, major ones like this) are made to your load order & we'll close this issue. If, however, you can reliably reproduce the issue, then we'll need more info to investigate (a debug log at least) as we can't reproduce it with what's given.

**Comment by sibir-ine** [comment] 2021-06-26 12:25
@Dreifels Were you able to reproduce the error? If not, we'll close this issue as there's not much else we can really do.

**Comment by Dreifels** [comment] 2021-06-26 14:14
don't have these files related anymore but later versions only.
BTW: it is correct that my LOOT never shows if a file is unclean? (except if I reinstall the original vanilla files by new downloading from Steam, these get notice)

**Comment by sibir-ine** [comment] 2021-06-26 14:24
@Dreifels 
> don't have these files related anymore but later versions only.

Got it, I'll close the issue then.

> BTW: it is correct that my LOOT never shows if a file is unclean? (except if I reinstall the original vanilla files by new downloading from Steam, these get notice)

This is probably better discussed in the Discord or at the official forum thread (both links can be found out our [website](https://loot.github.io/)) than in this issue. However, briefly, if a cleaning report for a mod wasn't added to the masterlist manually, LOOT cannot tell if it's dirty or not. This data also depends on the checksum of the file for which the cleaning report was generated, so, if you have a version of the mod we don't have a cleaning report for (e.g., an older version of the mod, a translation) or if you manually edit it, the cleaning report cannot be displayed. If you have any further questions, please do ask on our Discord or at our official forum thread.

**Closed by sibir-ine** 2021-06-26 14:24 UTC
Labels: awaiting-feedback
