### ISSUE TITLE
Make metadata copied via Copy Metadata function stylistically consistent with masterlists

### ISSUE THREAD

**Issue by Scythe-Bearer** [loot/loot#1733] opened 2022-03-25 18:21 UTC
Feedback, actually.  

I went through the process of using the app (Version 0.18.2) to add Metadata to some of the mods I support.  I then used the "Copy Metadata" function to extract the data and prepare it for inclusion in the MasterList.  

But alas, the data "copied" was not all the Data necessary for inclusion in the Masterlist, nor was it formatted in the manner the update process requires.  

My suggestion, make the data collection and reporting between the app and the Masterlist update process consistent, thus removing the need for intermediate editing and reformatting.   

Thank you for your consideration.

**Comment by sibir-ine** [comment] 2022-03-26 03:24
After some quick testing, the main stylistic differences between what's copied with LOOT's _Copy Metadata_ function & what's in the masterlists are:

* indentation
* the `url` key is at the bottom instead of between `name` & `group`
* single-element maps aren't written in flow style
* letters in raw hexadecimal numbers (i.e., `crc` values for cleaning data) aren't capitalized
* leading zeroes in raw hexadecimal numbers are trimmed

I believe the _Copy Metadata_ function copies the raw YAML data for the selected plugin, so I'm not sure how complicated it would be to reformat that data before sending it to the clipboard. If it's not worth the hassle, correcting it at review isn't difficult from the point of view of a maintainer. We make use of GitHub's suggestions wherever possible, so I hope it's not a big deal for contributors either, but your mileage may vary.

Every other stylistic issue (e.g., encouraging location names, trailing slashes for certain URLs where they don't break it) should be achievable within the metadata editor & are easily corrected at review as well.

One other thing I noticed that would be good to change too is writing the BBCode code & spoiler tags on their own lines before & after the copied metadata like below:

```
[spoiler][code]
name: 'Example.esp'
...
[/code][/spoiler]
```

**Comment by Ortham** [comment] 2022-03-26 09:19
> But alas, the data "copied" was not all the Data necessary for inclusion in the Masterlist, nor was it formatted in the manner the update process requires.

What data was missing? Please provide a before/after example of metadata copied by LOOT and what it looked like after you made the necessary manual adjustments.

**Comment by sibir-ine** [comment] 2022-03-26 10:37
I assume they're referencing https://github.com/loot/fallout4/pull/437. BellCube submitted metadata that Scythe Bearer provided using the _Copy Metadata_ function which required some manual adjustments for consistency before it could be merged. I think the missing data they are referencing is the location names & trailing slashes I asked for, but those can be added via the metadata editor & do show up if copied as previously stated (unless they ran into a different issue since that PR was submitted).

**Comment by Scythe-Bearer** [comment] 2022-03-26 18:04
Orhtam, 

> > But alas, the data "copied" was not all the Data necessary for inclusion in the Masterlist, nor was it formatted in the manner the update process requires.
> 
> What data was missing? Please provide a before/after example of metadata copied by LOOT and what it looked like after you made the necessary manual adjustments.

sibir-ine has answered your question.  The PR he mentioned can identify the data which was missing/mis-formatted _in that particular instance_.   I am by  no means an expert, and I leave the identifying of data elements which are routinely missing/mis-formatted during the review process to you experts.  I am sure that sibir-ine can provide further examples of data elements found missing/mis-formatted.

**Comment by Ortham** [comment] 2022-03-27 09:01
I've made some changes to address most of the points sibir raised:

- The BBCode tags now appear on their own line in [this LOOT build](https://loot.jfrog.io/ui/native/loot/improve-copy-metadata/)
- The metadata formatting changes have been made in [this libloot build](https://loot.jfrog.io/ui/native/libloot/improve-copy-metadata/), just replace the loot.dll in the LOOT build above with that one.

I didn't change the indentation, because that's intentional - the metadata copied is a single object not a list entry because you're copying a single plugin's metadata, and so the YAML reflects that.

@sibir-ine Can you verify that metadata is now copied in the expected format?

**Comment by sibir-ine** [comment] 2022-03-27 09:19
Yup, just one last thing: the flow-style maps in the masterlists have a space for padding between the brackets & the quotes (e.g., `[ 'Example.esp' ]` instead of `['Example.esp']`), but _Copy Metadata_ prints them without the padding.

**Comment by Ortham** [comment] 2022-03-27 09:20
That's not something I can control.

**Comment by sibir-ine** [comment] 2022-03-27 09:21
That's fine then, everything thing else matches 👍

**Comment by Ortham** [comment] 2022-03-27 09:25
OK, closing this as the libloot change is done in loot/libloot@46c8b875dffbd8ffb38353cee2f75baad48fb7bc and the LOOT change is done in cfd2ae5f7f4ff13d08a6d8d4170ac5ecc357ec8b. I won't release a new version of libloot just for that change, but I'll do it before LOOT's next release.

**Closed by Ortham** 2022-03-27 09:25 UTC
Labels: enhancement, backend

**Comment by Scythe-Bearer** [comment] 2022-03-27 11:47
Hey, what about the user?  Don't I get a say about when it's fixed?

What about the missing data which isn't collected in the "edit metadata" interface in the app.  Should not the app prompt for this missing data before allowing the data to be saved.  

For example, there is no place to input the mod name as it is presented to the users.  Yet that data element was requested to be supplied when the Masterlist was updated.

**Comment by sibir-ine** [comment] 2022-03-27 12:12
As previously stated, location names can be entered using the metadata editor. Specifically, the field is to the right of the URL for each location:

![image](https://user-images.githubusercontent.com/69141501/160280215-d3ca79ae-17fe-4b00-b737-2f9cd58a45fb.png)

It's not a required field for locations, so that's why you can enter & save a location without entering a name. As for locations added to the masterlist, we only started encouraging contributors to add location names recently since we only recently integrated locations into the UI in a more formal manner (#989) & in a way that utilizes their names. They're not hard requirements to having your contributions accepted, they're just preferable to have & easy enough to suggest in a review. If someone added a bunch of locations but didn't have the time to add names, they can just be added at a later date.

Otherwise, are there any other inconsistencies you noticed that we missed? Or did you try the LOOT & libloot snapshots & they didn't act as expected? If not, as Ortham said, the changes have made (save for a slight limitation aforementioned) & will be present in the next version, so the issue can be considered fixed.

**Comment by Ortham** [comment] 2022-03-27 12:35
> Hey, what about the user? Don't I get a say about when it's fixed?

If you think it isn't fixed then you can say so, but if sibir confirms it's fixed that's good enough for me, I only need one confirmation.

> What about the missing data which isn't collected in the "edit metadata" interface in the app. Should not the app prompt for this missing data before allowing the data to be saved.

No, because the user might not care about it, e.g. because the metadata they're adding isn't intended for inclusion in the masterlist later.

**Comment by Scythe-Bearer** [comment] 2022-10-11 07:08
My request is not to make things "stylistically"  or "cosmetically"
consistent, and your implication that I am concerned about the appearance
of the data is demeaning.

My request is one of functional consistency between the metadata input via
the app, what is extracted with the Copy Metadata function and what is used
as input into the process to update the Masterlist.  The mere fact that the
data extracted via the Copy Metadata function needs to be modified and/or
have additional data elements added after submission is a strong indication
that the data is not functionally complete or consistent between what is
input, what is extracted via the "Copy Metadata" function, and what is
expected as input to the process to update the masterlist.

What I am requesting is actually quite simple.  The data input via the app
= the data extracted via the copy metadata function = the data input to the
process to update the masterlist.  Currently, data elements required as
input to the process to update the masterlist are not required via the
app.  The formatting of some data elements used in the process to update
the masterlist is not the format which is required at input via the app.
Thus, the need for human intervention and the attendant human error.

My reasoning is basically that having what is extracted with the "Copy
Metadata" function capable of being input directly into the MasterList
update process without further modification would reduce (or potentially
eliminate) the necessity for edits, and greatly reduce the time necessary
for review.

**Comment by Ortham** [comment] 2022-10-11 07:14
@Scythe-Bearer The improvements made so far shipped in LOOT v0.18.5. Rather than describing the issue in general terms (which I understand but is hard to act on), could you give some specific examples of what you think still needs improvement?

**Comment by Scythe-Bearer** [comment] 2022-10-11 09:02
Thank you for the contact, but, given that this ticket is closed, any
further discussion is moot.

**Comment by Ortham** [comment] 2022-10-11 09:14
The ticket is closed because as far as I'm aware the issue is fixed - none if your replies since the issue was closed have indicated what (if anything) is still wrong. If the issue is still unresolved then please say so (with some actionable detail) and then I can re-open the ticket.
