### ISSUE TITLE
"Updating and parsing masterlist" infinite?

### ISSUE THREAD

**Issue by Synthpotato** [loot/loot#755] opened 2017-01-26 15:31 UTC
hi im having a problem where after i press sort load order it just says "Updating and parsing masterlist" and doesnt end, This problem started after i updated LOOT from a very old version to the latest one after i restarted my pc i tried sorting my load order and this problem started, im using mod organzier and launching loot from there btw, (windows 10)

**Comment by WrinklyNinja** [comment] 2017-01-26 19:09
Running LOOT through Mod Organiser is unsupported, as

1. Mod Organiser itself is unsupported
2. Most issues reported by Mod Organiser users are caused by Mod Organiser, which I can't do anything about.

Please try to replicate your issue while running LOOT independently of Mod Organiser.

**Comment by EsOmEs** [comment] 2017-01-27 11:40
I had the same issue. I ran LOOT without triggering it through MO2. It updated masterlist and git files sucessfully. After that it also worked through MO2.

Hope that helps.

**Comment by Synthpotato** [comment] 2017-01-27 20:08
@EsOmEs That worked thanks man!

**Comment by WrinklyNinja** [comment] 2017-01-27 20:10
Closing this then.

**Closed by WrinklyNinja** 2017-01-27 20:10 UTC
