### ISSUE TITLE
Sorting by name

### ISSUE THREAD

**Issue by selsie** [loot/loot#1815] opened 2022-10-23 12:04 UTC
When I open the plugins list, there are 3 headers: Position, Index, Plugin Name.
When I click on them to just sort the view of the files, nothing happens.

It would be good to be able to view the list of mods sorted by name too, for adding plugins to groups it is much easier to find them.

**Comment by sibir-ine** [comment] 2022-10-23 12:12
Duplicate of #1769

**Closed** 2022-10-23 12:12 UTC
Labels: duplicate
