### ISSUE TITLE
Windows cannot access LOOT.exe

### ISSUE THREAD

**Issue by herzer1234** [loot/loot#589] opened 2016-06-22 00:34 UTC
I'm having trouble. Its been awhile since I played skyrim so I deleted everything and want to start over and when I went to grab LOOT and tried to start it this is what I got.( after deleteing the appdata local file. ) Before this it told me Access denied code 5

![2016-06-21](https://cloud.githubusercontent.com/assets/20077480/16250993/2806819a-37f0-11e6-9d05-808223709a46.png)

Please help me I'm going 7 hours stumped on this.. I deleted the appdata local file like I saw in other posts but it didn't work

**Comment by WrinklyNinja** [comment] 2016-06-22 05:12
Have you checked your permissions for the Program Files (x86) folder? That looks like a generic Windows error message.

**Comment by herzer1234** [comment] 2016-06-22 18:30
I am the owner of this computer and only one who uses it. How do I not have permission?

**Comment by WrinklyNinja** [comment] 2016-06-22 18:41
I don't know, I'm just going by what the error message suggests.

**Comment by RenegadeCoder** [comment] 2016-06-24 21:26
Classic issue: things installed in the "Program Files" or "Program Files (x86)" directories are automatically protected by Windows, so you need to explicitly run the program with elevated privileges (run as administrator).

**Comment by herzer1234** [comment] 2016-06-25 02:12
I'll try it as soon as I get home I'm at work. Will post results.

**Comment by herzer1234** [comment] 2016-06-25 20:41
Nothing worked

**Comment by WrinklyNinja** [comment] 2016-11-15 07:29
Does this still happen with the v0.10.1 release?

**Comment by WrinklyNinja** [comment] 2016-11-18 18:14
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.

**Closed by WrinklyNinja** 2016-11-18 18:14 UTC
Labels: awaiting-feedback
