### ISSUE TITLE
"oh no something went wrong!"

### ISSUE THREAD

**Issue by AfroNinjaJesus** [loot/loot#842] opened 2017-11-26 06:17 UTC
when i installed and opened loot for the first time (on mod organizer) it showed a red message that told me something was wrong and to check my debug files. so i tried opening loot independently and got the same message. i tried uninstalling and reinstalling but the same error popped up. this is my first time trying to mod anything (skyrim special edition) so i am very new to this. 
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1503682/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1503683/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1503684/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2017-11-26 09:08
Looks like something got corrupted: `[22:09:02.982302] [error]: Git operation failed. Details: -1; Corrupted loose reference file: HEAD: libgit2 error`.

Try deleting your `%LOCALAPPDATA%\LOOT\Fallout4` folder.

**Comment by AfroNinjaJesus** [comment] 2017-11-27 01:38
I dont have that folder

**Comment by AfroNinjaJesus** [comment] 2017-11-27 02:08
*update* so i tried just loading loot through fallout. then switching to skyrim special edition. this still game me an error message but it would show my installed plugins and let me sort and save my load order. idk if this will work or if there is a way to not get the error message but as far as i can tell this might work

**Comment by WrinklyNinja** [comment] 2017-11-27 09:02
> I dont have that folder

If you didn't have that folder, a lot more would be going wrong. It's the same as `C:/Users/Joshua/AppData/Local/LOOT/Fallout4`. Just delete the whole LOOT folder.

**Comment by WrinklyNinja** [comment] 2017-12-08 20:22
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed by WrinklyNinja** 2017-12-08 20:22 UTC
Labels: awaiting-feedback

**Comment by Gates6689** [comment] 2017-12-21 05:05
Hello I had updated to the newest version of loot and now none of the mods i had for FONV show up and it says "Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information."

I did so and this is the what it said. I am new to using loot so not sure what i am doing wrong that its having issues just from updating. And help will be appreciated.

[23:04:17.813873] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:04:20.912026] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:04:24.951235] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3

**Comment by Gates6689** [comment] 2017-12-21 05:11
Tired a different method of installation and this is what the debug text said.

[23:04:17.813873] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:04:20.912026] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:04:24.951235] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:02.384852] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.
[23:10:03.454976] [error]: Failed to sort plugins. Details: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:07.795009] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.
[23:10:08.870632] [error]: Failed to sort plugins. Details: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:11.405973] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.

**Comment by Frikster** [comment] 2018-01-20 22:55
I had the same issue. Deleting C:/Users/Joshua/AppData/Local/LOOT/Fallout4 fixed the issue thanx.

**Comment by CreHater** [comment] 2018-02-08 11:42
I had the same issue. The reason was that Fallout was still running. In the Task Manager, the task was closed, but there still was a process running. The LOOT cannot save the sorted list.
Just open the Task Manager and select 'More Details' at the bottom. Then scroll down to the Fallout process, select it and hit delete. You do not have to close LOOT when doing this. As soon as the process is stopped, you can hit APPLY.

**Comment by WrinklyNinja** [comment] 2018-02-08 13:50
It looks like there are a few different issues being reported here: "oh no something went wrong!" is a generic error message, I see a few underlying causes in the comments above:

- `Git operation failed. Details: -1; Corrupted loose reference file: HEAD: libgit2 error`: Something corrupted the masterlist repository, delete the`%LOCALAPPDATA%/LOOT/<game>/.git` folder to recreate it.
- `FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3`: See #858, `FreesideOpen - NewVegasBountiesIII.esp` is corrupt.
- `Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.`: not sure about this one, may be related to the corrupt plugin.
- Fallout running with LOOT open: LOOT can't save the load order while it's open in Fallout (or any other game), this is not an issue, don't try making load order changes with the game running.

If you've found this issue because you've searched for "oh no something went wrong!", don't post here if it's not one of the above causes, file a new issue instead.

**Comment by CaiqueSell** [comment] 2018-08-04 06:03
I had the same issue. Deleting C:/Users/Joshua/AppData/Local/LOOT/Fallout4 fixed the issue thanx.
