### ISSUE TITLE
Fallout 4 VR cant optimize load order

### ISSUE THREAD

**Issue by caliburn2003** [loot/loot#960] opened 2018-06-02 20:23 UTC
LOOT is giving me an error on trying to organize my FO4VR load order... before you ask, no my plugins.txt isnt read only. here is from my Debug Log:

[16:19:53.140675] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[16:19:53.140807] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[16:19:53.141651] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\XXXXXX\AppData\Local\Fallout4VR\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)

**Comment by caliburn2003** [comment] 2018-06-02 20:27
oh sorry ok here you go
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2065338/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment] 2018-06-02 20:30
You don't have debug logging enabled.

**Comment by caliburn2003** [comment] 2018-06-02 20:31
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2065343/LOOTDebugLog.txt)
 is that better?

**Comment by WrinklyNinja** [comment] 2018-06-02 20:43
Yes, but I see

```
[16:31:33.694895] [info]: 		Fallout4.esm
[16:31:33.694907] [info]: 		DLCRobot.esm
[16:31:33.694917] [info]: 		DLCworkshop01.esm
[16:31:33.694926] [info]: 		DLCCoast.esm
[16:31:33.694935] [info]: 		DLCworkshop02.esm
[16:31:33.694947] [info]: 		DLCworkshop03.esm
[16:31:33.694955] [info]: 		DLCNukaWorld.esm
[16:31:33.694964] [info]: 		Fallout4_VR.esm
```

When I added Fallout 4 VR support, [I was told](https://github.com/loot/loot/issues/869#issuecomment-362825258) that the Fallout 4 DLC weren't in the VR version. I don't own it myself, so I can't check, but is that wrong? How come you've got the DLC plugins?

**Comment by caliburn2003** [comment] 2018-06-02 20:48
because you can move them over into the VR folder just fine... the only thing is you have to use the pancake version to use the robot workbench otherwise it all works fine... there was a whole google doc of mods that work with VR. the DLCs were included.

**Comment by caliburn2003** [comment] 2018-06-02 20:51
you dont have to but you can put them in

**Comment by WrinklyNinja** [comment] 2018-06-02 20:54
OK, I think this is a metadata issue then. What happens if you add user metadata so that DLCRobot.esm loads after Fallout4_VR.esm?

**Comment by caliburn2003** [comment] 2018-06-02 20:56
it doesnt want to sort my load order now says no changes made... think that was the issue?

**Comment by caliburn2003** [comment] 2018-06-02 21:04
oh and while i have you here it seems that Skyrim VR is expecting the Skyrim SE version of Script Extender... there is a separate Script Extender for VR... it pops up as an error... just figured id give you a heads up

**Comment by WrinklyNinja** [comment] 2018-06-02 21:09
> it doesnt want to sort my load order now says no changes made... think that was the issue?

Yes, the error was because the Fallout4_VR.esm wasn't loading directly after Fallout4.esm. This is basically a duplicate of #956.

> oh and while i have you here it seems that Skyrim VR is expecting the Skyrim SE version of Script Extender... there is a separate Script Extender for VR... it pops up as an error... just figured id give you a heads up

What do you mean? As far as I'm aware LOOT will only show messages for SKSE64 for Skyrim SE and only for SKSEVR for Skyrim VR.

**Comment by caliburn2003** [comment] 2018-06-02 21:15
well my loot says its asking for SKSE64 in my Skyrim VR. not a huge deal because I keep mine up to date but I figured id let you know

**Comment by caliburn2003** [comment] 2018-06-02 21:16
![screenshot 6](https://user-images.githubusercontent.com/30640878/40880940-a78f7282-6688-11e8-8fc2-ea41164e4936.png)

**Comment by caliburn2003** [comment] 2018-06-02 21:17
![screenshot 7](https://user-images.githubusercontent.com/30640878/40880949-ddd1b24c-6688-11e8-8551-aa4f54246e71.png)

**Comment by WrinklyNinja** [comment] 2018-06-02 21:40
As far as I can see, Achievements Mods Enabler is an SKSE64 plugin, and there's no version available for SKSEVR. I don't know if it actually works for you with SKSEVR, but trying to run it like that doesn't seem like a very good idea to me.

**Closed** 2018-06-02 21:41 UTC
Labels: duplicate

**Comment by caliburn2003** [comment] 2018-06-02 21:45
achievement mods enabler works just fine as far as i can tell
