### ISSUE TITLE
Search Cards arrows not functioning properly

### ISSUE THREAD

**Issue by MlemandPurrs** [loot/loot#1405] opened 2021-01-23 13:05 UTC
When using the search cards function you can click those ^ v up down arrows and it highlights the item but doesnt jump to where it is in the listing.

**Comment by pStyl3** [comment] 2021-01-23 15:36
Which version of LOOT do you use? Can you enable full debug logging in LOOTs settings and post your LOOTDebugLog.txt according to [How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by MlemandPurrs** [comment] 2021-01-23 19:07
ok here is log:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/5860870/LOOTDebugLog.txt)
![blergh](https://user-images.githubusercontent.com/48881353/105611568-22e15580-5dc7-11eb-9b69-eb204830a627.gif)
also nevermind as i have figured what it is: 
the filters hide settings dont play nice with search, to obtain best result turn off all then search as its still jumping to an otherwise hidden plugin's place in the list. in the gif i had 'hide inactive plugins' toggled on so the first time its gone to show that.

**Comment by pStyl3** [comment] 2021-01-24 14:11
@Ortham I can confirm this issue. With `Hide inactive plugins` the `Search Cards` feature is kind of wonky, it doesn't accurately jumps to the appropriate plugins.

Also, with `Hide messageless plugins` enabled, the search may find results, even though their cards are hidden.

**Comment by Ortham** [comment] 2021-01-24 15:01
Search is supposed to only operate on visible text, so something's gone wrong here. @MlemandPurrs thanks for the report, and @pStyl3 thanks for replicating it.

**Comment by Ortham** [comment] 2021-01-30 09:23
This should be fixed as of 9bb8e5716cf96a941054e7c08bd4de45213dff80, snapshot builds [here](https://bintray.com/loot/snapshots/loot/0.16.0-70-g1694710_fix-search#files).

**Comment by pStyl3** [comment] 2021-01-30 10:52
Using `loot_0.16.0-70-g1694710_fix-search-win32.7z` I no longer can replicate the issue. It seems to be fixed.

**Closed** 2021-01-30 11:31 UTC
Labels: bug
