### ISSUE TITLE
Cyclic interaction detected between plugins "Change Follower Outfits Redux.esp" and "Change Follower Outfits Redux -- Dawnguard.esp". Back cycle: Change Follower Outfits Redux -- Dawnguard.esp, Change Follower Outfits Redux.esp

### ISSUE THREAD

**Issue by Thejiffiness** [loot/loot#828] opened 2017-09-30 06:42 UTC
Cyclic interaction detected between plugins "Change Follower Outfits Redux.esp" and "Change Follower Outfits Redux -- Dawnguard.esp". Back cycle: Change Follower Outfits Redux -- Dawnguard.esp, Change Follower Outfits Redux.esp

https://www.nexusmods.com/skyrim/mods/23798/?tab=4&&navtag=https%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fcomments%2F%3Fmod_id%3D23798%26page%3D1%26sort%3DDESC%26pid%3D0%26thread_id%3D777827&pUp=1

Was not doing this until recently as far as I am aware. Never had this problem before.

**Comment by pStyl3** [comment] 2017-09-30 08:25
I can reproduce this. This is LOOT's metadata for this Skyrim plugin:

> - name: 'Change Follower Outfits Redux.esp'
    after:
      - 'Lively Followers.esp'
      - 'Thieves Guild Followers and Spouses.esp'
    req:
      - name: 'Change Follower Outfits Redux -- Lively Followers Compatability.esp'
        display: '[Lively Followers Compatibility Patch](http://www.nexusmods.com/skyrim/mods/23798/)'
        condition: 'active("Lively Followers.esp")'
      - name: 'Change Follower Outfits Redux -- USKP 1.2 Farkas Compatability.esp'
        display: '[USKP Compatibility Patch](http://www.nexusmods.com/skyrim/mods/23798/)'
        condition: 'active("Unofficial Skyrim Patch.esp")'
      - name: 'Change Follower Outfits Redux -- Dawnguard.esp'
        display: '[Dawnguard Compatibility Patch](http://www.nexusmods.com/skyrim/mods/23798/)'
        condition: 'active("Dawnguard.esm")'
      - name: 'Change Follower Outfits Redux -- Hearthfire.esp'
        display: '[Hearthfire Compatibility Patch](http://www.nexusmods.com/skyrim/mods/23798/)'
        condition: 'active("Hearthfires.esm")'
      - name: 'Change Follower Outfits Redux -- Dragonborn.esp'
        display: '[Dragonborn Compatibility Patch](http://www.nexusmods.com/skyrim/mods/23798/)'
        condition: 'active("Dragonborn.esm")'


The plugins have the following masters:

Change Follower Outfits Redux.esp
Skyrim.esm, Update.esm

Change Follower Outfits Redux -- Dawnguard.esp
Skyrim.esm, Update.esm, Dawnguard.esm, Change Follower Outfits Redux.esp

Change Follower Outfits Redux -- Hearthfire.esp
Skyrim.esm, Update.esm, HearthFires.esm, Change Follower Outfits Redux.esp

Change Follower Outfits Redux -- Dragonborn.esp
Skyrim.esm, Update.esm, Dragonborn.esm, Change Follower Outfits Redux.esp

**Comment by WrinklyNinja** [comment] 2017-09-30 08:35
Right, so we should make those last three into "also use X" messages, because though they're required they're not required to load before `Change Follower Outfits Redux.esp`.

Maybe it's worth adding a special check to make it so that if A has B as a req but B has A as a master, LOOT doesn't try to put B before A. It introduces an inconsistency, but perhaps it would be neater overall...

**Comment by WrinklyNinja** [comment] 2017-09-30 08:43
Fixed in [91c67121ceefd5cdc3e4806991532c99e7e99674](https://github.com/loot/skyrim/commit/91c67121ceefd5cdc3e4806991532c99e7e99674).

**Closed by WrinklyNinja** 2017-09-30 08:43 UTC
