### ISSUE TITLE
Unknown Error trying to sort load order

### ISSUE THREAD

**Issue by AHamsterPig** [loot/loot#783] opened 2017-05-23 08:23 UTC
I've been using Loot for all my mods and just ran into this error out of nowhere after reinstalling a mod for Fallout 4: Details: "C:\Users\Tyler\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error: Libloadorder error

**Comment by WrinklyNinja** [comment] 2017-05-23 09:39
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). In particular the bit about debug logs.

**Comment by nico4544** [comment] 2017-08-22 18:05
I had the same problem. But it worked fine when Nexus Mod Manager was running at the same time as i tried sorting them. Not sure if that's you problem, but you could try. :) 👍

**Comment by Jtreu** [comment] 2017-08-22 18:45
You've probably already done this, but In case you haven't: 
1. Navigate to C:\Users\Tyler\AppData\Local\Fallout4
If plugins.txt IS there, right click on properties and make sure read only is unchecked.
If it IS NOT there, then there is a problem because you have it on a different drive or a different directory.

**Comment by WrinklyNinja** [comment] 2017-12-08 20:22
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed by WrinklyNinja** 2017-12-08 20:22 UTC
Labels: awaiting-feedback
