### ISSUE TITLE
Loot application opens as background process then closes

### ISSUE THREAD

**Issue by Chaoticity** [loot/loot#786] opened 2017-06-05 00:03 UTC
Clean install, all loot files removed from _appdata\local_ and install folder. LOOT version is v0.11.0 from the Skyim SE Nexus.

When the loot application is run it appears as a background process for around a second in Task Manager then disappears. It generates an _appdata\local\LOOT_ folder but it is completely empty, so no logs to attach.

LOOT is installed to _D:\Programs\LOOT_ with Windows on my C: drive so it shouldn't be affected by UAC. Just to make sure I've allowed it through the Windows Firewall, and disabled/removed all anti-virus software for the moment.

I have Fallout 4 and Skyrim SE installed to _D:\Programs\Steam\steamapps\common_ if that helps.

The last time I used LOOT was about a month ago and it worked, albeit an earlier version.

**Comment by Chaoticity** [comment] 2017-06-05 00:11
I've just run LOOT through MO2 for Fallout 4 (I know it's unsupported) and it generated an _appdata\local\LOOT\Fallout4_ folder that contains a .git folder and masterlist.yaml. [I've uploaded the Fallout 4 folder if you need it.](https://github.com/loot/loot/files/1050812/Fallout4.zip)

It couldn't sort any plugins because it closed two seconds after "preparing VFS" finished.

Masterlist.yaml is strange because it contains plugins from mods that I have not currently got installed.

**Comment by WrinklyNinja** [comment] 2017-06-05 06:56
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html), in particular the bit under the "If you can't reach the settings dialog" heading. You don't have a `settings.yaml`, so won't be replacing `enableDebugLogging: false`, just adding a new file with just one line, but the process is still roughly the same.

**Comment by Chaoticity** [comment] 2017-06-05 07:11
I created settings.yaml and ran LOOT [and this is what I got](https://github.com/loot/loot/files/1051321/LOOTDebugLog.zip)

**Comment by WrinklyNinja** [comment] 2017-06-05 07:16
There weren't any other log files?

**Comment by Chaoticity** [comment] 2017-06-05 07:17
That was the only one it generated. I renamed it to LOOTDebugLog1.txt and ran it again to make sure but it just made the same one again.

I have view hidden items enabled so as far as I can tell it didn't add anything else.

**Comment by WrinklyNinja** [comment] 2017-06-05 15:30
Hmm... Does LOOT [v0.10.3](https://github.com/loot/loot/releases/tag/0.10.3) work?

**Comment by Chaoticity** [comment] 2017-06-06 09:57
Yes, on a clean install v0.10.3 worked immediately. It recognised all games I have installed and is listing all plugins correctly. I don't know if you need them, but [I've uploaded both debug logs that were created.](https://github.com/loot/loot/files/1054505/Logs.zip)

**Comment by WrinklyNinja** [comment] 2017-06-06 19:57
I can't really see why it would be crashing, especially so early during initalisation. You're not using any symlinks/hardlinks/junction links, are you? This crashing occurs when you run LOOT directly, not through any mod manager?

**Comment by Chaoticity** [comment] 2017-06-06 20:01
I'm not using any symbolic links or anything like that, v0.11.0 crashed almost immediately when ran directly. The older version works perfectly though

**Comment by Freso** [comment] 2017-07-10 15:31
@Chaoticity What Windows version are you on? If Windows 10, are using the Insider Program?

**Comment by micmou** [comment] 2017-07-11 07:40
http://i.imgur.com/8gQ8xFR.jpg

It is 1703 15063.413

For me

**Comment by Chaoticity** [comment] 2017-07-11 16:59
I'm using version 1703, build 15063.447

**Comment by VisionaryLion** [comment] 2017-07-18 21:59
I'm having the same problem as well. For now just using the previous version which seems to work perfectly fine.

**Comment by eyezack** [comment] 2017-09-17 18:18
I was having the same issue until I rolled back to 10.3

Windows 7 SP 1 Professional x64 bit

**Comment by WrinklyNinja** [comment] 2017-09-18 06:56
Could anyone experiencing this issue please try using the [latest snapshot build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-40-gf1e4c4f_dev) and let me know if it works or not.

**Comment by Ghostwalker71** [comment] 2017-09-19 00:57
This is very likely due to antivirus software triggering a false positive and shutting down the process. It happened to me until I white listed the exe, and it happens with almost every new exe file when LOOT is updated.

**Comment by oblivion2k** [comment] 2017-09-30 01:18
> You're not using any symlinks/hardlinks/junction links, are you?

To confirm, these would cause this issue, and I need to move my Fallout 4 installation the hard way if I'm going to do so?

**Comment by WrinklyNinja** [comment] 2017-09-30 08:28
> To confirm, these would cause this issue, and I need to move my Fallout 4 installation the hard way if I'm going to do so?

No, LOOT should work with filesystem links but support is sparsely tested and people have encountered issues while using them in the past, so it's worth knowing when debugging.

**Comment by oblivion2k** [comment] 2017-09-30 08:34
> No, LOOT should work with filesystem links but support is sparsely tested and people have encountered issues while using them in the past, so it's worth knowing when debugging.

Ah, understood. I was receiving OP's error, but my background process would last about 10 seconds before closing itself, and it was only an issue once I created symlinks via SteamMover. Currently in the process of rebuilding my mods folder after moving everything over the hard way. I'll test to verify that it's fully functional again and update with results.

**Comment by johnthinc** [comment] 2017-10-08 15:20
I can confirm that this issue happens with symlinked directories.  I only began experiencing this issue after I moved Skyrim SE directory to my SSD and symlinked back to my original install directory.  10.3 loads and sorts just fine however it won't save the load order after sorting.

**Comment by WrinklyNinja** [comment] 2017-10-08 17:12
> I can confirm that this issue happens with symlinked directories. I only began experiencing this issue immediately after I moved Skyrim SE directory to my SSD and symlinked back to my original install directory. 10.3 loads and sorts just fine however it won't save the load order after sorting.
> 
> Hope this helps narrow down the issue. Just let me know if you need anything else from me.

Does the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-40-gf1e4c4f_dev.7z) work?

**Comment by alchmo** [comment] 2017-10-09 11:42
Latest snapshot works fine, i even went overboard, and "installed" LOOT on a symbolic link drive, and Fallout4 is installed on another symbolic link drive

**Comment by WrinklyNinja** [comment] 2017-10-09 13:15
Great, I will close this as fixed then. If anyone still experiences the issue, it can be re-opened.

**Closed by WrinklyNinja** 2017-10-09 13:15 UTC
Labels: bug
